### ISSUE TITLE
wololo.net

### ISSUE THREAD

**Issue by BlazDT** [yous/YousList#103]
http://wololo.net/

<img width="888" alt="wololo net" src="https://user-images.githubusercontent.com/34266271/57181474-83fb2400-6e94-11e9-89a4-c54d38365525.png">

Broken site layout, fix:

@@||cdn.wololo.net^

**Comment by yous** [comment]
It seems that there is no rules blocking `cdn.wololo.net` in this filter. I see the site with fine layout with YousList enabled. And I don't see any requests to `cdn.wololo.net` from wololo.net, is it just for me?

I checked on Safari:
- http://wololo.net
- http://wololo.net/2019/05/02/switch-news-linux4tegra-ubuntu-with-audio-vulkan-and-docking-support-released-reicast-dreamcast-emulator-gets-aarch64-dynarec-support-which-will-improve-performance-on-the-switch-and-nintendo-bri/

**Comment by BlazDT** [comment]
*/detroitchicago/edmonton.webp^
*/porpoiseant/jellyfish.webp^

These two rules are in Youslist. I noticed for layout this rule is enough (which was displayed before with YousLIst, now with AdGuard Base filter: @@||cdn.wololo.net/utilcave_com/templates/combine.php

After checking the two blocked request it seems one is used for ads, the other one for sharing options:
http://cdn.wololo.net/detroitchicago/edmonton.webp?dirname=wololo_net&cb=184-3

**Comment by yous** [comment]
Sorry for the late response, but as far as I can see, the script of <http://cdn.wololo.net/detroitchicago/edmonton.webp?dirname=wololo_net&cb=184-3> tracks events of page, sharing buttons, etc. The function `D()` returns every sharing buttons or links, and then it calls addEventListener for click event to each element.

Also sharing links seem to work without whitelisting this script, so let's see whether there are some breakages or not.

**Comment by yous** [comment]
Closing now. Feel free to open an issue when there is a problem or you see advertisements.
