### ISSUE TITLE
adbnMobileBanner 문제

### ISSUE THREAD

**Issue by newget** [yous/YousList#105]
||mediacategory.com/servlet/adbnMobileBanner^

adguard 로그를 보면 차단은 제대로 되었다고 나오는데 자꾸 adbnMobileBanner라는 파일을 다운 받습니다.

여기 첨부는 안 되는데 파일을 텍스트뷰어로 열어보니 2 라고만 적혀있네요.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 문제가 발생하는 URL을 알 수 있을까요?

**Comment by newget** [comment]
URL은 모르겠습니다. 최근엔 받아지는 일이 없는데 저번달에 이게 생겼던게 어디 주소였는지 모르겠습니다.

**Comment by yous** [comment]
네, 혹시 현상이 다시 발생하면 알려주세요.
