### ISSUE TITLE
애드블록 사용시 매일경제 신문 큰제목 사라지는 현상이 있습니다.

### ISSUE THREAD

**Issue by wuxing22c** [yous/YousList#106]
안녕하세요!

애드블록 등 광고 차단 어플을 사용할 때
매일경제 사이트에서 
신문 기사 페이지에 
기사의 큰 제목이 사라지는 현상이 발생합니다.

이 부분에 있어 도움을 주신다면 감사하겠습니다!
감사합니다 ^^

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 PC에서 접속할 때 그런 현상이 발생하나요, 아니면 휴대폰에서 접속할 때 발생하나요?

방금 기사 하나에 대해 확인해보았는데, 제목이 사라지는 것 같지는 않습니다. 다음은 각각 PC와 모바일 환경에서 확인한 URL입니다.
- https://www.mk.co.kr/news/business/view/2019/05/365164/
- http://m.mk.co.kr/news/company/2019/365164/

제목이 사라지는 기사 URL 하나만 알려주시면 감사하겠습니다. 만약 위의 URL에서도 그런 현상이 발생하고 있다면, 다른 필터의 영향일 가능성도 있습니다.

**Comment by wuxing22c** [comment]
위 사진에 보이듯 제목이 잘려서 보이지 않습니다 ㅠ

일단 피씨에서 볼 떄 이러한 현상이 발생합니다만

제 기억에는 모바일로 볼 때도 동일한 현상이 발생했습니다

지금 제 크롬은 다른 확장프로그램은 적용하고있지 았습니다

감사합니다

강오성 배상

**Comment by yous** [comment]
uBlock Origin에서 확인해보니 EasyList 필터가 켜져 있으면 해당 현상이 발생하는 것을 확인했습니다. 만약 EasyList를 계속 쓰고 싶으시다면 사용자 필터에 다음을 추가해보세요.

```
mk.co.kr#@#.ad_header
```

**Comment by wuxing22c** [comment]
죄송하지만

사용자 필터는 무엇이고

여기에 무언가를 추가하려면 어떻게 해야하는 지 

조금 만 더 설명해주실 수 있으신지요? :)


위의 설명은 제가 모르는 말들입니다 ㅠㅠ

**Comment by yous** [comment]
![Screenshot 2019-05-30 19 21 48](https://user-images.githubusercontent.com/853977/58626621-31384f00-8310-11e9-9e0d-652906542582.png)

uBlock Origin 설정 페이지에 들어가면 위와 같이 켜져 있는 필터 목록이 나오고요, 여기에서 EasyList 등을 체크 해제하면 문제가 해결될 수 있습니다. Adblock Plus 등에도 비슷한 설정 페이지가 있을 겁니다.

<img width="859" alt="Screenshot 2019-05-30 19 23 45" src="https://user-images.githubusercontent.com/853977/58626749-7a889e80-8310-11e9-902c-256abaf052bc.png">

사용자 필터의 경우에는 uBlock Origin에서 '내 필터' 탭을 누르면 편집할 수 있고요, 위와 같이 `mk.co.kr#@#.ad_header`를 추가하시면 EasyList를 체크 해제하지 않아도 문제가 해결될 것으로 보입니다.

**Comment by wuxing22c** [comment]
와.... 정말 친절한 설명 감사합니다!잘 쓰겠습니다:)강오성 드림Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Chayoung You <notifications@github.com> Date: 5/30/19  7:25 PM  (GMT+09:00) To: yous/YousList <YousList@noreply.github.com> Cc: wuxing22c <wuxing22c@gmail.com>, Author <author@noreply.github.com> Subject: Re: [yous/YousList] 애드블록 사용시 매일경제 신문 큰제목 사라지는 현상이 있습니다. (#106) 

uBlock Origin 설정 페이지에 들어가면 위와 같이 켜져 있는 필터 목록이 나오고요, 여기에서 EasyList 등을 체크 해제하면 문제가 해결될 수 있습니다. Adblock Plus 등에도 비슷한 설정 페이지가 있을 겁니다.



사용자 필터의 경우에는 uBlock Origin에서 '내 필터' 탭을 누르면 편집할 수 있고요, 위와 같이 mk.co.kr#@#.ad_header를 추가하시면 EasyList를 체크 해제하지 않아도 문제가 해결될 것으로 보입니다.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yous/YousList/issues/106?email_source=notifications\u0026email_token=AMGSBL3644BJZCIDLL4HEFTPX6TRHA5CNFSM4HRALX2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWR7BXI#issuecomment-497283293",

"url": "https://github.com/yous/YousList/issues/106?email_source=notifications\u0026email_token=AMGSBL3644BJZCIDLL4HEFTPX6TRHA5CNFSM4HRALX2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWR7BXI#issuecomment-497283293",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
