### ISSUE TITLE
안녕하세요 쿨앤조이 광고차단 부탁드립니다.

### ISSUE THREAD

**Issue by swan201** [yous/YousList#109]
http://www.coolenjoy.net/
http://cooln.kr/

이렇게 두개의 사이트에서 광고차단 부탁드립니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/f8ac8a2b50a42529c6720b02bf88dc1303086e70 커밋에서 업데이트 했습니다.
