### ISSUE TITLE
필터 추가 요청

### ISSUE THREAD

**Issue by Fenslett** [yous/YousList#11]
웹서핑 도중, `<iframe>`을 이용해 특정 토렌트 사이트에 연결시키는 사이트를 발견했습니다.
불필요한 트래픽이 생기는데다가 광고마저 성인용인 경우가 많아 차단하고자 합니다.

해당 페이지 특성때문에 접근 자체가 차단되다보니, 여러 도메인가지고 돌려쓰고 있었는데요.
*tobest*나 *tosarang*, *yasarang*이라는 3개의 prefix가 붙는 것으로 확인되었습니다.

아예 해당 도메인을 차단해버리는 게 바람직하지 않을까 생각이 들었지만,
애드블럭 자체가 순수하게 광고 차단의 목적이니, 광고만 차단하는 필터를 만들었습니다.

```
||tobest*.net/img/
||tosarang*.net/img/
||yasarang*.net/img/
```

img 서브 디렉터리를 완전히 차단하는 터라, 일부 이미지가 누락되는 경우가 있지만(극히 일부입니다)
사이트 이용에는 문제가 없을 거라고 사료됩니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사드립니다. 만약 가능하시면 해당 광고가 보이는 URL을 하나만 알려주실 수 있을까요? 감사합니다.

**Comment by Fenslett** [comment]
http://tosarang2.net/ 으로 들어가시면 됩니다 ^^

**Comment by yous** [comment]
안녕하세요, 광고 영역만을 가리도록 업데이트 해봤는데, 한번 테스트 부탁드립니다.

**Comment by Fenslett** [comment]
필터링 정상 작동 확인했습니다.
그런데, 해당 사이트의 트위터 내역을 보면 *tosarangnew.net*이나 *tosarang22.net*와 같이 도메인이 지속적으로 바뀌고 있어서,
```
||tosarang*.net##div#left>div:not([class]):not([id]):not([style])>a
||tosarang*.net##div#right
||tosarang*.net##div.analytics_google
```

와 같이 전역 설정을 하는 게 좋지 않을까 생각이 들었는데, 어떻게 생각하시는지요?

**Comment by yous** [comment]
해당 트위터 내역에 나온 tosarang, tobest 관련 도메인을 모두 추가했습니다. 한번 확인 부탁드립니다.
