### ISSUE TITLE
rp5.ru - adblock detection

### ISSUE THREAD

**Issue by BlazDT** [yous/YousList#112]
https://rp5.ru/%D0%9F%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%91%D0%B0%D0%BB%D1%82%D0%B5,_%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0

Rule causes adblock detection:
##ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type])

Screenshot in first post:
https://github.com/AdguardTeam/AdguardFilters/issues/35046

**Comment by yous** [comment]
Thanks for the report! I added an exception for rp5.ru at <https://github.com/yous/YousList/commit/d2b25ba24d6f4de3675cb56e4ea3247739bf9e9d>.
