### ISSUE TITLE
tgd.kr 메인페이지 광고차단 부탁드립니다.

### ISSUE THREAD

**Issue by swan201** [yous/YousList#116]
https://tgd.kr/ -> 메인페이지 이미지

https://tgd.kr/saddummy -> 배너광고

오늘부터 신규로 도입된 것 같습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 다만 메인페이지 이미지의 경우 차단하면 이런 식으로 완전히 검은색이 되는데, 차단하는 게 더 나은 건지 잘 모르겠습니다.

<img width="1248" alt="Screenshot 2019-07-29 15 34 43" src="https://user-images.githubusercontent.com/853977/62026623-7694d200-b216-11e9-8fc9-e407ebe4a1e3.png">

**Comment by yous** [comment]
그 외의 광고는 https://github.com/yous/YousList/commit/1df4d422af37478ce82849433c71d515fe6f91af 커밋에서 업데이트했습니다.

**Comment by swan201** [comment]
그렇군요, 아예 이미지라서 따로 배경교체나 그런건 안되나보네요. 그냥 냅두는게 좋을 것 같습니다. 업데이트 감사합니다
