### ISSUE TITLE
tgd.kr 메인 js 차단 관련

### ISSUE THREAD

**Issue by SnorlaxH** [yous/YousList#117]
트게더 메인에서 불러오는 5f1b439bdf9bf52de0892c7e5bf81ffe.js 스크립트가
지난 7월 29일 commit에서 차단목록에 추가되었는데 혹시 어떠한 이유로 차단이 되었는지 알 수 있을까요??
해당 스크립트 차단으로 트게더 메인에서 단축키 기능이 동작하지 않아 확인해보니 애드블락 확장에서 막고있어서 문의드립니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 광고와 관련된 코드가 있어서 막았는데 다른 코드도 있었네요. 다시 제외하도록 하겠습니다.

**Comment by yous** [comment]
Closed via #118.
