### ISSUE TITLE
특정사이트 자사 광고 차단문의합니다

### ISSUE THREAD

**Issue by urtheuniverse** [yous/YousList#119]
![20190810_160257](https://user-images.githubusercontent.com/28980080/62818879-87cfce00-bb88-11e9-9fd6-94fc0f814dc9.jpg)
![20190810_160350](https://user-images.githubusercontent.com/28980080/62818880-8bfbeb80-bb88-11e9-821c-f8a540c7f375.jpg)

특정사이트에서 생긴 자사 광고입니다. 
각 각 의 카테고리마다 상단에 광고 및 글을 조회했을때 중간 쯤에 광고가 들어가는데 개인적으로 요소 차단을 하려하는데 잘 안되네요. 혹시 차단 가능할까요?

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/40ae316b3ddbe0edabf88405af744f40e7b9863d 커밋에서 업데이트 했습니다.

**Comment by urtheuniverse** [comment]
감사합니다!
