### ISSUE TITLE
네이버 tvcast

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#12]
uBlock 에서 사용할 때 tvcast에서 재생 전 영상광고가 필터링이 되고 어떤 건 안 되네요.
e.g. [http://tvcast.naver.com/v/826186](http://tvcast.naver.com/v/826186)

**Comment by yous** [comment]
안녕하세요, 제보 감사드립니다. 조금 들여다봤는데, <http://serviceapi.rmcnmv.naver.com/resources/js/rmcplayer3_launcher_20150820.js?20160412> 스크립트에서 광고 처리와 더불어 영상 재생을 담당하는 것 같습니다. 다만 광고 동영상의 주소를 막으면 재생할 수 없는 환경이라고 나오고, 광고가 재생된 후에 영상을 재생하는 로직이 있는 것 같아 우회하려면 더 깊이 들여다봐야할 것 같습니다.

**Comment by gtgvxinf** [comment]
||advod.smartmediarep.com^$third-party

**Comment by yous** [comment]
다음 줄을 추가하면 크롬에선 문제 없이 재생이 됩니다만, 사파리에서 해당 영상의 재생을 지원하지 않는다고 나오고 있어서 추가하지 못하고 있습니다.

```
||advod.smartmediarep.com/*.mp4^$third-party
```

**Comment by gtgvxinf** [comment]
Above rule also breaks the playback of videos in Firefox 48.0a2. Working fine with Edge and Chrome.

**Comment by gtgvxinf** [comment]
By the way, the rule Yous mentioned above is what I've posted here and removed shortly. Wouldn't it be better if you had acknowledged the person who suggested the rule?

**Comment by yous** [comment]
Yes, as subscribers had received via email, the above rule is suggested by @gtgvxinf. The rule is slightly modified, though, I thought there were some reasons to remove the comment. It would be better if I mentioned you. That was my short, sorry for that.

**Comment by gtgvxinf** [comment]
There are other ad sources, which can be blocked by the following rule.
`||ams.rmcnmv.naver.com`
I am not sure whether this rule is too broad or too narrow. Should take a look at it further.
This rule, too, makes some unexpected behavior with Firefox, but in this case videos are still playable.

**Comment by gtgvxinf** [comment]
It seems that the above rule will be good. By blocking ams.rmcnmv.naver.com, it does not send request to advod.smartmediarep.com anymore, also it does block some other advertisement videos that are not covered by blocking advod.smartmediarep.com. Please check whether it has any issues with Safari.

**Comment by gtgvxinf** [comment]
I was told that it is possible to eliminate those unexpected behavior by modifying VAST configuration that tvcast uses, but it seems that ublock does not support it.

**Comment by yous** [comment]
@gtgvxinf Thanks for investigating this issue. I tried `||ams.rmcnmv.naver.com/item` rule on Safari, but unfortunately it just shows loading bar and video won't be played. `||ams.rmcnmv.naver.com/item/create/2010/SMR^` rule also just blocks playing video.

**Comment by gtgvxinf** [comment]
I can confirm that this rule breaks the video playback with Safari :( Currently have no other idea.
It seems that [Korean Adblock list](https://github.com/gfmaster/adblock-korea-contrib) just added the rule `||ams.rmcnmv.naver.com^`. I'd like to mention that the rule `||ams.rmcnmv.naver.com/item/create/2010/SMR^` is not generic enough.

**Comment by yous** [comment]
That's right. I think we should wait until the issue with Safari disappears. Update of Naver's script, maybe? 😅

**Comment by yous** [comment]
안녕하세요, 최근 네이버 tvcast 주소가 tv.naver.com으로 바뀌면서 업데이트가 된 것 같네요. 필터링이 되는 것 같아 업데이트했습니다. https://github.com/yous/YousList/commit/5fdaf1075313ca957adc89dd41e1be47fb974f32 커밋에서 수정되었습니다.
