### ISSUE TITLE
다음 갤러리의 컨텐츠가 전혀 출력되지 않습니다.

### ISSUE THREAD

**Issue by ChiftKey** [yous/YousList#120]
예시의 페이지 입니다.

https://gallery.v.daum.net/p/viewer/978/Npj0tChzXu

광고만 차단되는 것이 아니라, 사이트 자체가 출력이 되지 않습니다.

사이트에서 나오는 출력물 (이미지, 텍스트)등 을 전부 광고로 인식하여 차단하는 것 같습니다.

감사합니다^^ 항상 잘쓰고 있어요

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 Fanboy's Social Blocking List를 함께 사용하고 계신가요? uBlock Origin에서 테스트해보니 다음 필터 때문에 사이트가 제대로 나오지 않는 것 같습니다.

```
/socialshare/*
```

위 필터를 끄시거나, 사용자 규칙에 다음 규칙을 추가하시면 잘 작동하는 것 같은데, 한번 확인해주세요.

```
@@||t1.daumcdn.net/daumtop_deco/socialshare/socialshare_*.js^$domain=gallery.v.daum.net
```

**Comment by ChiftKey** [comment]
답변 감사드립니다.
말씀하신대로 제 환경은
Windows10 Pro, Opera브라우저에서 uBlock Origin (1.21.6버전) 을 사용하고 있으며.

언급하신 `Fanboy's Social Blocking List`는 사용하고 있지 않은 상태입니다.
![캡처1](https://user-images.githubusercontent.com/40620901/63233391-de18cd00-c26a-11e9-9f0c-6f5d610abe0f.PNG)

사용자 규칙에 위의 규칙도 추가해보았습니다.
![캡처2](https://user-images.githubusercontent.com/40620901/63233406-f38df700-c26a-11e9-81e1-9db6043deefd.PNG)

제 PC가 문제인건지 증상이 해결되지 않네요 ㅠㅠ 답변감사드립니다!
![캡처3](https://user-images.githubusercontent.com/40620901/63233411-fc7ec880-c26a-11e9-880a-608d99fefbde.PNG)

**Comment by yous** [comment]
아, 감사합니다. EasyPrivacy에 `||daumcdn.net/tiara/` 필터가 있어서 안 나오고 있었네요. 알려드린 규칙 대신 이 규칙을 추가해보시겠어요? 아니면 사용자 규칙 없이 EasyPrivacy를 빼면 동작할 것 같습니다.

```
@@||daumcdn.net/tiara/js/v1/tiara.min.js^$domain=gallery.v.daum.net
```

**Comment by chilo-demo** [comment]
오 해결되었어요 감사합니다 ㅠㅠ
youslist 때문이 아니었는데 친절한 답변 감사드려요!

**Comment by yous** [comment]
언제든지 광고가 보이거나 문제가 있다면 제보해주세요. 감사합니다!
