### ISSUE TITLE
https://lover.ne.kr:124/ 이 사이트의 광고가 차단이 되지 않습니다.

### ISSUE THREAD

**Issue by thatembezzler** [yous/YousList#121]
<https://lover.ne.kr:124/bbs/view.php?id=sitelink7&page=1&sn1=&divpage=1&category=1&sn=off&ss=on&sc=on&select_arrange=headnum&desc=asc&no=32541>
접속하면 약 5초 정도 기다린 후에 뜨는 "①"을 클릭해서 다른 페이지로 연결되는 방식의 사이트인데요. 애드블럭을 활성화시켜 놓으면 "①"을 클릭해도 아무 반응이 없습니다. 필터 업데이트로 해결해 주실 수 있을까요?

**Comment by thatembezzler** [comment]
List-KR에서 AdGuard 베이스 필터의 다음과 같은 규칙이 문제가 되는 것이라는 답변을 받았습니다.

lover.ne.kr#%#//scriptlet("prevent-window-open")

AdGuard 필터에 직접 이슈를 개설해주셨고요. (AdguardTeam/AdguardFilters#39995)

**Comment by yous** [comment]
아, 감사합니다. 다른 필터에서 팝업 창이 열리는 것을 막아두었나 보군요. 일단 YousList만 켜둔 상태에서는 끝까지 들어갈 수 있는 것 같습니다.

**Comment by yous** [comment]
AdguardFilters에서도 해결된 것 같으니 이 이슈는 닫겠습니다. 문제 있으면 언제든지 제보해주세요.
