### ISSUE TITLE
Invalid rule

### ISSUE THREAD

**Issue by Alex-302** [yous/YousList#122]
Invalid selector: `reuters.com##div.TwoColumnLayout_column>div[class]::not(.ArticleHeader_content-container):not(.StandardArticleBody_container)`
**::not()** should be `:not(`
The rule can be checked on `https://www.reuters.com/article/us-apple-board/disney-ceo-bob-iger-resigns-from-apple-board-as-tv-battle-looms-idUSKCN1VY2G9`

**Comment by yous** [comment]
Thanks for the report! It's fixed on <https://github.com/yous/YousList/commit/7324714f33449381d4209f810290816509930809>.
