### ISSUE TITLE
필터 규칙 추가 요청

### ISSUE THREAD

**Issue by someone5678** [yous/YousList#126]
@@||dcimg*.dcinside.co.kr
@@||down.humoruniv.org
@@||i.huv.kr

디시인사이드와 웃긴대학의 이미지 링크를 차단 해제하는 규칙입니다.
Adguard에서 Youslist 필터를 켰더니 이미지가 나오지 않는 문제가 있더군요.
Youslist를 끄고 다시 확인해 봤는데 이미지가 나오는 걸로 봐선 Youslist에 규칙을 추가해야할 것 같습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 이미지가 안 나오는 디시인사이드 URL과 웃긴대학 URL 하나씩 알려주실 수 있나요?

**Comment by someone5678** [comment]
> 안녕하세요, 제보 감사합니다. 혹시 이미지가 안 나오는 디시인사이드 URL과 웃긴대학 URL 하나씩 알려주실 수 있나요?

답변감사합니다!
이미지가 안나오는 URL 예시입니다.

디시인사이드 예시:  https://gall.dcinside.com/board/view/?id=issuezoom&no=6559

웃긴대학 예시:  http://web.humoruniv.com/board/humor/read.html?table=photo&number=16924&device=pc

**Comment by yous** [comment]
PC에서 안 보이시는 건가요? 혹시 지금 별도로 추가하신 규칙 끄고 YousList만 켰을 때에도 그 현상이 다시 발생하나요? Adguard는 아니지만 uBlock Origin에서 YousList만 켰을 땐 두 페이지 모두 이미지가 보입니다.

**Comment by someone5678** [comment]
방금 PC 및 모바일에서 모든 필터를 다 끄고 YousList만 켜서 다시 확인해 봤습니다.

우선 웃긴대학의 경우에는 모바일, PC 모두 몇 개의 이미지가 보이는 경우가 있으나 대부분 이미지가 로딩이 되지 않습니다.

디시인사이드의 경우에는 모바일에선 모든 이미지가 나오지만 PC에선 이미지가 나오는 경우도 있고 안나오는 경우도 있습니다..

**Comment by yous** [comment]
PC 같은 경우에 필터링 로그를 볼 수 있는데요, 이미지가 뜨지 않는 페이지에서 필터링 로그를 켠 다음 페이지 새로고침을 눌러서 이미지 URL이 차단되고 있는지 확인해주실 수 있을까요?

![Screenshot 2020-01-24 20 48 36](https://user-images.githubusercontent.com/853977/73067063-06c48300-3eeb-11ea-9dc1-bea1ab9f448e.png)
![Screenshot 2020-01-24 20 49 59](https://user-images.githubusercontent.com/853977/73067106-1a6fe980-3eeb-11ea-9075-e15031c2ffb2.png)

**Comment by someone5678** [comment]
아.. 방금 필터링 로그를 확인 했더니 차단 이력이 없어 혹시나해서 AdGuard에서 모든 모드를 다 끄고 YousList만 적용해 봤는데 이미지가 전부 정상적으로 뜨는 걸 확인했습니다..
이건 AdGuard의 문제이니 이슈는 닫도록 하겠습니다..
연휴에 방해해서 죄송합니다..
답변 감사드립니다!

**Comment by yous** [comment]
아닙니다, 확인해주셔서 감사합니다! 언제든지 자유롭게 제보해주시고 즐거운 명절 보내시길 바랍니다. 😃
