### ISSUE TITLE
Breaking site: x.kinja-static.com

### ISSUE THREAD

**Issue by p1r473** [yous/YousList#128]
Hi, not sure how you want to handle this one
This one breaks Gozmodo news articles, but also lets in some ad pictures.

![image](https://user-images.githubusercontent.com/9235633/78388479-1a592d80-75af-11ea-89ed-a1751758c1de.png)
![image](https://user-images.githubusercontent.com/9235633/78388502-204f0e80-75af-11ea-9547-b77e67ed3ef6.png)

**Comment by yous** [comment]
This filter hasn't blocked x.kinja-static.com. Also I've pushed 7f82859, which removes some ads on gizmodo.com, but still "Popular Deals" section exists.

**Comment by yous** [comment]
Oh, I see. It's because of the following rule:
``` adblockfilter
||x.kinja-static.com/assets/packaged-js/dollars.*.js^
```
I removed it from hosts.txt. 6e6a5ba
