### ISSUE TITLE
네이버뉴스 광고필터링이 전혀 안됩니다

### ISSUE THREAD

**Issue by applykim** [yous/YousList#129]
모바일 네이버뉴스에서 뉴스 목록 사이의 광고랑 본문 내 광고가 전혀 필터링이 안됩니다...
얼마 전부터 갑자기 이러네요

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 광고가 보이는 URL 하나만 알려주실 수 있을까요? 안드로이드를 사용 중이라면 안드로이드 버전이나 사용한 브라우저는 어떤 건지 알 수 있을까요?
