### ISSUE TITLE
filter rules

### ISSUE THREAD

**Issue by gtgvxinf** [yous/YousList#13]
comic.naver.com###ppl_video_section
comic.naver.com###ppl_image_section
tcafeaa.com###cssImg > TBODY > TR:last-child > TD:first-child > TABLE:last-child
tcafeaa.com###cssImg > TBODY > TR:last-child > TD:first-child > TABLE:first-child > TBODY > TR:last-child
tcafeaa.com###mw_basic > TABLE:nth-child(6) > TBODY > TR:last-child > TD > TABLE > TBODY > TR > TD:first-child
tcafeaa.com###mw_basic > CENTER:nth-child(2)
tcafeaa.com###cssImg > TBODY > TR:first-child > TD:last-child > TABLE > TBODY > TR > TD > TABLE > TBODY > TR > TD.dp:last-child
tcafeaa.com###divpop
shencomics.com###fbanner
shencomics.com##DIV.mobfloat

**Comment by yous** [comment]
Thanks for the report! I'll add them after check.

**Comment by yous** [comment]
Closed via https://github.com/yous/YousList/commit/90b6bc2561a52320b268ae3d8f97e1f9c87473db, https://github.com/yous/YousList/commit/be42609719140a514fec77e0ee51a0af6e72f1aa, https://github.com/yous/YousList/commit/46b7af1e93e4d1e686296abe434a11eb8cd38628.
