### ISSUE TITLE
namu.live / hiyobi.me / 기타 등등

### ISSUE THREAD

**Issue by dnldtrump** [yous/YousList#130]
나무라이브: 광고는 안 뜨는데 공백 공간이 생겨서 `namu.live##.ad` 추가가 필요합니다.
hiyobi: `||api.hiyobi.me` 추가가 필요합니다.
기타 (도박 광고): 
> ##[href*="spin800.com"]
##[href*="slot0505.com"]
##[href*="wnx-ir.com"]
##[href*="onca888.com"]
##[href*="sureman77.com"]
##[href*="2020tteecaca.com"]
##[href*="butterkorea.com"]
##[href*="wb-tt.com"]
##[href*="rk-33.com"]
##[href*="nb-iu.com"]
##[href*="ptd-va.com"]
##[href*="10x10bet888.com"]
##[href*="bingre-n.com"]
##[href*="777bbet.com"]
##[href*="2020kkaggme.com"]

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. f8bdd21, 11a5aac 각각 namu.live와 hiyobi.me에 대해 업데이트 했는데, hiyobi.me에서 더 보이는 광고가 있는지 확인 가능하실까요? 사이트가 잘 뜨지 않아서 확인이 잘 안 되네요.

**Comment by dnldtrump** [comment]
> 안녕하세요, 제보 감사합니다. [f8bdd21](https://github.com/yous/YousList/commit/f8bdd21d258eb02ae9520188c0b695f4ac1bd5cc), [11a5aac](https://github.com/yous/YousList/commit/11a5aac8f39c27943af40f0a520156f1b948ec70) 각각 namu.live와 hiyobi.me에 대해 업데이트 했는데, hiyobi.me에서 더 보이는 광고가 있는지 확인 가능하실까요? 사이트가 잘 뜨지 않아서 확인이 잘 안 되네요.

없습니다.

**Comment by yous** [comment]
감사합니다. 이 이슈는 닫겠습니다. 언제든 또 제보해주세요!

**Comment by dnldtrump** [comment]
@yous 이슈 가장 위에 있는 도박 광고 관련 차단도 필요할 것 같습니다.
