### ISSUE TITLE
도박 광고 / smpeople.net

### ISSUE THREAD

**Issue by dnldtrump** [yous/YousList#131]
### 도박 사이트 광고
>##[href*="spin800.com"]
>##[href*="slot0505.com"]
>##[href*="wnx-ir.com"]
>##[href*="onca888.com"]
>##[href*="sureman77.com"]
>##[href*="2020tteecaca.com"]
>##[href*="butterkorea.com"]
>##[href*="wb-tt.com"]
>##[href*="wb-ct.com"]
>##[href*="rk-33.com"]
>##[href*="nb-iu.com"]
>##[href*="ptd-va.com"]
>##[href*="10x10bet888.com"]
>##[href*="bingre-n.com"]
>##[href*="bingre-i.com"]
>##[href*="777bbet.com"]
>##[href*="2020kkaggme.com"]
>##[href*="co-mang.com"]
>##[href*="kwe45.com"]
>##[href*="pmca82.com"]
>##[href*="seda1.bet"]
>##[href*="rev-112.com"]
>##[href*="bys8282.com"]
>##[href*="ccow888.com"]
>##[href*="pay-410.com"]
>##[href*="sy-bol.com"]
>##[href*="goodsimba.com"]
>##[href*="spo39.com"]
>##[href*="ccow99.com"]
>##[href*="bbmc1414.com"]

[예시 사이트](https://tkor.host/)
1. 해당 광고가 걸리는 사이트는 도메인이 자주 변경됨 & 하나가 아님
2. 광고 링크는 도메인이 자주 변경되지 않음

### smpeople.net
>smpeople.net##.left_side_banner
>smpeople.net###boxer
>smpeople.net##.fancybox-skin
>smpeople.net##ul > div:nth-of-type(3)
>smpeople.net##ul > div:nth-of-type(4)
>||smpeople.net/mappy/ad/*.png^$domain=smpeople.net

**Comment by dnldtrump** [comment]
몇가지 추가했습니다.

**Comment by dnldtrump** [comment]
@yous PR 요청을 하는게 더 빠를까요?

**Comment by yous** [comment]
아, 아닙니다. 오늘 중으로 업데이트 가능할 것 같아요.

**Comment by yous** [comment]
일단 smpeople.net, tkor.host / tkor.tax 사이트에 대해 업데이트 했습니다. 아래 목록은 확인되는 대로 업데이트 할 것 같은데, 광고 보이는 사이트를 좀 더 알려주시면 바로 적용하겠습니다.

```
##[href*="wb-ct.com"]
##[href*="rk-33.com"]
##[href*="nb-iu.com"]
##[href*="ptd-va.com"]
##[href*="10x10bet888.com"]
##[href*="bingre-n.com"]
##[href*="bingre-i.com"]
##[href*="777bbet.com"]
##[href*="2020kkaggme.com"]
##[href*="co-mang.com"]
##[href*="kwe45.com"]
##[href*="pmca82.com"]
##[href*="seda1.bet"]
##[href*="rev-112.com"]
##[href*="bys8282.com"]
##[href*="ccow888.com"]
##[href*="pay-410.com"]
##[href*="sy-bol.com"]
##[href*="goodsimba.com"]
##[href*="spo39.com"]
##[href*="ccow99.com"]
##[href*="bbmc1414.com"]
```

**Comment by dnldtrump** [comment]
smpeople.net은 로그인 시에 추가로 보이는 광고가 있습니다. 또한 큰 상관은 없지만 광고구분선도 차단하는 게 좋을 것 같습니다.
tkor은 모두 차단이 된 것 같습니다.

**Comment by dnldtrump** [comment]
그리고 smpeople.net는 처음에 대놓고 엄청 큰 광고유도 팝업을 띄웁니다. 확인해주세요.

**Comment by dnldtrump** [comment]
1. wfwf102.com
2. funbe.space
3. 5rs-wc21.com

**Comment by yous** [comment]
알려주신 사이트에 대해 업데이트했습니다.
