### ISSUE TITLE
mlbpark.donga.com 게시물 하단 네이버 파워링크 광고

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#135]
mlbpark.donga.com [BULLPEN 게시판](http://mlbpark.donga.com/mp/b.php?p=1&m=list&b=bullpen)에서 개별 게시물 하단에 네이버 파워링크 광고가 필터링되지 않습니다. 어떨 때는 기존 필터가 커버하는지 뜨지 않을 때도 있으나 무작위로 여러 게시물을 클릭하다 보면 올라오더군요.

**Comment by yous** [comment]
제보 감사합니다. 4a6c4a0 커밋에서 업데이트했습니다. 한번 확인해주세요.

**Comment by yous** [comment]
해결된 것으로 보고 닫겠습니다. 광고가 보이면 언제든지 제보해주세요.
