### ISSUE TITLE
marumaru, moeni, tkor, newtoki, wfwf, wtwt, fxfx

### ISSUE THREAD

**Issue by dnldtrump** [yous/YousList#137]
https://marumaru.sale/
https://moeni.org/ > 로고와 검색창 사이 간격이 박살나는 버그가 있음
https://tkor.pink/
https://wfwf107.com/
https://newtoki73.com/
https://fxfx23.com/
https://wtwt32.com/

**Comment by dnldtrump** [comment]
https://wfwf107.com/
https://newtoki73.com/

**Comment by dnldtrump** [comment]
https://fxfx23.com/
https://wtwt32.com/

**Comment by yous** [comment]
제보 감사합니다. 다음 커밋에서 업데이트했습니다.

- da04aec: marumaru.sale
- 4d8b91b: moeni.org, `a` 태그 대신 이미지만 가려도 로고의 레이아웃이 깨져서 그냥 두었습니다. 모바일에선 애초에 로고가 제대로 나오지 않습니다.
- 816a9e7: tkor.pink
- e154a9e: wfwf107.com
- e7399f9: newtoki73.com
- cac3af0: fxfx23.com
- bb5aed7: wtwt32.com
