### ISSUE TITLE
나무위키 검색바 차단

### ISSUE THREAD

**Issue by weak-man** [yous/YousList#140]
ublock origin 나무위키 검색바가 차단됩니다.

YousList 해제시 검색바가 정상적으로 보이네요.

확인 부탁드립니다.

**Comment by reidin999** [comment]
이 문제 때문에 글 쓰러 오니 이미 올리신 분이 있군요. 필터 상세정보는 다음과 같습니다.

필터: namu.wiki##div[id^="chika"]
필터 목록: KOR: YousList 
컨텍스트: namu.wiki
유형: dom
URL: https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8

필터가 잘못 입력된 것 같아 보입니다.

**Comment by yous** [comment]
제보 감사합니다. 그새 사이트가 업데이트된 것 같네요. #141 PR로 해결될 것 같습니다.

**Comment by yous** [comment]
#141 PR이 머지되어 닫습니다. 다른 문제가 생기면 언제든지 제보해주세요.
