### ISSUE TITLE
DVDPrime 광고차단 안됩니다

### ISSUE THREAD

**Issue by xeleven11** [yous/YousList#151]
[https://dvdprime.com](url) 디비디프라임 상단과 왼쪽에 광고 모두 표시됩니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 왼쪽 광고는 74bab2d 커밋에서 업데이트했습니다. 다만 상단 로고와 같이 나오는 광고는 가리게 되면 로고도 사라져서 어쩔 수 없이 그냥 두고 있습니다.

**Comment by xeleven11** [comment]
[https://dvdprime.com/g2/bbs/board.php?bo_table=tvmonitor]( ) 또는 아무 게시판에 가면 오른쪽에 광고가 있습니다. 그래서 로고 포함해서 그냥 다 차단했습니다. 빈칸 없애려고 dvdprime.com##div#top_banner.box_shadow_5 필터 추가했어요. 아마존배너 dvdprime.com/g2/img/banner/side/도 있습니다.

**Comment by yous** [comment]
감사합니다. 오른쪽 광고는 c8f898e 커밋에서 업데이트했습니다. 다음 필터를 '내 필터' 등의 개인 필터로 추가하시면 자리는 남지만 왼쪽 로고 자리를 클릭해서 홈으로 가실 수 있습니다.
```
dvdprime.com##div#top_banner>div.relative:not([id])
```

자리까지 없애려면 말씀하신 필터를 쓰시면 될 것 같습니다.
```
dvdprime.com##div#top_banner
```
