### ISSUE TITLE
Tving 광고가 뜹니다

### ISSUE THREAD

**Issue by icedcocktail** [yous/YousList#152]
adguard를 사용 중인데, 티빙에서 실시간 tv, 정주행을 할 수 있는 tving tv까지 모두 광고가 뜹니다.
특히 티빙티비에선 거의 십분에 한번 간격으로 광고가 뜨는데 해결 방법이 있을까요?

http://www.tving.com/live/player/C40341

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. PC에서 보시는 건가요?

**Comment by yous** [comment]
일부 광고는 bc02a05 커밋에서 업데이트했습니다. 실시간 TV에서는 광고가 보이는 것 같았는데, 일단 tving tv는 괜찮아보입니다.

**Comment by icedcocktail** [comment]
안녕하세요, 네, PC(네이버 웨일브라우저)로 보고 있습니다.
방금 업데이트 해주신 필터를 적용해보니 일단 광고 없이 잘 가동되는 것 같습니다!
정말 고맙습니다.

**Comment by yous** [comment]
확인 감사합니다. 이슈는 일단 닫겠습니다. 또 광고가 보이거나 다른 문제 있으면 제보해주세요.
