### ISSUE TITLE
m.dcinside.com에서만 발생하는 문제 2가지

### ISSUE THREAD

**Issue by growgi** [yous/YousList#154]
디씨인사이드의 모바일 페이지(m.dcinside.com)에서만 다음 2가지 문제가 발생합니다.
데스크탑 페이지에서는 발생하지 않습니다.

1. 이력이 없는 초기 상태에서 댓글 작성불가 문제

사이트 처음 이용, 시크릿모드 등 dcinside.com에 대해 이력이 없는 상태이어야 합니다.
갤러리 > 아무 게시판 > 아무 게시글 > 댓글 등록을 합니다.
Youslist 사용 중인 상태에서는 댓글이 생성되지 않는 문제가 있습니다.
광고차단 일시 해제 후, 아무 댓글 하나를 등록합니다. 이후부터는 광고차단을 다시 켜도 댓글이 정상적으로 등록됩니다.
시크릿모드 등 초기화된 상태에서는 여전히 동일한 문제가 발생합니다.

2. 갤로그 방명록 내역 차단 문제

광고차단이 켜져 있는 상태에서는 갤로그 > 방명록 메뉴에서
기존에 작성되어 있던 방명록들도 광고마냥 같이 차단되어 보이지 않는 문제가 있습니다.
방명록에 대해, 갤로그 주인이 대댓글로 달아놓은 방명록은 정상적으로 표시됩니다.
광고차단을 해제할 경우 모든 방명록이 정상적으로 표시됩니다.

**Comment by yous** [comment]
제보 감사합니다. 먼저 2번 항목은 b685266 커밋에서 업데이트했습니다. 1번은 어떤 부분이 문제인지 파악하는 데 시간이 좀 걸릴 것 같네요.

**Comment by growgi** [comment]
댓글을 1번이라도 작성했으면 이후에는 괜찮고, 시크릿모드 다시 커보면 또 안 되는 것으로 봐서 쿠키 등과 관련이 있나 의심이 됩니다.

추가로 다른 문제도 제보 드립니다. 역시 모바일 페이지에서만 문제가 있습니다.
대댓글이 달려 있던 댓글이 삭제될 경우, 삭제된 댓글 위치에는 '삭제된 댓글' 이라고 시스템메세지가 댓글 자리에 남게 되는데, 이 시스템 메세지 댓글니 광고취급되는지 차단되어 보이지 않습니다.

**Comment by growgi** [comment]
자신이 작성한 게시글에 타인이 남긴 댓글은, 자신이 글 작성자 권한으로 해당 댓글을 삭제할 수가 있습니다.
이 경우, 대댓글이 달려 있지 않더라도 
'이 댓글은 게시물 작성자가 삭제하였습니다.' 라는 시스템 메세지 댓글이 남는데 모바일 페이지에서는 광고차단 필터에 의해 차단되고 있습니다.

**Comment by yous** [comment]
댓글돌이? 댓글 가리면서 삭제된 댓글도 같이 걸리는 것 같네요. 혹시 말씀하신 경우와 같은 삭제된 댓글이 있는 링크 하나만 주실 수 있을까요? 두 경우가 비슷할 것 같긴 한데, 각각 링크가 있으면 더 좋을 것 같습니다.

**Comment by growgi** [comment]
https://m.dcinside.com/board/yds/2069

서로 다른 ip(사용자)들로 댓글 여러 개를 임의 작성하고 삭제한 글입니다.

**Comment by yous** [comment]
감사합니다. 2f34059 커밋에서 업데이트했습니다. 다만 필터의 한계로 댓글돌이 자리에는 빈칸이 생기게 되었습니다.

**Comment by growgi** [comment]
데스크탑 페이지의 경우, 삭제된 댓글이라는 시스템 메세지도 정상적으로 나오면서 댓글돌이는 빈 자리 없이 깨끗하게 차단되던데 m.dcinside.com은 규칙이 달라서 동일한 필터 규칙으로 처리할 수가 없는 건가요?

**Comment by yous** [comment]
네, 데스크톱 페이지랑 모바일 페이지랑 구조가 다른데, 모바일에선 댓글돌이 댓글이랑 삭제된 댓글을 일반 필터로는 구분하기가 어렵네요. 그래서 댓글돌이 자리까지 지울 순 없고 내용만 지우게 바꿨습니다.

이게 데스크톱 규칙입니다.
```
gall.dcinside.com##ul.cmt_list>li.dory.ub-content
gall.dcinside.com##ul.reply_list>li.dory.ub-content
```
이게 모바일 규칙입니다.
```
m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id])>a.nick>span.dori-icon
m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id])>a.nick>span.dori-icon-txt
m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id])>div.dori-box
```
기존 모바일 규칙은 이랬습니다. 이렇게 하면 삭제된 댓글도 같이 걸립니다.
```
m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id])
```

**Comment by yous** [comment]
아, AdGuard나 uBlock Origin 사용하시면 사용자 필터에 이 규칙 추가하시면 될 거 같습니다. 확장 기능이라 호환성이 조금 떨어져서 필터에 추가하지는 않고 있습니다.

```
m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id]):has(>div.dori-box)
```

**Comment by growgi** [comment]
> 아, AdGuard나 uBlock Origin 사용하시면 사용자 필터에 이 규칙 추가하시면 될 거 같습니다. 확장 기능이라 호환성이 조금 떨어져서 필터에 추가하지는 않고 있습니다.
> 
> ```
> m.dcinside.com##div.all-comment>ul.all-comment-lst>li.comment:not([id]):has(>div.dori-box)
> ```

AdGuard에서 사용자규칙에 이것을 추가해보니
빈칸으로 댓글돌이 영역이 나오는게 아니라
댓글돌이 자체가 전혀 차단이 되지 않고 댓글돌이광고(사진 및 텍스트)가 온존히 나옵니다.
데스크탑 필터링처럼 댓글돌이 영역이 완전히 제거되도록 하는 규칙이 아닌 것 같습니다...

**Comment by yous** [comment]
iOS 버전에서 시도해봤는데 안 되네요. 확장 기능은 iOS API 한계로 적용이 안 되는 것 같습니다. https://forum.adguard.com/index.php?threads/does-adguard-for-ios-support-extended-css-selectors.19204/

**Comment by growgi** [comment]
저는 Android에거 확인했던 것이었는데 댓글돌이광고가 온전히 나타났습니다.

제가 맨 처음에 제기했던 문제에 대해서 좀더 정확한 조건을 남깁니다.

1) 광고차단된 채로 모바일 페이지 첫방문이어야 할 것 (시크릿모드로 인한 첫방문도 동일)

2) 광고차단하지 않은 채로 모바일 페이지를 방문한 기록이 생기면 해당 문제가 발생하지 않음

예를 들어, 처음부터 광고차단을 킨 채로 시크릿모드로 방문하자마자 댓글을 작성하려하면 불가능합니다. 삼성브라우저 등에서 '광고 차단 일시 해제'로 껐다가 아무것도 하지 않고 바로 다시 광고차단을 키기만 했어도 댓글을 정상적으로 등록할 수 있습니다.
결론적으로, 광고차단없이 모바일 페이지 첫 방문 기록이 있어야 하는 것 같습니다.

**Comment by yous** [comment]
첫 번째 문제를 찾다가 빈 공간 문제 해결해서 c9a2aa7 커밋에서 업데이트했습니다.

**Comment by growgi** [comment]
Windows용 크롬에서 m.dcinside.com 사이트를 열고 F12 키를 눌러 콘솔을 열어보니, 
댓글이 입력되지 않는 상태(최초부터 광고차단된 상태로 방문)와 
댓글이 입력 가능한 상태(광고차단 없이 방문한 이력이 존재)가 
콘솔 로그에 전혀 다르게 나타납니다.

댓글이 입력되지 않는 상태의 경우, 
_Failed to load resource: net::ERR_BLOCKED_BY_CLIENT_
또는
_Uncaught ReferenceError: MezzoAD is not defined
    at adStart (글번호:108)
    at 글번호:150_
등의 사유로 스크립트 등의 리소스 호출이 실패하는데

댓글이 입력 가능한 상태의 경우에는 
_GET "https:// 스크립트 등의 url주소" net::ERR_BLOCKED_BY_CLIENT_
의 오류 메세지가 표시됩니다.

리소스 호출이 실패하면서 comment-write가 정해진 글번호(주소)로 댓글입력을 반환하는 것들도 실패하는 것일까요?

**Comment by yous** [comment]
파이어폭스 시크릿 모드에서 테스트했을 때 댓글이 안 달리고, 크롬 시크릿 모드에서 했을 땐 댓글이 달려서 차이점이 뭔가 보니, 파이어폭스 시크릿 모드에서 추적 콘텐츠를 차단하도록 되어 있었습니다. 그 결과 다음 URL이 차단됩니다.

- https://www.googletagservices.com/tag/js/gpt.js
- https://ssl.google-analytics.com/ga.js
- https://www.google-analytics.com/analytics.js

추적 스크립트가 차단된 경우 댓글이 달리지 않고, 파이어폭스에서 추적 콘텐츠 차단을 해제했을 경우 시크릿 모드에서도 댓글이 달리는 걸 확인했습니다.

크롬의 경우에 기본 설정으로는 시크릿 모드에서도 댓글 기능이 동작하는 것 같은데, 다른 필터에서 해당 URL을 차단하고 있는 것일 수도 있습니다. 크롬에서 F12를 눌러 개발자 도구를 연 상태로 사이트에 들어간 다음, 네트워크 탭을 보시면 해당 스크립트가 로드되고 있는지 확인할 수 있습니다.

**Comment by growgi** [comment]
"AdGuard 추적 보호 필터" 하나를 해제하니 말씀대로 크롬 계열의 시크릿모드에서 댓글이 작성됐습니다. 감사드립니다.
이제 youslist로 인한 m.dcinside.com의 문제는 없는 것 같습니다. 이 issue는 닫으셔도 될 것 같습니다.
작은 요청에도 많은 시간을 할애해주셔서 감사합니다.

**Comment by yous** [comment]
해결되었다니 다행이네요. analytics 차단하면 동작 안 하는 건 예상 못했는데, 제보해주셔서 감사합니다. 광고가 보이거나 다른 문제가 생기면 언제든지 제보해주세요.
