### ISSUE TITLE
티빙 광고차단이 작동하지 않습니다.

### ISSUE THREAD

**Issue by Dark-Layer** [yous/YousList#155]
PC용 크롬, AdGuard 애드온으로 YousList 를 사용하고 있습니다. (최신필터로 업데이트해서 사용함)
http://www.tving.com/live/player/C31642
에서 10분? 정도마다 광고가 나옵니다.
아마 제 예상으로는 티빙에서 광고사이트를 변경하지 않았나 싶습니다.

**Comment by yous** [comment]
맥용 파이어폭스, uBlock Origin으로 30분 정도 봤는데 광고가 없어서, PC 크롬에서 다시 확인해봐야 할 것 같네요.

**Comment by Dark-Layer** [comment]
uBlock Origin으로 테스트 해보셨다고해서 크롬 uBlock Origin를 설치해서 해봤으나 똑같이 광고가 나오네요
브라우저 때문일려나요...
<img src="https://i.imgur.com/7C9VrM1.png" width="60%">
<img src="https://i.imgur.com/qt2VeaP.png" width="60%">

**Comment by yous** [comment]
tving에서 적용되어야 하는 규칙이 이런 건데요, 이거 외에 aproxy-next.tving.com 관련 링크를 추가로 요청하는 게 있는지 봐야할 것 같네요.
```
||aproxy-next.tving.com/v1/v/WNPULive/get/$domain=tving.com
||aproxy-next.tving.com/v1/v/WNPUTvingTV/req/list^$domain=tving.com
```

**Comment by Dark-Layer** [comment]
그렇군요... 잘 쓰다가 어느 순간부터 티빙이 광고를 계속 내보내서
무슨 손을 썼는가봅니다
늦은 시간까지 알아봐주셔서 감사합니다 ^^

**Comment by yous** [comment]
혹시 지금도 광고가 계속 보이시나요?

**Comment by Dark-Layer** [comment]
아 보고하는 것이 늦었네요.
그 뒤로 일주일동안 여러가지 해보아서 해결법을 찾았는데 좀 어이가 없더군요.
문제가 애드온으로 쓰고있는 AdGuard가 문제였습니다...

예전에 보고한 

> uBlock Origin으로 테스트 해보셨다고해서 크롬 uBlock Origin를 설치해서 해봤으나 똑같이 광고가 나오네요
> 브라우저 때문일려나요...
> 
여기 사진에도 AdGuard의 광고차단기능을 켜둬서 안됬던걸로 판단내렸습니다.

AdGuard관련된 친구들을 다 끄니까 완벽히 차단됩니다.
그리고 uBlock Origin 으로 교체해서 사용하고 있습니다.
별 것 아닌걸로 소란피워서 정말 죄송합니다 ㅠㅠ

**Comment by yous** [comment]
아하 AdGuard 쪽 필터가 원인일 수 있겠네요. 알려주셔서 감사합니다. 광고가 보이거나 문제가 있으면 언제든지 제보해주세요.
