### ISSUE TITLE
wavve 광고

### ISSUE THREAD

**Issue by icedcocktail** [yous/YousList#158]
안녕하세요.
웨이브에서 라이브 채널을 틀면 광고차단 프로그램을 해제하라는 문구가 뜹니다. 
웨일브라우저에서 adguard를 사용 중입니다. 
개선해 주시면 감사하겠습니다. 

https://www.wavve.com/player/live?channelid=S01

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 광고를 차단하면 아예 재생이 되지 않거나 팝업이 뜨게 되어 있어서 5330f55 커밋에서 수정했습니다. 지금으로서는 필터의 한계로 광고를 막을 간단한 방법은 없는 것 같습니다.

**Comment by icedcocktail** [comment]
친절한 답변 감사합니다!
