### ISSUE TITLE
유튜브 영상 챕터 기능이 작동하지 않습니다.

### ISSUE THREAD

**Issue by comjun04** [yous/YousList#159]
YousList 적용 시 유튜브 영상 내 챕터 기능이 작동하지 않습니다. (챕터 화면이 열리지 않습니다.)
![image](https://user-images.githubusercontent.com/30339539/100838540-ef183c80-34b5-11eb-8100-d0cd61c55961.png)
(표시한 부분을 클릭했는데 아무 반응이 없습니다)
다른 필터도 테스트해봤는데 YousList 켰을때만 이런 문제가 발생합니다.

Adguard 사용 중이고, 필터 모두 최신 업데이트한 상황입니다,

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 테스트할 링크 하나만 알려주시겠어요?

**Comment by comjun04** [comment]
https://www.youtube.com/watch?v=cbuZfY2S2UQ
사진에 나온 영상 링크입니다.

**Comment by yous** [comment]
#156 이슈와 동일한 문제 같은데요, e485929 커밋에서 업데이트해서 지금은 잘 보이는 것 같습니다. AdGuard 쪽에서 업데이트가 아직 안 된 건지 잘 모르겠네요.

**Comment by yous** [comment]
지금 이 버전으로 잘 보이는 것 같습니다. 다른 필터나 기능을 전부 끄고 확인한 거라 어쩌면 다른 곳의 영향이 있을 수도 있습니다.

<img width="687" alt="Screenshot 2020-12-02 16 03 12" src="https://user-images.githubusercontent.com/853977/100839664-ede80f00-34b7-11eb-9bff-ea514d86575f.png">

**Comment by krystian3w** [comment]
AdGuard have ~8 updates daily for 3p lists so problem was fixed 8 days ago with forced updated filters from AdGuard settings.

**Comment by yous** [comment]
@krystian3w Thanks for the information, I get that.

@comjun04 일단 현재 버전으로는 잘 되는 것 같으니 이 이슈는 닫겠습니다. 필터 업데이트 후에도 계속 문제가 있거나 다른 문제가 생기면 제보해주세요.
