### ISSUE TITLE
네이버 웹툰 광고 차단 필터 요청

### ISSUE THREAD

**Issue by Fenslett** [yous/YousList#16]
네이버 웹툰에 최근 광고가 추가되었습니다. 
``` html
<div class="view_area" id="comic_view_area">
    
    <!-- 뷰어  -->
    <div class="wt_viewer" style="background:#FFFFFF"> <!-- 웹툰 이미지 --> </div>
    <!-- // 뷰어 -->
    <div id="webtoon_ad_section" class="ads_sc"> <!-- 추가된 광고 --> </div>

</div>
```
위 DOM elements에 따라, 다음 규칙을 추가하면 되리라 생각이 듭니다.
`comic.naver.com##div#webtoon_ad_section` 

자세한 것은 [이곳] (http://comic.naver.com/webtoon/detail.nhn?titleId=675554&no=50&weekday=mon)으로 가시면 확인하실 수 있습니다.

**Comment by yous** [comment]
제보 감사드립니다. <https://github.com/yous/YousList/commit/590502174d8296ad97688cc17ebb4c6f394af421>에서 해결되었습니다.
