### ISSUE TITLE
fxfx / wfwf / ani365

### ISSUE THREAD

**Issue by lucoa-q** [yous/YousList#160]
https://fxfx39.com (wildcard 필요)
https://wfwf125.com (wildcard 필요)
https://ani365.org

참고로 imgcloud5.net 도메인은 저 쪽에서 광고 용도로만 사용하는 자체 클라우드 같습니다.

**Comment by yous** [comment]
다음 커밋에서 업데이트했습니다.

- c9c0747: fxfx39.com
- b4dffc6: wfwf125.com
- 1bbff96, 9e22cb6: ani365.org

지금 보니 이미지 도메인이 imgcloud6.net이어서 `imgcloud*.net`으로 적용했습니다.
