### ISSUE TITLE
dcinside 

### ISSUE THREAD

**Issue by lucoa-q** [yous/YousList#161]
dcinside.com
m.dcinside.com
'팬더티비' 부분이 유사 광고로 보입니다.

**Comment by lucoa-q** [comment]
시각적 어그로 ##.ani_lines
버튼 자체 ##.linebox
모바일, PC 동일합니다.

**Comment by yous** [comment]
제보 감사합니다. 다음 커밋에서 업데이트했습니다.

- d666e9b: dcinside.com
- 6aed0f3: m.dcinside.com

**Comment by yous** [comment]
사이트가 업데이트돼서 버튼은 다시 나오는데 애니메이션은 사라졌네요.
