### ISSUE TITLE
퀘이사존 칼럼란 차단 문제

### ISSUE THREAD

**Issue by Gini765** [yous/YousList#162]
안녕하세요, 퀘이사존에서 광고 차단 시 광고 뿐만 아니라 칼럼란까지 같이 차단이 되고 있는 현상이 발생하고 있습니다.
아래가 원본이구요 보시면 빨간 박스 친 부분이 칼럼이 실리는 부분입니다.

![퀘이사존 광고 원본](https://user-images.githubusercontent.com/14210418/103847426-8b4fe780-50e3-11eb-9827-cfaca580e6b4.png)

그런데 차단을 진행한 후에 보시면 칼럼란까지 같이 차단이 되어버리네요.

![퀘이사존 광고 차단](https://user-images.githubusercontent.com/14210418/103847465-a7ec1f80-50e3-11eb-9e8f-de9b44fb3c88.png)

여기다 제보를 하는게 맞는지 모르겠는데, 혹시 틀렸다면 알려주세요. 
필터 잘 사용중에 있습니다 감사합니다.

**Comment by yous** [comment]
혹시 다른 필터도 사용 중이신가요? YousList만 썼을 땐 괜찮아보이는데, 사용 중인 목록을 알려주시면 확인해보겠습니다.

**Comment by yous** [comment]
아, 예전에 로그인/로그아웃 상태에 따라서도 달랐던 것 같은데, 혹시 로그아웃하면 보이는 건가요?

**Comment by Gini765** [comment]
> 아, 예전에 로그인/로그아웃 상태에 따라서도 달랐던 것 같은데, 혹시 로그아웃하면 보이는 건가요?

로그인 로그아웃 상태에서도 동일했습니다.
지금 사용중인 필터는 uBlock 기본제공 필터와 EasyList, EasyPrivacy, YousList정도입니다.

따 끄고 제가 사용하는 필터들을 하나씩 테스트 했을때도 차단이 되어있는 상태였는데, 다시 체크 후 업데이트 하니까 정상작동합니다. 제가 따로 커스텀해서 유저필터를 사용하지는 않고 있는데 신기하네요. 뭔가 오류가 있었던 모양입니다. 

이슈는 클로즈 하셔도 될 것 같습니다.
번거롭게 해드려서 죄송합니다!

**Comment by yous** [comment]
아 업데이트로 해결되었나보네요. 확인 감사합니다. 일단 이슈는 닫겠습니다. 문제 있으면 언제든지 알려주세요.
