### ISSUE TITLE
오르비/네이버 모바일/네이버 카페/카카오뱅크 내 광고

### ISSUE THREAD

**Issue by AndyH0ng** [yous/YousList#163]
![0F8A2432-8809-49F8-9158-951012F8F5DE](https://user-images.githubusercontent.com/60703412/105434872-ab64d680-5c9f-11eb-8a36-1f8cbaf79097.jpeg)
orbi.kr
오르비 사이트의 광고가 전부 차단이 안되어 있으며

![3502209D-563F-4FF4-AF1A-D1185E014AA2](https://user-images.githubusercontent.com/60703412/105435461-bec47180-5ca0-11eb-9ff9-82c9d7dd7f27.jpeg)
![4EE754B6-772D-4F3E-9161-3C8895068BB8](https://user-images.githubusercontent.com/60703412/105435468-c257f880-5ca0-11eb-93ea-136ef673348e.jpeg)
네이버 모바일사이트와 카페 사이트 내 광고도 일부 차단되어 있지 않습니다

![4A7705E4-A266-4879-9318-3BF4C84C527D](https://user-images.githubusercontent.com/60703412/105435496-ca179d00-5ca0-11eb-9066-83205937c917.jpeg)
추가로 카카오뱅크 내의 배너도 차단이 가능할까요?

애드가드 4.0.4 (588)
iOS 14.3
Cloudflare DNS 사용
DNS/사파리 필터 적용중

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 다음 커밋에서 업데이트했습니다.

- 472352e orbi.kr
- abea052 m.cafe.naver.com
- 427c041 m.naver.com

네이버 모바일 사이트의 경우 NOW나 네이버 앱 부분은 자사 서비스라 광고라고 하기 애매한 부분이 있어 놔두었는데요, 버거킹 부분은 일정 부분 차단되고 있는 것 같은데 이번에 추가로 업데이트했습니다.

카카오뱅크의 경우엔 앱이라서 차단에 어려움이 있습니다. 기본적으로는 PC나 모바일 브라우저에서 작동하도록 테스트하고 있습니다.

**Comment by AndyH0ng** [comment]
orbi.kr에서 아래로 스크롤했다 최상단으로 올라가면 배너가 제대로 나타나지 않네요
<img width="1440" alt="스크린샷 2021-01-27 오후 10 46 35" src="https://user-images.githubusercontent.com/60703412/105999914-977f0180-60f1-11eb-9db2-2749cbed7745.png">
1. 기존
<img width="1440" alt="스크린샷 2021-01-27 오후 10 46 30" src="https://user-images.githubusercontent.com/60703412/105999922-9948c500-60f1-11eb-8a43-0c58980217df.png">
2. 아래로 내린 후 올라갔을 때
https://github.com/AndyH0ng/MyFilter/blob/main/hosts.txt
css로 top써서 제대로 표시되도록 만들긴 했는데 같이 올려봅니다

**Comment by yous** [comment]
맨 위의 배너를 가렸을 때 레이아웃이 망가져서 일부러 그대로 뒀는데, 배너 이미지 URL을 막으면 이 최상단 배너가 가려질 수 있어서 04e6b2f 커밋에서 다시 되돌립니다. 업데이트 후에는 이런 식으로 보입니다.

![Screenshot 2021-01-28 22 23 47](https://user-images.githubusercontent.com/853977/106144441-87315a00-61b7-11eb-8fa9-309c2887c734.png)

**Comment by yous** [comment]
일단 이 이슈는 닫겠습니다. 빠뜨린 광고가 있거나 다른 사이트에서 광고가 보인다면 언제든지 알려주세요.
