### ISSUE TITLE
tv.kakao.com

### ISSUE THREAD

**Issue by lucoa-q** [yous/YousList#164]
uBlock Origin에서 Chrome + uBlock filters + EasyList 기준으로 카카오TV 광고 차단이 되는 것 같습니다. 이 방식을 YousList에서 구현해주시면 될 것 같은데 다른 uBO 외 광고 차단 프로그램에서 문제가 발생할까요?

**Comment by yous** [comment]
아까 언급하신 #124 이슈와 관련해서 한번 테스트 해보겠습니다.

**Comment by yous** [comment]
EasyList를 켰을 땐 `/videoads.` 규칙 때문에 `https://videoads.kakao.com/adserver/api/v2/vmap` 링크가 막히면서 동영상을 재생할 수 없다고 나오는 것 같네요.

테스트 링크입니다. https://play-tv.kakao.com/channel/3754840/cliplink/416865629

**Comment by yous** [comment]
크롬에서는 현재 YousList만으로 재생이 잘 되는 것 같아서 또 모르겠네요.
