### ISSUE TITLE
아카라이브 측면 념글 목록을 허용해주실 수 있나요?

### ISSUE THREAD

**Issue by Imsiro-Sogang** [yous/YousList#166]
원래 나무위키 메인 또는 특정 문서 우측에는 '주식 채널'과 같은, 특정 아카라이브 채널의 개념글 목록이 나오도록 되어 있습니다.
이게 특정 문서에 맞게, 거기에 맞는 아카라이브 커뮤니티의 개념글 목록을 보여주게 되어있어서 나름 쏠쏠한 기능이거든요.
(예: '라스트오리진' 문서에서 '라스트오리진 채널 최근 개념글 목록'을 확인할 수 있음)

그런데 uBlock Origin에서 광고차단을 실행하면, 그 '개념글 목록' 기능까지 비활성화해버려요.
광고차단을 켜도 나무뉴스는 냅두는 걸로 봐서, 그냥 버그 내지는 의도하지 않은 동작으로 보입니다.
우측 념글 목록은 생각외로 쏠쏠한 기능입니다. 필터 목록을 잘 조정해서 어떻게 좀 해주실 수는 없을까요?

**Comment by yous** [comment]
사이트가 좀 업데이트 되면서 레이아웃이 바뀐 것 같네요. e9aec4e 커밋에서 업데이트 했습니다. 한번 확인해주세요. 보니까 '최근 변경', '나무뉴스', '○○ 채널' 이렇게 3개가 나와야 할 것 같네요.

**Comment by Imsiro-Sogang** [comment]
죄송하지만 업데이트를 어떻게 적용하는지 잘 모르겠습니다. 일단 uBlock Origin 설정에 들어가서 yous 필터 업데이트 버튼(시계모양)을 눌러보긴 했는데, 적용이 안 되네요.

**Comment by yous** [comment]
시계 모양 버튼을 누른 다음 위에서 '지금 업데이트' 버튼을 누르면 적용될 것으로 보입니다. 그래도 적용이 안 되면 다른 필터 때문일 수도 있는데, 한국 필터 중에 YousList 외에 다른 게 있으면 끈 다음 확인해보셔도 됩니다.

**Comment by Imsiro-Sogang** [comment]
작동 확인했습니다. 감사합니다!

**Comment by yous** [comment]
확인 감사합니다. 다른 광고가 보이거나 문제가 있으면 언제든지 알려주세요.
