### ISSUE TITLE
아프리카tv 광고 제보

### ISSUE THREAD

**Issue by bobblun** [yous/YousList#170]
play.afreecatv.com###ad_video

play.afreecatv.com##.text_output

play.afreecatv.com##.promotion_area

play.afreecatv.com##.promotion_area_left

play.afreecatv.com##.promotion_area_right

vod-player.afreecatv.com/creatives/media/*

필터 추가 부탁드립니다

**Comment by yous** [comment]
제보 감사합니다. 일단 동영상 광고가 보여서 281ea2b 커밋에서 업데이트했습니다. `#ad_video`나 `vod-player.afreecatv.com/creatives/media/*` 쪽은 이걸로 해결됐을 것 같은데, `.text_output`은 어디 있는지 모르겠네요. 업데이트 후에도 광고가 보이면 알려주세요.

**Comment by yous** [comment]
일단 이 이슈는 닫겠습니다. 추가로 다른 광고가 보이면 언제든지 제보 주세요.
