### ISSUE TITLE
루리웹 우측 하단 플로팅 광고

### ISSUE THREAD

**Issue by blocky9** [yous/YousList#174]
![image](https://user-images.githubusercontent.com/86645381/123741844-b45c7280-d8e5-11eb-94c8-43aa101059d2.png)
우측 하단의 플로팅 광고 삭제 부탁드립니다

**Comment by yous** [comment]
제보 감사합니다. 정확히 저 상자가 뜨진 않아서 가능성이 있는 걸 5c0a1f8 커밋에서 막았는데 한번 확인 부탁드립니다.

**Comment by yous** [comment]
일단은 해결된 것으로 보고 닫겠습니다. 추후 광고가 보이면 언제든지 제보해주세요.
