### ISSUE TITLE
네이버 PC 로그인 창 이동

### ISSUE THREAD

**Issue by blocky9** [yous/YousList#175]
![image](https://user-images.githubusercontent.com/86645381/123742669-06ea5e80-d8e7-11eb-9757-e34a8decce18.png)
스크롤할때 로그인인 창이 아래로 이동합니다.

**Comment by blocky9** [comment]
### 재현 영상
https://user-images.githubusercontent.com/86645381/123742805-3f8a3800-d8e7-11eb-9359-42ae9f00d7ab.mov

**Comment by yous** [comment]
보니까 `div#shopcast` 또는 `div.sc_shopcast`를 통째로 가린 것으로 보이는데요, 지금 YousList에서는 가리고 있지 않아서요. 다른 필터 한번 확인 부탁드립니다.

**Comment by yous** [comment]
일단 YousList에서 재현되지 않아 닫습니다.
