### ISSUE TITLE
해당 필터 적용시 접속 문제

### ISSUE THREAD

**Issue by iOS81** [yous/YousList#176]
해당 필터(https://raw.githubusercontent.com/yous/YousList/master/youslist.txt) 를 Pi-hole에 적용시 네이버(카페, 뉴스, 블로그 등 네이버 서비스 일체), 구글(지메일), 퀘이사존, 인벤, 나무위키 등의 사이트가 아예 접속되지 않는 문제가 있는데 뭐가 문제인건가요?

**Comment by yous** [comment]
안녕하세요, 제가 알기로 Pi-hole은 도메인 전체를 막는 식으로 작동하기 때문에 youslist.txt 대신 hosts.txt를 사용해 주시면 될 것 같습니다.

- https://raw.githubusercontent.com/yous/YousList/master/hosts.txt

**Comment by yous** [comment]
이 이슈는 일단 닫겠습니다. hosts.txt를 사용해도 문제가 생기면 알려주세요.
