### ISSUE TITLE
newtoki 등

### ISSUE THREAD

**Issue by lucoa-q** [yous/YousList#178]
https://newtoki95.com/ (wildcard)
https://manatoki95.net/ (wildcard)
https://www.ani365.org/
https://copytoon142.com/ (wildcard)
https://frtoon71.com/ (wildcard)
https://bam211co.com/ (wildcard)
https://www.cultureland.co.kr/ (공백, +로그인 아래 광고)
https://www.happymoney.co.kr/ (+로그인 오른쪽 광고)
https://hodu208.net/ (wildcard)
https://blacktoon107.com/ (wildcard)
https://www.chosun.com/ (기사 상단 공백)
https://www.hankookilbo.com/ (기사 우측 공백)

**Comment by yous** [comment]
- 73b56fe newtoki95.com
- 60ea761 manatoki95.net
- 9bf9cc8 copytoon142.com
- 3f36a36 frtoon71.com
- 0c8aaa4 bam211co.com
- 012106e happymoney.co.kr
- a1d7e8e hodu208.net
- 295608b blacktoon107.com

그 외 ani365.com은 들어가지지 않고, cultureland.co.kr은 애매하여 일단 두고, chosun.com, hankookilbo.com은 딱히 발견하지 못했습니다.

**Comment by lucoa-q** [comment]
@yous https://www.hankookilbo.com/ (기사 내)
![image](https://user-images.githubusercontent.com/68857640/125180432-06ca5700-e235-11eb-8600-fbc92333072f.png)
https://www.chosun.com/ (기사 상하단)
![image](https://user-images.githubusercontent.com/68857640/125180443-282b4300-e235-11eb-8c21-0955107164c0.png)
![image](https://user-images.githubusercontent.com/68857640/125180451-38dbb900-e235-11eb-9ad6-78572ec65350.png)
https://cultureland.co.kr/
![image](https://user-images.githubusercontent.com/68857640/125180499-d33bfc80-e235-11eb-9e0c-7d664a339c38.png)
https://m.happymoney.co.kr/ (로그인 페이지)
![image](https://user-images.githubusercontent.com/68857640/125180538-21e99680-e236-11eb-8fab-b0f9be2ffb69.png)
https://www.happymoney.co.kr/ (로그인 페이지)
![image](https://user-images.githubusercontent.com/68857640/125180576-80af1000-e236-11eb-935c-b9ba65cc1b0c.png)
해피머니랑 컬쳐랜드의 경우 큰 배너 말고 아래에 조그만 간편 로그인 이거는 애매한 게 맞는 것 같습니다.

**Comment by yous** [comment]
- hankookilbo.com의 경우, 각각은 이런 영역입니다. 다른 필터에서 차단하고 있는 것으로 보입니다.

  ![Screenshot 2021-07-11 20 01 39](https://user-images.githubusercontent.com/853977/125192440-d6a9a500-e282-11eb-914a-67cd41667a9e.png)
  ![Screenshot 2021-07-11 20 02 03](https://user-images.githubusercontent.com/853977/125192447-e0cba380-e282-11eb-9083-f4f71ef0b27c.png)
- chosun.com의 맨 위 영역은 422a699 커밋에서 차단했습니다. 나머지 부분들은 주위 영역과 형태가 거의 흡사하여 특정하기 애매한 부분이 있어 그대로 두고 있습니다.
- cultureland.co.kr의 빈 영역은 광고 차단을 꺼보니 대부분이 자사 이벤트라서 보여야 할 거 같은데 아예 아무것도 안 보이고 있었네요. d3bc269 커밋에서 업데이트했습니다.
- m.happymoney.co.kr은 fd0a110 커밋에서 업데이트했습니다.
- happymoney.co.kr은 이미 업데이트된 상태입니다.
