### ISSUE TITLE
auction, gmarket

### ISSUE THREAD

**Issue by ucza20fX66pSiCoIHiZv** [yous/YousList#179]
https://memberssl.auction.co.kr/Authenticate/?url=http%3a%2f%2fwww.auction.co.kr%2f&return_value=0 (로그인 오른쪽에 광고)
https://signinssl.gmarket.co.kr/LogIn/LogIn?URL=http://myg.gmarket.co.kr/ (옥션과 비슷)

**Comment by yous** [comment]
다음 커밋에서 업데이트했습니다.

- 3554ba9 auction.co.kr
- df0ef37 gmarket.co.kr
