### ISSUE TITLE
Video ad in Jobplanet

### ISSUE THREAD

**Issue by Fenslett** [yous/YousList#18]
In Jobplanet website, I found a video advertisement that is shown up all of sudden as I scrolled down

![image](http://i.imgur.com/RhKVLCN.jpg)

The filter for this element is given below:
``` 
jobplanet.co.kr###prism_displayAD 
```
But I'm afraid I can't assure you this filter normally work because It was confirmed that the advertisement was not always turned up. The only thing I know so far is that it seems to appear in section `기업리뷰` mostly. If you want to make sure, please visit [this page](https://www.jobplanet.co.kr/companies/30139/reviews/%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90). 

Well, besides, there's an alternative filter. I'd recommend this since site-specific rule is more efficient in the way that we can reduce unnecessary HTTP traffic and that we can make a general rule for other advertisements. Thus, I tried to block the advertisement through domain name-based filter that covers all ranges of video if possible. So I found one:
```
||cdnprisms.pandora.tv/_adv_img/*
OR
||cdnprisms.pandora.tv/_adv_img/prism_ad/*
! example: cdnprisms.pandora.tv/_adv_img/prism_ad/201605/junier_160517.mp4
```

**Comment by yous** [comment]
Thanks for the report. The advertisement won't be shown on Safari, but I can see it on Chrome. There is a `<script>` in the first `<section>` under
``` css
article#viewReviewsList > div.section_wrap > div.section_body > div.section_group
```

This is a starting part of the script:
``` javascript
_PrismADP = new PrismADP(); //PrismADP 생성자 호출 

function Prism_PlayerSetting(){
  var type = 'display_inRead';
  var url = 'https://prism.pandora.tv/jobplanet_PC/sub_top/displayinread/';
  var channel = '';
  var category = '';
  var IP = '';
  var country = '';
  var clientBrowser = '';
  var ran = '1679';
  var ad_options = {
    adType: 'display_inRead',  //preroll,  native, list_native, display_inRead
    adWidth:$("#prism_displayAD").width(), 
    muted:true, //true : 사운드OFF, false:사운드ON / displayVideo상품은 true가 디폴트 
    RolloverControll :true, //사운드 마운스 컨트롤 / displayVideo상품은 true가 디폴트 
    isAutoPlay:true, 
    autoSkipOnpause:false, //모바일 환경에서 onPause 이벤트발생시 자동으로 스킵 할지의 여부 설정 / displayVideo일경우 무조건 **false** (true : 자동스킵, false : 일시정지)
    isAdFinishShowPoster:false,
    adTag: url + '?filetype=xml&channel='+channel+'&category='+category+'&IP='+IP+'&country='+country+'&browser='+clientBrowser 
  };

  if (ad_options) {
    _PrismADP.adPlayer('prismADP').setup(ad_options); 
    jQuery("#mainPlayer").height($("#prism_displayAD").width()*9/16);
  }
}
```

So I think we should block `adTag`.
```
https://prism.pandora.tv/jobplanet_PC/sub_top/displayinread/
```

But the URL seems to be specific to jobplanet site, so we may block the entire `prism.pandora.tv`. Also, as you mentioned, `cdnprisms.pandora.tv/_adv_img/prism_ad/` will be blocked. `#prism_displayAD` and its container will be blocked, too.
