### ISSUE TITLE
cgv.co.kr

### ISSUE THREAD

**Issue by DandelionSprout** [yous/YousList#183]
Two placeholders on `http://www.cgv.co.kr/movies/detail-view/?midx=84911`; 1 on top, and 1 near the bottom. I propose:
```
cgv.co.kr###cgv_main_ad
cgv.co.kr##.sect-ad
```
![image](https://user-images.githubusercontent.com/22780683/132533311-8635f1c8-c566-499f-b9a2-b4d4a7ad59f4.png)
(…)
![image](https://user-images.githubusercontent.com/22780683/132533342-884711b7-2e6e-425b-99aa-a3e6a84a53e9.png)

Adblockers: uBO 1.37.3b21 + I Don't Care About Cookies 3.3.2
Browser: Chrome 93.0.4577.63 x64
OS: Windows 10 21H1 x64
Lists in use: ↓
![image](https://user-images.githubusercontent.com/22780683/132533625-4f25fc3b-5576-4571-bd32-94674b4446ba.png)

**Comment by yous** [comment]
Thanks, I updated in dabee80. Until now, "movie selection" section was empty, so I allowed to show some movie-related ads.

<img width="1161" alt="Screenshot 2021-09-09 03 33 40" src="https://user-images.githubusercontent.com/853977/132565618-48e0b333-b148-4afd-a2b4-ab6bf8afd52c.png">

**Comment by yous** [comment]
Closing this. If you still have problems or there are other ads, feel free to open a new issue.
