### ISSUE TITLE
unsa-financesindustrie.org [anti-adblock]

### ISSUE THREAD

**Issue by felix-22** [yous/YousList#190]
http://unsa-financesindustrie.org/

![ss](https://user-images.githubusercontent.com/75935068/137271071-91f645c6-163d-427d-afda-aa5b3784481b.png)

**Comment by yous** [comment]
You're right, it seems that the script is a variant of BlockAdBlock. To workaround the problem with BlockAdBlock and EasyList, I had to added the following lines:
```
#@#.pub_300x250
#@#.pub_300x250m
#@#.pub_728x90
#@#.text-ad
#@#.text-ad-links
#@#.text-ads
#@#.textAd
#@#.text_ad
#@#.text_ads
```

But this script doesn't use one of the above, it only uses `.adsBox`. So, I'm thinking adding the `#@#.adsBox` for workaround.
