### ISSUE TITLE
namu.wiki

### ISSUE THREAD

**Issue by aF4buMppY5o64p2Uztzc** [yous/YousList#198]
https://namu.wiki/w/GitHub
Powerlink ad in footer

**Comment by yous** [comment]
Thanks for the report. Updated in c143e57.

**Comment by lemonNsoda** [comment]
Hi, I think this ad avoided blocking again.

**Comment by piquark6046** [comment]
@lemonNsoda Do you use AdGuard?

**Comment by lemonNsoda** [comment]
@piquark6046 
Unfortunately, it doesn't work with my Adguard …

**Comment by piquark6046** [comment]
@lemonNsoda Can you take a screenshot DevTool Element section of the Naver powerlink & send it?

**Comment by lemonNsoda** [comment]
ㅒㅏ But how do I send it..?

**Comment by piquark6046** [comment]
https://github.com/yous/YousList/issues/198#issuecomment-1013725448

Just drag the file into textBox.

**Comment by yous** [comment]
Updated in b3d3aa6, but I think the site monitors filters, so this can be expired soon.

**Comment by lemonNsoda** [comment]
![주석 2022-01-16 025756](https://user-images.githubusercontent.com/81494708/149632557-5aabda61-fa98-4f07-8911-61f0d45a7625.png)

**Comment by piquark6046** [comment]
@lemonNsoda 
Please copy the following rule into user rule and reload the website:
```
namu.wiki#?#article > div:not([id]):matches-attr("/data-v-/"):has(> div:not([id]):matches-attr("/data-v-/") > a[href^="https://saedu.naver.com/adbiz/"])
```

**Comment by lemonNsoda** [comment]
Yeah That ad gone!

**Comment by piquark6046** [comment]
@lemonNsoda Thanks you. Pushed List-KR.
if you want to block the advertisement request, I need the network history of DevTool network section.
However, If you concern your privacy because your network history will be public, you can send it to my email (`piquark6046@protonmail.com`).
Of course, my OpenPGP public key is available at [here](https://keys.openpgp.org/vks/v1/by-fingerprint/6600B38056B9793AD0EA81AED2304DD7CBB69BE5).

**Comment by yous** [comment]
Try after updating YousList.

**Comment by piquark6046** [comment]
> but I checked mobile but it didn't work there

Then, I need the screenshot that has element section in DevTool Inspector of the Naver powerlink.

**Comment by lemonNsoda** [comment]
@yous ok that works on mobile

**Comment by lemonNsoda** [comment]
Thank you to everyone.

**Comment by aF4buMppY5o64p2Uztzc** [comment]
@yous I'm sure they are monitoring filter. Filter has expired again.
