### ISSUE TITLE
inven advertisement 인벤 광고

### ISSUE THREAD

**Issue by b10li** [yous/YousList#203]
www.inven.co.kr/board/lostark
lostark.inven.co.kr

![제목 없음](https://user-images.githubusercontent.com/37690375/151073668-a0f1af9b-c572-4791-b413-9f09e27fb329.jpg)
![제목 없음2](https://user-images.githubusercontent.com/37690375/151073954-7287cda4-5299-4ad2-b906-d4bc51da2b79.jpg)

**Comment by yous** [comment]
When the long banner is blocked, every image of site won't be displayed. Updated to hide banner in sidebar, but the site can block images for this also. 2bdf6e7

**Comment by yous** [comment]
FWIW, mobile version is much cleaner: https://m.inven.co.kr/board/lostark/4811

**Comment by lunamoth** [comment]
https://www.inven.co.kr/board/wow/1896

광고가 다시 나오는 것 같습니다.

![image](https://user-images.githubusercontent.com/99085/153324221-e9e472a5-5f5a-4b80-b141-2dcabefdef2c.png)

**Comment by piquark6046** [comment]
@lunamoth Fetched in List-KR.

**Comment by yous** [comment]
Seems like it's gone?

**Comment by lunamoth** [comment]
KST 2022년 4월 13일 오후 11:11 현재 

와우 인벤 유저 정보 게시판 아래 링크로 접속하면 애드쉴드 광고가 나오더군요. 혹시 차단 지원 가능하다면 부탁드리겠습니다.

https://www.inven.co.kr/board/wow/1896
![화면 캡처 2022-04-13 231035](https://user-images.githubusercontent.com/99085/163199994-e279d184-c279-4f6c-bbd7-8a468f984f7a.jpg)

**Comment by seia-soto** [comment]
@yous Latest working filter for AdShield:

```
loawa.com,ygosu.com,inven.co.kr,ppss.kr##+js(set, innerHeight, undefined)
```

> I am leaving this as comment because I don't know if you accept script injection rules.

**Comment by piquark6046** [comment]
@yous Please close this issue.

**Comment by yous** [comment]
Ad-Shield is removed from inven.co.kr. For Ad-Shield, see: https://github.com/List-KR/microShield
