### ISSUE TITLE
나무위키 나무뉴스가 제거가 되지 않습니다.

### ISSUE THREAD

**Issue by tjtnsgns** [yous/YousList#204]
![K-001](https://user-images.githubusercontent.com/28147257/153113389-b672dd54-8f00-40cb-bd1a-443cedc7df08.jpg)
나무위키에서 나무뉴스를 따로 보지를 않고 자꾸 갱신중이라고 떠서 제거를 하려고 했는 데 며칠동안은 괜찮은 데 다시 나옵니다.
![K-002](https://user-images.githubusercontent.com/28147257/153113547-aaccd19f-b754-4fa9-805b-c404aa00c5a0.jpg)
차단하려고 보려고 해도 하단의 파워링크처럼 계속 변경되는 것 같습니다. 
https://namu.wiki/w/uBlock%20Origin

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/108961

**Comment by yous** [comment]
다음 규칙을 '내 필터' 등에 추가해보시기 바랍니다.

```
namu.wiki##:xpath(//aside/div[@id][h5[text()="나무뉴스"]])
```

**Comment by tjtnsgns** [comment]
pc에서 됩니다.  모바일도 가능할까요?

**Comment by yous** [comment]
모바일용으로는 이걸 추가해 보시기 바랍니다.

```
namu.wiki##:xpath(//div[contains(concat(' ',normalize-space(@class),' '),' app ')]/div[last()]/div[h5[text()="나무뉴스"]])
```

**Comment by tjtnsgns** [comment]
모바일도 적용확인했습니다. 감사합니다.

**Comment by yous** [comment]
일단 이 이슈는 닫도록 하겠습니다.
