### ISSUE TITLE
1412.rest

### ISSUE THREAD

**Issue by 9JI0oFWdNImpT0** [yous/YousList#206]
Anti Adblock Script
https://1412.rest/romance1/6769996
![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f57376d505a33612e706e67](https://user-images.githubusercontent.com/100195064/155098425-85f2c4f1-e7b5-4d86-abb6-7186807887d7.png)

**Comment by 9JI0oFWdNImpT0** [comment]
Fix ublock assets!
thank you

**Comment by 9JI0oFWdNImpT0** [comment]
ublock origin에서 youslist필터를 사용시에는
ublock필터에 의해 해결되었지만
비발디 브라우저의 내장 광고차단기등 ublock필터가 없는 차단기에서
이지리스트와 youslist만 사용할시에는
애드블록방지 스크립트에 감지 되고 있습니다.

youslist에서 해당사이트의 광고차단스크립트인
https://1412.rest/addons/sejin7940_content_hide/adblockDetector.js?20220221130032
를 차단해주시면 좋을것 같습니다.
ublock origin에서는 차단하지 않더라도 애드블록방지 스크립트에 감지되지는 않지만
저 스크립트가 불필요한곳에 연결을 시도하기에
개인정보보호를 위해서도 차단하면 좋을것 같습니다.

항상 감사드립니다.

**Comment by yous** [comment]
제보 감사합니다. 8407827 커밋에서 업데이트했습니다. 추가로 다음과 같은 항목이 있으니 EasyList 등에서 차단하지 않도록 예외를 만들어서 쓰시면 될 것 같습니다.

``` html
<script defer src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'onerror='adError();' onload='adSuccess();' ></script>
```

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js^$domain=1412.rest
```

**Comment by 9JI0oFWdNImpT0** [comment]
감사합니다.
이슈를 닫겠습니다.
