### ISSUE TITLE
네이버 쇼핑 광고

### ISSUE THREAD

**Issue by alexkoala** [yous/YousList#207]
https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%EC%84%9C%EB%9E%8D%EC%9E%A5 (PC)
https://m.search.naver.com/search.naver?where=m&sm=top_hty&fbm=0&ie=utf8&query=%EC%84%9C%EB%9E%8D%EC%9E%A5 (모바일)

![image](https://user-images.githubusercontent.com/44674417/155847281-36d24aa8-dc83-4782-902f-b5ae65a31d69.png)

**Comment by yous** [comment]
제보 감사합니다. 7df4fa0, aa58549 커밋에서 업데이트 했습니다.
