### ISSUE TITLE
네이버 뉴스화면 광고

### ISSUE THREAD

**Issue by hotdog5785** [yous/YousList#208]
현재 쓰고 있는 필터: adguard mobile/adguard dns/youslist/adguard basefilter/list-kr

![D2734A6C-3505-4B99-A115-3AE6DFA035EC](https://user-images.githubusercontent.com/99060747/155850183-304d0b58-20b9-4453-846b-8191eb3b2bbc.png)

m.naver.com

참고: 뉴스 탭을 "새로고침"해야 뜸. 홈화면에서 그냥 넘기면 광고가 안뜸

**Comment by yous** [comment]
제보 감사합니다. a463c79 커밋에서 업데이트했습니다.

**Comment by hotdog5785** [comment]
@yous 
애드가드 기준 필터가 업데이트가 안되어서 계속 보이는건지는 모르겠으나 광고가 사라지지 않고 그대로입니다.

**Comment by yous** [comment]
Safari에서는 계속 보이고 있었네요. cdc9e06 커밋에서 다시 업데이트했습니다.

**Comment by hotdog5785** [comment]
@yous 
뉴스탭과 홈화면을 왔다갔다하면 광고가 사라지나, 뉴스탭에서 새로고침을 하거나 홈화면에서 새로고침 후 홈에서 뉴스탭을 들어가면 다시 광고가 생깁니다. 자꾸 "해줘" 만하는거같아 죄송하네요 ㅜㅜ 컴공이 아니라 화공이라...

**Comment by yous** [comment]
업데이트 이후로는 안 보이는 것 같은데, AdGuard 필터 업데이트가 되어야 하는 걸 수도 있겠네요. 폰에서 YousList가 사용되고 있기는 한 건지 잘 모르겠습니다... AdGuard를 깔아봤는데 List-KR만 들어가는 것처럼 보이고, 필터를 선택하는 옵션이 있는지 잘 모르겠네요.

<img src="https://user-images.githubusercontent.com/853977/156178108-1afe870e-797e-42a2-9c3a-90d4c63862ce.PNG" alt="IMG_8108" width="50%">

**Comment by hotdog5785** [comment]
@yous 

애드가드 특정 youslist의 업뎃이 21년 12월에 멈춰있네요 애드가드쪽 문제인거 같습니다 

![953A9F3C-36E8-46DE-AFD5-2785C9B19205](https://user-images.githubusercontent.com/99060747/156342804-ce0ad229-55d1-4d56-8c65-473c62ad2096.png)

**Comment by yous** [comment]
앱 메인에서 한번 업데이트 눌러보시기 바랍니다. 추가로 'Wi-Fi 환경에서만 자동 업데이트' 등의 옵션이 기본값으로 켜져 있으니 한번 확인해보세요.

**Comment by hotdog5785** [comment]
@yous 
혹시 몰라 애드가드를 삭제하고 다시 까니까 되네요! 잠깐 필터 업데이트가 꼬인거 같습니다. 제 폰 문제인걸로 ㅎㅎ 작동 잘 됩니다 감사합니다
