### ISSUE TITLE
twitter, dcinside

### ISSUE THREAD

**Issue by sharbet** [yous/YousList#209]
twitter: 프로모션, 광고 등이 3/2~로 차단되지 않습니다

[redacted]: 광고 자체는 차단이 되나, 기존에 표시되지 않았던 ad-placement div 등이 다시 나타났습니다. (3/2~)

tested: firefox nightly, bromite, android 12 with Adguard(android)

[link redacted]

**Comment by yous** [comment]
음... dcinside는 로그인 상태에서 저렇게 보이는지 확인해봐야 할 것 같네요.

**Comment by extratype** [comment]
https://github.com/yous/YousList/commit/2e8d3ab6d86e7db22249e495251ef70e517e32c6#diff-7017bf2bd7b249d9f7bc6f2e3d9afdabd86df74e7b327098ce99a32d9976862bR7067
이 필터 때문에 트위터에서 동영상 재생이 안됩니다. 데스크탑 Edge 브라우저 쓰고 있습니다.

**Comment by yous** [comment]
dd15491 커밋에서 업데이트했습니다.

**Comment by yous** [comment]
혹시 dcinside 문제가 아직도 재현이 되면 링크 하나만 알려주시기 바랍니다.
