### ISSUE TITLE
루리웹 룰 갱신

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#21]
루리웹이 ruliweb.daum.net에서 ruliweb.com으로 옮겼는데, 기존 규칙이 아직 남아있어서 한 번 확인해보시라고 이슈로 올립니다.

**Comment by yous** [comment]
사이트도 약간 개편된 것 같네요. 알려주셔서 감사합니다.

**Comment by yous** [comment]
v20160708 버전에서 해결되었습니다.
