### ISSUE TITLE
kakao tv 에서 광고차단을 감지합니다.

### ISSUE THREAD

**Issue by 9JI0oFWdNImpT0** [yous/YousList#211]
https://tv.kakao.com/channel/3193314/livelink/11850678
카카오에서 광고차단을 감지하는지 최근들어 카카오 관련 영상이 재생불가능 합니다.
해당링크의 영상뿐아니라 다른 영상(티스토리등 블로그에 카카오로 올린영상 포함)도 재생이 불가능 합니다.
윈도우에 크로미움 엣지 99버전, ublock origin 기본값에 youslist필터 사용중이고 필터업데이트는 시도 하였습니다.
ublock origin을 끄면 영상이 재상됩니다.

**Comment by yous** [comment]
혹시 EasyList를 사용하고 계신가요? 한번 끄고 시도해보시기 바랍니다.

**Comment by 9JI0oFWdNImpT0** [comment]
EasyList필터를 체크 해제하니
ublock origin을 끄지 않아도 정상 작동합니다.

**Comment by 9JI0oFWdNImpT0** [comment]
youslist필터의 문제가 아니기 때문에
이슈를 닫겠습니다. 감사합니다.

**Comment by yous** [comment]
#180 이슈도 참고하시기 바랍니다.
