### ISSUE TITLE
트게더 ad쉴드로 광고가 보호됨

### ISSUE THREAD

**Issue by hotdog5785** [yous/YousList#213]
![CE52E406-E814-47F0-A9A4-19C9EBD4C276](https://user-images.githubusercontent.com/99060747/158041842-c194ed2f-0e54-40b3-89cf-3a46ed634ed0.png)
![0DD66CDB-5D33-4492-805A-63F18A2A5178](https://user-images.githubusercontent.com/99060747/158041846-ef812052-c95e-4393-8176-7a7499e219f4.png)

+하단부분 광고 빈자리가 완전히 날라가지 않음

예시: https://tgd.kr/s/sizer0346/1049100

**Comment by yous** [comment]
당장 ad-shield 광고를 막기는 어렵고, 나머지 부분에 대해서는 7d270f3 커밋에서 업데이트했습니다.

**Comment by piquark6046** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1741

**Comment by yous** [comment]
현재로서는 광고 자리만 남아있는 것으로 보입니다.

**Comment by piquark6046** [comment]
@yous Please close this issue because Ad-Shield is removed from tgd.kr.

**Comment by yous** [comment]
tgd.kr에서 Ad-Shield가 제거된 것으로 보여 닫습니다. Ad-Shield 광고는 여기를 참조하세요. https://github.com/List-KR/microShield
