### ISSUE TITLE
나무위키 목차가 잘리는 것 같습니다

### ISSUE THREAD

**Issue by pillose** [yous/YousList#215]
아마
https://github.com/yous/YousList/blob/9e780ffe81d86ca9fea68af72b8cd966b5e6be8e/youslist.txt#L5770
이것 때문인 것 같네요. (시간이 없어서 대충 찾아본 거라 아닐 수도 있습니다)

나무위키 맨 아래 광고는
`namu.wiki##div > div > div > div:has(img[src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKMAAAAkCAYAAADl2YrgAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QsRCBULu1xPXgAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAYDSURBVHja7VxfSFtXHP46BLdsLEvxT9uViClIRCqWiO1D62yJUgZ7GCwv3WgZcwlj61720FD0yVCSh73oxjBVupdVaMb6MBijCd1sGYrgWtqGZt2MNLVGrZilxbg+uQfPTU7ivbn33JybXOP9QGLIvcd7zvnO9/t9v3MMYMCAAQMG8rHHGAL94cSA/V0AYwD2V3lXkwD6b/tivwDAK8bU6xK7gYggfRwT3hhk1O8k7bq+1nBs1AnAQX4PAYhr8OAXyOssgAjHdt0ALABSAILGWqgMeJLRAcBPkaUYGS2EAAKBLeR6gWRShBDa9xaQ0UZ+lECMxC7yLBGDjPogo4VSNhbEGVXQASBM/h5ECOUiRPUQciqBiyKqFqZN7dgISDH0xSAjRRJWeAEEFF5rKyBikFJRG1EnF3mWawA6yURWGmrHhlbjXr1Met3r+3HEegzpTAozj3+vyjCtNOcTiNgpohZBooqjlEoqCZsBmQVxgUE5dxS6mnrQ3/eFfPhamoP/562U+4j1GAbPXEIsEcXMZX2SMUKFsE2JFU1PqppwZ6PalQpbQfJ3bCKhvFKIqOxvmKi9ZjCbLLBb27i3G/z0R+Z7xm58U5LS1uh0wadUkNymYBFUHcIPryM8eF3y897W9zF45hJzu2oIbjaVph01FSKZgyqliOVnrGaBxcDsSsSX5piu7x5sZVJRHupc7qJ3iHKnYiHMRYxL4fUGSsT6xouyqLQeldFPqd4scdwCuQSTIudQPVBXONdiv92tMn8ta3oghORYIgr35Q+2wu3bW4r1YuO5aCi+NfQQAPLuYXbn5gZdu2mHDMkihLA2CbMQAN8dllLh0tqIaIVGy9Zu29O1J9s+y7zMILE8ryqM55OxHpmXGd2SMUipWkoiXIdEjAdrAV0MToWLxEIpthxYCtazVJ/9Kg0ZN/yz+BeWU0nREJpYnlethmJt6ZWMIYXKJkc+gawsJFVanGZRXq/KcfCrIDNXfP/HcE7BSLFbDc47B+B650OEJn/ASMSXlxoAwPp/67olo5giybndYltuLLs8Ssg3C20OcpQ1X/S+F4Bt36Hse9OrbwAArI3N2TphnbkBdeb6vPuGrl7k9gxvvmbeUpXk3zuGjJYScy65iQ1wIKuWZNSE+LZ9h0RLKqZaE+zWNsQSUaymV7CaXsHKv8tYTiW5P8OBvQcBAItrC7ogo03BYMeLhDo/lWfSpRyehwukVFfI77yQrnvyMHGa5Ixq8z0htPLA4eYOAMD9J39yJaObuMbCAQ1LDPAm3T8FZAzIkDGugYN2I1dGKmY4guB/dMyiMj8tGUJuKJR1BMSeRnEnMY07iWkMXb2IdIbPGoklonj07B5XMoqF0lLDq5Y5phwRrhU8e6HSOijFHCWvHo59KHt5qqW+HZ+d/gqOlq7idv/RDL779WsuBOLlxgvJGGIMi4UO18FZVUpZBG7q/ggJw7MSZSA/eXa3jIKzIlVOMrbUt2PYcwWmWhNW08/w290bWFxbwPONdNZoHNh7ECc7+uBo6cJw0xV8OfoxF0JqQUYeNT5ekMox/QxkFEJwr4zD7gQwh9x5ygAndS6atvFu8GyPB6ZaE27du4mB0OeS141EfPC5vkV3+ymc7fHkXVvozvNCP9llOdnRl80Ti0HNCR69ntqRUiil5LAxGoe4iGOvVIqiCg1vNQIAJh/Ii/Hkgwi6209l75Fz5/mkrN9WKhKDmhM8NahOCORSUuuzSFxXrAKgO9yfvwu7tQ3nnB7cSUxjdT0paW7OOT3Ze7TK/ypV2tEjgsjtfYeLmAkXcgd5C10vz/xRc0xMjeNo63FYG5rwk/cmYonoNrIdbu7IKl9i5TEmpsZ11YdqJWOAEEwwMk4RsjlFCBzYqR1eXU/io5HTOO8cwNHW47Bb20RDrmBuJqbGJdWzGshIu0eWAhbLkS+W9oX/LqRP3IjlgCHqZ8djJOLDCBmlwuJ2qecNtcZu+q4dZxFy6wonBuybu2hecNsX21PNYRo7hXgGcjC+a0efSO6ivi4ZZNQ3+ulJqmIsAPjEmG4DBgwYkML/0ua9lPDwfmAAAAAASUVORK5CYII="])`

`namu.wiki##div > div > div > div:has(img[src="//w.namu.la/s/cc74b25a310cfe8aad3f1aab7ebe3e3cea613f3899715bea7d2cce8f3a2c055f"])`

이렇게 하면 삭제되더군요

**Comment by yous** [comment]
2d20110 커밋에서 업데이트했습니다. 추후 생기는 문제는 #201 이슈에서 다루도록 하겠습니다.
