### ISSUE TITLE
나무위키 문서역사가 보이지 않습니다.

### ISSUE THREAD

**Issue by WBWBWBS** [yous/YousList#216]
예시 : https://namu.wiki/history/A

필터를 끄면 문서 히스토리가 보이는데 필터를 켜면 문서 히스토리가 안 보입니다.

**Comment by yous** [comment]
한번 필터 업데이트 해보시겠어요? 사이트 업데이트가 자주 되다보니 이전 버전 중에 문제가 있었던 것 같습니다.

**Comment by WBWBWBS** [comment]
해결된거같습니다. 감사합니다.
