### ISSUE TITLE
이젠 YousList를 활성화 하면 그냥 나무위키 문서자체가 안보이는 군요.

### ISSUE THREAD

**Issue by DevilNANA** [yous/YousList#218]
![12345](https://user-images.githubusercontent.com/27700862/159479124-e58a3589-6a28-411c-997b-ba3cc361de8b.PNG)
![54321](https://user-images.githubusercontent.com/27700862/159479132-1a626b75-8440-40a0-b225-698c765f2021.png)

참고바랍니다.

**Comment by yous** [comment]
00d9a62 커밋에서 업데이트했습니다.

**Comment by yous** [comment]
추후 생기는 문제는 #201 이슈에서 계속 다룹니다.
