### ISSUE TITLE
필터 수정 요청

### ISSUE THREAD

**Issue by kang-chan** [yous/YousList#22]
1.
zangsisi.net##body>center
zangsisi.net##div.fixed-top
위 두개의 필터 때문에 해당사이트의 내용이 아예 나오지 않습니다. 
수정을 바랍니다. 

2. 
http://www.spojoy.com/live/
이 사이트에 들어가면 원래는 맨아래에 큰 광고가 있는데, 
귀 필터로 인해 광고는 안보이게 되었지만, 
대신 스크롤이 자동으로 아래로 휙 가버리는 스크립트는 여전히 남습니다. 
스크롤이 맨 아래 광고가 있던 자리로 자동 이동되는 현상을 막아주시길 간청드립니다. 

감사합니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사드립니다.

- zangsisi.net의 필터는 업데이트 했으니 확인 부탁드립니다.
- spojpy.com 사이트의 맨 아래에 나타나는 광고는 살펴보니 realclick 광고인데, 자동으로 스크롤하는 스크립트를 특정 주소를 통해 로드하는 방식이 아니고 웹 페이지 자체에 포함시키는 방식이라서 차단하기 어렵습니다. 예전부터 굉장히 고치고 싶었던 문제인데, Adblock Plus 필터로는 막기 어려울 것 같습니다. 해당 사이트의 다른 광고는 추가로 업데이트 했습니다.

**Comment by yous** [comment]
v20160709 버전에서 수정되었습니다.
