### ISSUE TITLE
사용하는 페이지가 막힙니다.

### ISSUE THREAD

**Issue by KritzA** [yous/YousList#220]
https://ko.ff14angler.com/
파판하면서 낚시 정보 얻을 때 쓰는 사이트인데, YousList를 사용하면 사이트가 막혀버립니다.
![2022-03-23_191820](https://user-images.githubusercontent.com/55195717/159676863-7b8ead7d-687f-43ec-a7c0-3918a3046e57.png)
![2022-03-23_191830](https://user-images.githubusercontent.com/55195717/159676875-eb898ba3-7ba9-45ea-ab83-161ea5d87c6c.png)

**Comment by yous** [comment]
d2b2cca 커밋에서 예외 처리했습니다. 크롬에서 자리는 남는데, 별 문제는 없어 보입니다. Firefox에서는 기본적으로 adsbygoogle.js를 차단해서 이걸 이 사이트에서는 끄든지 해야 사이트가 보일 것 같네요.

**Comment by yous** [comment]
일단 해결된 것으로 보고 닫겠습니다.

**Comment by KritzA** [comment]
감사합니다. 처음 쓰는거라 예외 처리하시고 닫으신 줄 알았습니다.
