### ISSUE TITLE
https://windowsforum.kr

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [yous/YousList#221]
#https://github.com/List-KR/List-KR/issues/240#issue-1171967042
After the ad is blocked, blank space 
![1](https://user-images.githubusercontent.com/101787143/160416901-ad4d4e0a-4864-4eb5-bc63-c73b62b5e6d1.png)

**Comment by yous** [comment]
They have `margin-top: 120px;` for `#content .content`, so this can't be removed without modifying their own CSS.

**Comment by yous** [comment]
Try this on uBlock Origin:
```
windowsforum.kr##div.top_banner+div.content:style(margin-top:10px!important)
```

**Comment by yous** [comment]
Closing now.
