### ISSUE TITLE
ppss.kr clickable leftovers and one ad image

### ISSUE THREAD

**Issue by JobcenterTycoon** [yous/YousList#222]
`https://ppss.kr/archives/252922`

<img width="828" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/161735902-19abaa48-9a7d-4e74-80a7-b4de393ddd7b.PNG">

Adblocker: uBlock Origin default + YousList

Filter suggestion:
```
||ppss.kr/wp-content/uploads/202*/*/cartax-*.jpg$image
ppss.kr##div[onclick*="www.mediacategory.com/servlet/sdrc?kno="]
ppss.kr##div[style="width:100%;height:300px; margin-top:0px;"]
```

**Comment by yous** [comment]
Thanks, updated in 66c431e.

**Comment by yous** [comment]
Also updated in 6febcb3, but this can be blocked by site later.

**Comment by JobcenterTycoon** [comment]
```
ppss.kr##div.ppss-title-banner
ppss.kr##div.wing_banner
```

triggers anti adblock but `||ppss.kr/wp-content/uploads/202*/*/cartax-*.jpg$image` not and it blocks the ads too. (yes i know ad-shield can bring the ads back but i counter this in uBO)

**Comment by yous** [comment]
Okay, let's try. 6697dc5.

**Comment by JobcenterTycoon** [comment]
Thanks, works very well
