### ISSUE TITLE
unblocked ad/tracking domains

### ISSUE THREAD

**Issue by JobcenterTycoon** [yous/YousList#224]
`​api.linkmine.co.kr`
`nefing.com` (seems to be a domain from `adpick.co.kr`)

When i click on a adcrap ad on `ppss.kr` or `ygosu.com` i get redirected through `api.linkmine.co.kr` and `nefing.com`. 
<img width="918" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/162572838-2adf0859-347e-415b-b0be-29f484d7bf74.PNG">

See https://github.com/List-KR/List-KR/issues/269#issuecomment-1093936666

Adblocker: uBlock Origin default + YousList

**Comment by yous** [comment]
Updated in f02036e.

**Comment by JobcenterTycoon** [comment]
The filter doesn’t cover the redirection i still get redirected through it. Only full blocking or adding `$document` works

**Comment by yous** [comment]
Hmm... But then when user clicks an ad, it just blocks to redirect. Is that meaningful?

**Comment by JobcenterTycoon** [comment]
Yes so a user know he goes through tracking sites. For my opinion its a benifit

**Comment by yous** [comment]
Okay, already redirections are blocked by Safari Content Blocker, and uBlock Origin offers "turn off this rule once" options. Updated in da8869a.
