### ISSUE TITLE
YousList와 List-KR 통합?

### ISSUE THREAD

**Issue by ghost** [yous/YousList#228]
@yous @piquark6046 이번에 uBlock Origin에서 YousList가 제거되고 List-KR로 변경되었던데 YousList가 List-KR로 통합되는건가요?

**Comment by yous** [comment]
uBlock Origin에서 한국 지역 필터를 교체했고, 이유는 모릅니다. YousList가 다른 필터와 통합하는 것은 아닙니다. 별도로 YousList를 구독하면 계속해서 사용하실 수 있습니다. https://github.com/gorhill/uBlock/commit/ed0f7ae3ce1fbc9445e5c9bca0890fb86ab3d0b9

**Comment by piquark6046** [comment]
https://github.com/yous/YousList/issues/228#issuecomment-1126106467
Yes, List-KR blocks only advertisement and anti-adblock.
if you want to block tracker or anti-rightclick, please subscribe AdGuard Annoyances filter and AdGuard Tracking Protection filter. 

---

If you have an issue in namu.wiki, please read [this comment](https://github.com/List-KR/List-KR/issues/236#issuecomment-1086910452).

And, to block [Ad-Shield](https://ad-shield.io), please use microShield that will be available.
