### ISSUE TITLE
tvple.com

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#23]
http://tvple.com/ 에 광고 필터 감지루틴이 있는데 필터 규칙만으로도 우회가 되네요. 거기에 대해 역작업이 진행되고 있어 계속 가능할지는 모르겠지만요.

SlowMemory/List-KR@c5a7af49582103a844726d0d0e0b833585176e19
SlowMemory/List-KR@5ef0c87ce42e390d717a4cc3e4048832869c74ce

필터는 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.hi) 을 적용받아 크레딧을 명시하면 사용할 수 있으니 한 번 검토해주시기 바랍니다.

**Comment by yous** [comment]
제보 감사드립니다. 일단 제가 크롬과 사파리에서 몇 가지 주소를 테스트했을 때 광고 차단이 감지되는 것 같지는 않았습니다. 혹시 감지되는 URL이 있다면 알려주시기 바랍니다. 해당 사이트에서 나타나는 광고는 추가로 차단했습니다.

**Comment by yous** [comment]
v20160714에 포함되었습니다.

**Comment by yous** [comment]
tvple.com 관련해서 제보를 한 번 더 받았는데, EasyList 등의 다른 필터를 사용하면 구름이 보이지 않는 현상이 나타납니다. [FuckAdBlock](https://github.com/sitexw/FuckAdBlock)과 비슷한 방법을 사용하는 것 같습니다. EasyList에 `##.text-ads`, `##.text_ads` 등의 규칙이 있어서 감지됩니다.

**Comment by nagato7** [comment]
예, 그렇습니다. 다른 필터와의 충돌은 issue에 올릴 사항이 아니라 생각해 말씀드리지는 않았지만요.
일반적인 규칙 감지라면 해당 부분에 대한 예외처리를 하면 될 것도 같지만, FuckAdBlock같은 솔루션이라면 필터로는 해결하기 어렵겠군요.

**Comment by yous** [comment]
FuckAdBlock은 해당 요소를 가리지만 않으면 감지되지 않는데, EasyList에 있는 필터에도 예외를 적용할 수 있을지, 그걸 이 필터에서 처리해줘야 하는지는 잘 모르겠습니다.

**Comment by Fenslett** [comment]
@nagato7 서드파티 필터 중에 `Anti-Adblock Killer | Reek`가 있습니다. 해당 필터를 사용해 보니, adblock 플러그인 감지 스크립트를 어느 정도는 무력화시키더군요. 완벽하게 우회하지는 않았지만, 그래도 도움이 되지 않을까 싶습니다.

**Comment by nagato7** [comment]
@Fenslett 해당 필터로는 tvple은 무효화되지 않는 듯합니다.
@yous tvple.js를 찾아보니 말씀하신대로 일반적 필터에 대한 검출 로직이 있더군요. 제대로 된 테스트를 한 건 아닙니다만 제 환경에서는 다음 필터를 적용하면 Easylist를 사용하더라도 우회가 가능했습니다.

```
~tvple.com##.pub_300x250
~tvple.com##.pub_300x250m
~tvple.com##.pub_728x90
~tvple.com##.text-ad
~tvple.com##.textAd
~tvple.com##.text_ad
~tvple.com##.text_ads
~tvple.com##.text-ads
~tvple.com##.text-ad-links
~tvple.com##div[style="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;"]
```

(관리자께서 판단하시겠지만) 타 필터의 문제이니만큼 굳이 youslist에서 이 부분을 넣을 필요는 없다고 생각합니다.
