### ISSUE TITLE
네이버 홈화면 망가짐 문제

### ISSUE THREAD

**Issue by rock5684** [yous/YousList#231]
![E65A95DC-6ABC-47A1-8D83-948A903CE5AC](https://user-images.githubusercontent.com/104014662/174806344-8113376f-2f5b-4340-8605-427f93abf369.png)

왼쪽 스와이프로 뉴스탭으로 넘어가지지도 않습니다

**Comment by yous** [comment]
사용하시는 필터가 뭔가요?

**Comment by yous** [comment]
AdGuard에서 기본 필터 + YousList로 설정했을 때 현상 재현이 안 되는 것 같습니다. 다른 필터나 별도의 앱을 사용하시는 건가요?

**Comment by rock5684** [comment]
@yous list kr / youslist / 베이스 필터 사용중입니다

**Comment by rock5684** [comment]
@yous  nextdns에서 list kr /youslist/ 애드가드 베이스필터를 사용중이라 문의 드렸는데, nextdns에서  youslist를 껐다 키니 해결되었습니다~!
