### ISSUE TITLE
Unicornsoft wants to add youslist into their filters list

### ISSUE THREAD

**Issue by piquark6046** [yous/YousList#233]
https://support.getunicorn.app/hc/ko/community/posts/9407608758553/comments/9704771839129

**Comment by piquark6046** [comment]
@yous What do you think about it?

**Comment by yous** [comment]
The [license](https://github.com/yous/YousList/blob/master/README.md#license) of YousList is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), so as long as the "Attribution" term is satisfied, I'm okay with it.
