### ISSUE TITLE
클리앙 계정 부분이 블락이 됩니다. 

### ISSUE THREAD

**Issue by webzeroacs** [yous/YousList#237]
clien.net##div.nav_container>div.aside>div[class^="side_"]
이 부분으로 클리앙 계정 부분이 블락이 되어 문제가 되고 있습니다.

**Comment by yous** [comment]
그러네요. 로그인하면 `.account_section` 부분이 `.side_account`로 바뀌네요. be19e9e 커밋에서 수정했습니다.

**Comment by yous** [comment]
해결된 것으로 보고 이 이슈는 닫겠습니다. 다른 문제가 생기거나 광고가 보이면 제보해주세요.
