### ISSUE TITLE
광고제거 요청 nate.com 에서 네이트앱으로 보기 없애주세요

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#242]
안녕하세요 늘 감사드립니다

아이폰 ios safari adguard 광고 제거 부탁드려요

하단에 "네이트앱으로 보기" 없애주세요

캡처 첨부합니다

필터는 오직 youslist 단1개만 사용중입니다.

https://m.news.nate.com/view/20230318n05915

![7F0F0DDB-C2EE-4D47-B1F8-3D3304214123](https://user-images.githubusercontent.com/15683789/226092667-96c1b7f5-5eec-4b38-94ea-0250b8571b7e.jpeg)

**Comment by yous** [comment]
안녕하세요, 해당 영역의 경우에는 자사 제품을 표시한 것이라 바로 차단하기에는 애매한 부분이 있어서요, 사용자 필터로 다음 규칙을 추가하시면 될 것 같습니다. iOS AdGuard 앱의 보호 탭(두 번째 탭) → Safari 보호 → 사용자 규칙 → 새 규칙 추가 버튼을 통해 추가하실 수 있습니다.

```
m.news.nate.com##div.viewAppPOP
```

**Comment by swbaek81** [comment]
감사합니다
