### ISSUE TITLE
광고공백

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#246]
안녕하세요 늘 감사히 사용하고 있습니다

광고공란제거 부탁드려요 

아이폰 사파리 입니다

https://m.news.nate.com/section?mid=m01&sq=972651

![IMG_2440](https://user-images.githubusercontent.com/15683789/230088098-c2212221-a613-4b10-acaa-b1f7ab529bdd.jpeg)

**Comment by yous** [comment]
제보 감사합니다. 8d2f2ec 커밋에서 업데이트했습니다.
