### ISSUE TITLE
meeco.kr 광고공란 제거

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#249]
늘 감사히 사용중입니다

공란제거 부탁드려요

아이폰 사파리 입니다

https://meeco.kr/news/37020056

![IMG_2459](https://user-images.githubusercontent.com/15683789/230754654-af25924c-b586-4d79-b0bf-4919abf9cbfb.jpeg)

**Comment by yous** [comment]
92a7839 커밋에서 일부 업데이트했습니다. 특정 부분은 일반 필터로 가려버리면 스크립트가 감지하는 것 같고요, AdGuard 사용자 필터로 다음을 추가하면 될 것 같습니다.

```
meeco.kr#$#ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type]) { height: 0 !important; padding: 0 !important }
```
