### ISSUE TITLE
Should we block this autoplaying Youtube video?

### ISSUE THREAD

**Issue by fenslett** [yous/YousList#25]
I found a website(www.itworld.co.kr) posted an advertising Youtube video that isn't showed up on screen. 
Thought it was hidden by some filters, so disabled Adblock, but still remains hidden. 
After examining, turns out an administrator deliberately made it disappeared using script.

![image](http://i.imgur.com/r7wnQEo.jpg)
![image2](http://i.imgur.com/oiW93mA.jpg)
(Click to zoom)

As you might see, the script hiding the video is located inside the main index page. 
So, we have to block it using URL-specific rule if needed.

Here's a rule:
```
||www.youtube.com/embed/bDx8qS-FF8Q$object,domain=itworld.co.kr
```

**Comment by yous** [comment]
Hi, thanks for letting me know about this. 🙇

It seems that they defined `show_youtube()` and `hide_youtube()` and they just are not using them. `show_youtube()` dims background and YouTube player will appear at the center of the screen. So I think it's not enough just blocking the video URL. I tried to hide `#youtube_div`, and it's still hidden after the call of `show_youtube()`.

```
itworld.co.kr##div#youtube_div
```

Again, thanks for the report!
