### ISSUE TITLE
https://meeco.kr 공란

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#253]
안녕하세요 

공란이 남는데 제거 가능할까요 감사합니다

사용자필터를 사용해도 가려지지 않네요

meeco.kr#$#ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type]) { height: 0 !important; padding: 0 !important }

아이폰 사파리 입니다

https://meeco.kr/news/37082315

![IMG_2490](https://user-images.githubusercontent.com/15683789/234005539-86a1e927-c54b-48e5-8731-d17b433b0cdb.jpeg)
![IMG_2489](https://user-images.githubusercontent.com/15683789/234005548-f20705da-84aa-45db-bcae-622fa0b0cb8b.jpeg)

**Comment by yous** [comment]
지금 보니까 CSS 규칙은 iOS AdGuard에서도 지원 안 되는 것 같네요. https://adguard.com/kb/ko/general/ad-filtering/create-own-filters/#cosmetic-css-rules

>  **Compatibility with different versions of AdGuard**
>
> CSS rules are not supported by AdGuard Content Blocker.

**Comment by piquark6046** [comment]
https://github.com/yous/YousList/issues/253#issuecomment-1527137517

아니요. Safari 고급 보호를 활성화하면 되는데요.

**Comment by yous** [comment]
설정 → Safari → 확장 프로그램에서 콘텐츠 차단기 AdGuard — Custom, 확장 프로그램 AdGuard 켜주면 적용되네요. AdGuard에서는 고급 보호 기능 켜고요.

**Comment by swbaek81** [comment]
혹시 youslist 또는 listkr 필터를 단독으로 On하고도(즉 베이스 필터 조차 off) 하고도 되나요?

**Comment by yous** [comment]
네, 그 대신 사용자 필터를 써야 하니까 "AdGuard — Custom" 항목은 Safari 설정에서 켜줘야 해요.

**Comment by piquark6046** [comment]
YousList는 특정 언어에 등록되어 있지 않나요?

**Comment by yous** [comment]
이 규칙이 사용자 필터입니다.

```
meeco.kr#$#ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type]) { height: 0 !important; padding: 0 !important }
```

**Comment by yous** [comment]
기존에는 1Blocker 호환성을 위해서 `#$#` 등을 사용하는 규칙을 하나도 추가하지 않고 있었는데, 모바일에서는 AdGuard를 쓰면 환경 상관없이 CSS 규칙도 가능하니까 여기에도 고급 필터를 추가해야 하나 하는 생각이 드네요.

**Comment by piquark6046** [comment]
uBO에서 YousList 대신에 List-KR을 선택한 이유도 고급 필터를 사용해서 그런 듯 해요.
근데, 이렇게 되면 AdGuard와 uBO에서만 작동이 가능하게 되죠.

**Comment by yous** [comment]
아직 Adblock Plus에서 지원을 안 하는군요. https://help.adblockplus.org/hc/en-us/articles/360062733293#elemhide_basic

**Comment by yous** [comment]
일단은 이 이슈도 해결된 것으로 보고 닫겠습니다.
