### ISSUE TITLE
m.sportsseoul.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#263]
공백제거 부탁드립니다. 감사합니다

아이폰, 에드가드프로, 사파리

https://m.sportsseoul.com/news/read/1315781?ref=naver

![image](https://github.com/yous/YousList/assets/15683789/96026a33-9af4-421d-b536-9a16624c1816)

![image](https://github.com/yous/YousList/assets/15683789/02a635e2-3789-4ce3-9c7c-8a694b9dba7b)

**Comment by yous** [comment]
fdd218c 커밋에서 업데이트했습니다.
