### ISSUE TITLE
danawa.com/mobile

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#264]
광고제거 부탁드려요 감사합니다

아이폰 에드가드프로 사파리

https://search.danawa.com/mobile/dsearch.php?keyword=cf-sv1

![image](https://github.com/yous/YousList/assets/15683789/09b99557-c99d-435a-b83f-abc6a4a19c26)

**Comment by yous** [comment]
9bd4498 커밋에서 업데이트했습니다.
