### ISSUE TITLE
inven.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#265]
광고제거 부탁드려요 감사합니다

PC 
에드가드프로 
엣지 브라우저

https://www.inven.co.kr/board/webzine/2097/2083547

![image](https://github.com/yous/YousList/assets/15683789/f77c5c18-d756-4f05-aa8a-cb1db6636a4b)

**Comment by yous** [comment]
67a0715 커밋에서 업데이트했습니다.

**Comment by swbaek81** [comment]
필터업데이트 후에도 
새로고침 하다보면 광고가 나올때가 있어요

https://www.inven.co.kr/board/webzine/2097/2083547

![image](https://github.com/yous/YousList/assets/15683789/a7dc4c67-b3d7-4ff1-adbd-22d7ee85f917)
