### ISSUE TITLE
YousList의 다른 필터 리스트

### ISSUE THREAD

**Issue by piquark6046** [yous/YousList#271]
새로운 YousList 필터 리스트를 추가하실 계획이 있으시나요?

https://github.com/yous/YousList/issues/253#issuecomment-1527479706

**Comment by yous** [comment]
아직은 미정입니다. 만약 추가한다고 해도 youslist.txt 파일에 같이 제공할지, 별도의 파일로 따로 제공해서 선택적으로 사용할 수 있게 할지도 결정해야 하고요.
