### ISSUE TITLE
m.news.nate.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#275]
광고제거 부탁 드립니다 감사합니다

이이폰 사파리 애드가드프로

https://m.news.nate.com/hangzhou/news?ymd=20231007#news1831

![image](https://github.com/yous/YousList/assets/15683789/a88169fc-ada3-4d15-9afb-4b1fc215d2c3)

**Comment by yous** [comment]
0a11d32 커밋에서 업데이트했습니다.
