### ISSUE TITLE
m.zum.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#276]
아이폰 사파리 애드가드프로
youslist

광고제거 부탁드립니다 감사합니다

https://m.zum.com/

https://m.news.zum.com/articles/86167008?cm=front_news_text_1&r=2

![image](https://github.com/yous/YousList/assets/15683789/94c137ca-31a1-4d13-9409-b931fff0c315)

![image](https://github.com/yous/YousList/assets/15683789/384e09ad-5aec-4c92-a254-b81d7e287517)

**Comment by yous** [comment]
제보 감사합니다. dd41882, bba651a 커밋에서 업데이트했습니다.
