### ISSUE TITLE
www.etfcheck.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#278]
아이폰 사파리 애드가드프로
youslist

광고제거 부탁드립니다 감사합니다

https://www.etfcheck.co.kr/mobile/main

![image](https://github.com/yous/YousList/assets/15683789/d8d4b3b8-ca10-410c-88a8-64c21c5de0c2)

**Comment by yous** [comment]
fcd9e1f 커밋에서 업데이트했습니다.
