### ISSUE TITLE
모바일 DCinside에서 빈칸

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#28]
![Imgur](http://i.imgur.com/y8Cmmew.png)

모바일 DC에서 광고 자체는 필터링되는데 빈칸이 남습니다.

**Comment by fenslett** [comment]
![1](https://cloud.githubusercontent.com/assets/14074081/22879629/45d6ab4a-f222-11e6-9188-a4fc69ad6d34.png)
![2](https://cloud.githubusercontent.com/assets/14074081/22879619/3b292cd6-f222-11e6-9533-5cd79534f55c.PNG)

두 element 모두 id 값을 갖고 있으니, 

```
m.dcinside.com##div#set_list_bottom
m.dcinside.com##li#set_list_middle_ad
```

위 규칙만 추가하면 될 듯 합니다.

**Comment by fenslett** [comment]
Pull request for #29

**Comment by yous** [comment]
제보해주셔서 감사합니다. v20170214에서 확인하실 수 있습니다.
