### ISSUE TITLE
m.ygosu.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#284]
공벡제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
youslist 

https://m.ygosu.com

![image](https://github.com/yous/YousList/assets/15683789/6270c4d2-45e1-4974-9687-0bb6cab9765d)

**Comment by yous** [comment]
81f0007 커밋에서 업데이트했습니다.

**Comment by swbaek81** [comment]
필터업데이트는 방금 업데이트 했는데요
오늘부터 갑자기 광고가 다시 나옵니다

![image](https://github.com/yous/YousList/assets/15683789/4992d684-7a68-41c9-a020-dec89524d003)

**Comment by yous** [comment]
아, 이건 확인해 보니 Ad-Shield 때문입니다. https://github.com/List-KR/microShield 사용하면 해결 가능합니다. iOS 앱 Userscripts를 쓰면 Safari에서도 사용할 수 있습니다. https://itunes.apple.com/us/app/userscripts/id1463298887

**Comment by swbaek81** [comment]
listkr + 마이크로쉴드 조합으로는 광고차단이 되는데

yourlist + 마이크로쉴드 조합으로는 광고 차단이 안되요

**Comment by yous** [comment]
여러 번 새로고침하면 간간이 보이긴 하는 거 같네요. 한 군데가 막히면 다음 번에 다른 곳에 만드는 것처럼 보여요. fb34e86 일단 맨 위에 크게 보이는 경우는 없도록 합니다.
