### ISSUE TITLE
tvreport.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#286]
광고제거 부탁드려요 감사합니다

아이폰 사파리 애드가드프로
youslist

https://tvreport.co.kr/breaking/article/762991/

https://tvreport.co.kr/broadcast/article/762869/

![image](https://github.com/yous/YousList/assets/15683789/6401edd4-a51e-453f-b708-84fd466d11e4)

![image](https://github.com/yous/YousList/assets/15683789/b2d915e6-61de-4669-b2c3-431d98d3c859)

**Comment by yous** [comment]
54fdefa 커밋에서 업데이트했습니다.
