### ISSUE TITLE
newautopost.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#287]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
youslist

https://newautopost.co.kr/auto-newsroom/article/56718/

![image](https://github.com/yous/YousList/assets/15683789/9cda5e03-8be0-4ac2-910f-79e5567d7dd0)

**Comment by yous** [comment]
8bb1315 커밋에서 업데이트했습니다.

**Comment by swbaek81** [comment]
혹시 이 부분도 제거 가능할까요? 감사합니다

![image](https://github.com/yous/YousList/assets/15683789/bd8d4aa6-896b-4b4a-9c17-750ddd11bb55)

**Comment by yous** [comment]
b2af4a5 커밋에서 업데이트했습니다.
