### ISSUE TITLE
mememedia.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#289]
광고제거 부탁드려요 감사합니다

아이폰 사파리 애드가드프로
youslist

https://mememedia.co.kr/meme-video/article/51637/

![image](https://github.com/yous/YousList/assets/15683789/ccb3c37f-f392-4bcf-b73a-7d7a8dbd7f30)

**Comment by yous** [comment]
27d1539 커밋에서 업데이트했습니다.
