### ISSUE TITLE
tvhot.cc

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#291]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로 
youslist

https://tvhot.cc/
https://tvhot.cc/drama/1173/4049180

![image](https://github.com/yous/YousList/assets/15683789/7a333048-3f4e-4935-afa3-7f38ee55417e)

![image](https://github.com/yous/YousList/assets/15683789/52c7f92a-e774-4282-b722-5868fbeea4e5)

**Comment by yous** [comment]
eb0a5b2 커밋에서 업데이트했습니다.
