### ISSUE TITLE
m.inven.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#293]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
youslist

https://m.inven.co.kr/board/webzine/2097/2153885

![image](https://github.com/yous/YousList/assets/15683789/37095421-d211-4132-840b-20c95c1eeede)

![image](https://github.com/yous/YousList/assets/15683789/c33a7367-55a8-4b09-b51e-f7b21a8d0841)

**Comment by yous** [comment]
b629c88 지금은 업데이트가 된 건지 안 보이는데, 위쪽 공백은 제거했습니다.

**Comment by yous** [comment]
096075e 아래쪽 공백도 제거해뒀습니다.
