### ISSUE TITLE
mlbpark.donga.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#295]
공백제거 부탁드려요 감사합니다

아이폰 사파리  애드가드프로
youslist

https://mlbpark.donga.com/mp/b.php?p=1&b=bullpen&id=202310190086644190&select=&query=&subselect=&subquery=&user=&site=&reply=&source=&pos=&sig=hgjLGY2gjhTRKfX2h3aXHl-gKmlq

![image](https://github.com/yous/YousList/assets/15683789/f1ebfb4b-5a38-4bfd-8b4d-ecb5fb822aad)

**Comment by yous** [comment]
c7c35dd 커밋에서 업데이트했습니다.
