### ISSUE TITLE
ppss.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#296]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
youslist

https://ppss.kr/
https://ppss.kr/archives/264391

![image](https://github.com/yous/YousList/assets/15683789/926addf4-affe-42b3-b3e3-80deba716aaa)

**Comment by yous** [comment]
fea3777 커밋에서 업데이트했습니다. [microShield](https://github.com/List-KR/microShield)와 같이 사용하면 문제 없을 것 같네요.

**Comment by piquark6046** [comment]
@yous 애드쉴드가 해당 사이트에서 제거된 상태입니다.
