### ISSUE TITLE
m.tenbizt.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#298]
이것도 혹시 제거 가능할까요? 감사합니다

아이폰 사파리 애드가드프로
youslist

https://m.tenbizt.com/culture/article/60662/

![image](https://github.com/yous/YousList/assets/15683789/c2043450-c9f2-4bce-9753-680e0a3822e9)

**Comment by yous** [comment]
5990db6 커밋에서 업데이트했습니다.
