### ISSUE TITLE
m.mt.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#299]
공백제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
youslist 

https://m.mt.co.kr/renew/view.html?no=2023101915191353851&NTR_P#_across

![image](https://github.com/yous/YousList/assets/15683789/df48e8e0-14a3-427f-8a37-e2a23887b721)

![image](https://github.com/yous/YousList/assets/15683789/65d8b782-0dd1-4bde-9f90-779b6a9ed8df)

**Comment by yous** [comment]
70153b3 커밋에서 업데이트했습니다.
