### ISSUE TITLE
Problem with making rules using python 2.6 or below

### ISSUE THREAD

**Issue by fenslett** [yous/YousList#30]
There are compatibility issues when generating `Rules.1blockpkg` and `Rules.1blockpkg.json`. <br/> `TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'` error is brought on if the following scripts are executed with *python 2.6 or below*:
* `./bin/generate_rules.py youslist.txt > Rules.1blockpkg.json`
* `./bin/minify_pkg.py` 
* `./bin/prettify_pkg.py` <br />
  See this: ![1](https://cloud.githubusercontent.com/assets/14074081/22896856/020c94e0-f265-11e6-8930-8954e615db57.png)

 This error comes from the incompatibility between *python 2.7* and *2.6 (or below)* since `json` package in *python 2.6* doesn't include `object_pairs_hook` keyword([Can I get JSON to load into an OrderedDict in Python?](http://stackoverflow.com/a/6921842)). To fix this, every contributor who tries to add new rules with *python 2.6* has to install `simplejson` package in advance and insert this code:
``` python
#import json
import simplejson as json
```

I think there are two solutions for this problem:
1. write another script for *python 2.4 and 2.6*
2. check what version of the Python Interpreter is interpreting the script, and import module conditionally (looks a bit messy, though)
  ``` python
  import sys
  if sys.version_info >= (2,7):
	import json
  else:
	import simplejson as json
  ```
  ![2](https://cloud.githubusercontent.com/assets/14074081/22919813/4fc76668-f2d5-11e6-8b15-d1dc733b5ad1.png)

**Comment by yous** [comment]
Thank you for the report! I added `requirements.txt` and `requirements26.txt`. For python >= 2.7, running `pip install -r requirements.txt` is enough, whereas python < 2.7 needs to run `pip install -r requirements26.txt` additionally.
