### ISSUE TITLE
dcinside 마이너 갤러리 안티 애드블락

### ISSUE THREAD

**Issue by chbchb59** [yous/YousList#34]
디시인사이드에서 안티 애드블락 스크립트를 도입했었는데

어제자 youslist로 정규 갤러리에 한해 그 스크립트를 막아내셨더라구요.

그런데 마이너 갤러리에 한해서는 아직 안티 애드블락이 떠요.

http://gall.dcinside.com/mgallery/board/lists/?id=aoegame 

제가 주로 가는 갤러리인데 여기서는 메인화면에 개죽이 안티 애드블락이 뜹니다.

괜찮으시다면 저기도 막아 주실 수 있을까요.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다.

마이너 갤러리의 경우에는 요소의 class가 다르게 적용된 부분이 있어서 00d8677665098cf27600ee62ed0173be4137379b 커밋에서 수정되었습니다.
