### ISSUE TITLE
디시 애드블록팝업 다른필터들과 충돌관련

### ISSUE THREAD

**Issue by AndMeda** [yous/YousList#36]
현재시각 크롬+유블럭오리진 기준 디시 애드블록 팝업은 YousList가 유일하게 막아냅니다만.

EasyList
EasyList without element hiding rules
Korean Adblock List
List-KR
Fanboy's Korean
Fanboy+Easylist-Merged Ultimate List

이 필터중 하나라도 같이 켜져있으면 막아내지 못합니다. 
EasyList만이라도 같이 사용할 방법이 있을까요?

**Comment by fenslett** [comment]
소스를 확인해보니 dcinside는 [`blockadblock.js`](http://gall.dcinside.com/_js/blockadblock.js)파일과 내부 스크립트를 병행하여 사용하고 있습니다. `blockadblock.js`는 서드 파티이기 때문에 통상적인 광고 차단 플러그인으로 차단할 수 있지만, 문제는 내부 스크립트로 차단 여부를 2차적으로 감지하기 때문에 타 필터와 병행 시 감지가 되는 듯 합니다. 그런데 대다수의 플러그인이 내부 스크립트를 차단할 수 있는 기능을 지원하지 않더군요.

ublock같은 경우엔 `dcinside.com##script:contains(adBlockDetected)`를 이용하여, 해당 스크립트를 차단할 수 있지만, ABP는 그런 기능을 지원하질 않더군요. 심지어 ublock 개발자의 말에 따르면, 이 문법은 ABP에 문제를 초래할 수 있다고 합니다.

>   It appears inline script tag cosmetic filters can be used in filter lists which are also meant to be used for Adblock Plus ("ABP") -- ABP will ignore the `[...]##script:contains([...])` filters. This makes it possible for maintainers of filter lists to make use of this new filter syntax for the benefit of uBlock Origin users while not causing problem for users of ABP. The compatibility was verified for the Firefox version of ABP however, I did not check for the Chromium version of ABP. This will need confirmation for whether using the new filter on a Chromium version of ABP has no negative consequences.
> Update: Compatibility was verified with the Chromium version of ABP, and unfortunately this new filter syntax breaks ABP, as it fails to discard invalid CSS selectors.
[참고](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#compatibility-with-adblock-plus) 

이러한 이유 때문에, 
```
http://nstatic.dcinside.com/dgn/gallery/images/popup/addblockimg.jpg
http://nstatic.dcinside.com/dgn/gallery/images/popup/addblockimg2.jpg
http://nstatic.dcinside.com/dgn/gallery/images/popup/addblocktxt.jpg
http://nstatic.dcinside.com/dgn/gallery/images/popup/addblocktxt2.jpg
```
혹은
``` 
http://nstatic.dcinside.com/dgn/gallery/images/popup/addblock*.jpg
```

이 2가지 방식을 이용하여 이미지 자체를 감추는 방법 밖에 없을 듯 합니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다.

[BlockAdBlock](https://github.com/sitexw/BlockAdBlock)(또는 FuckAdBlock)에서 기본적으로 탑재하고 있는 광고 차단 플러그인 감지 방법을 설명드리자면,

``` html
<div class="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links"
    style="width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;">
</div>
```

위와 같은 미끼 요소를 만들어서 해당 `<div>`가 숨겨지는지를 확인합니다. 그런데 EasyList 등의 필터에는 일반적인 class를 숨기도록 되어 있기 때문에 많이 감지되는 것 같아요. 그래서 c895ae3da9d1f1bc8c041975e9e54adcb41056b5 커밋에서 해당 class는 일단 숨기지 않도록 필터에 추가했습니다.

- EasyList
- EasyList without element hiding rules
- Fanboy+Easylist-Merged Ultimate List
- KOR: Fanboy's Korean
- KOR: Korean Adblock List

필터를 같이 켰을 때 디시인사이드에서 감지되지 않는 것 확인했습니다. 다만 List-KR의 경우엔 디시인사이드에서 검사하고 있는 요소를 직접 가리기 때문인지 동작하진 않습니다.

**Comment by yous** [comment]
다시 확인한 결과 게시판 목록에서는 EasyList, Fanboy+Easylist-Merged Ultimate List, KOR: Fanboy's Korean 필터와 같이 사용해도 무관하지만 갤러리 글을 조회하면 다시 팝업이 뜨는 것을 확인했습니다. 이 경우엔 `#dc_advertisement`를 가리고 있어서 그런데요, 내 필터에 다음 줄을 추가하시면 같이 사용하실 수 있습니다.

```
#@##dc_advertisement
```

**Comment by yous** [comment]
사파리에서는 제대로 동작하는데 크롬에선 되지 않는 것을 확인했습니다. 예외가 적용되는 시점 문제 때문인지 팝업이 뜨네요. 지금으로서는 별다른 해결 방법을 찾지 못했습니다.

**Comment by AndMeda** [comment]
크롬 유블럭 오리진 내 필터에 `gall.dcinside.com##DIV[style*="position: fixed;"]`를 추가해서
따로 해결하긴 했습니다. 이경우 특별히 문제가 되는점은 없나요?

**Comment by yous** [comment]
지금으로서는 추가로 가리는 요소 없이 정상적으로 작동하는 것 같습니다.
