### ISSUE TITLE
m.richgo.ai/pc

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#362]
광고제거 부탁드립니다 감사합니다

윈10 엣지브라우저 애드가드프로
youslist

https://m.richgo.ai/pc

![image](https://github.com/yous/YousList/assets/15683789/fcbcca55-6fab-4d31-a00b-6365a3d6181c)

![image](https://github.com/yous/YousList/assets/15683789/5b40301f-2096-4361-9743-68b3097c51f7)

**Comment by yous** [comment]
지금 안 보이는 것 같아서요, 확인 부탁드립니다.

**Comment by swbaek81** [comment]
네 지금은 안보입니다 나중에 발견하면 다시 제보할게요

**Comment by swbaek81** [comment]
지금 광고가 보입니다. 감사합니다.

![image](https://github.com/yous/YousList/assets/15683789/ca7cd342-6d74-4da5-98eb-84af39b6d17e)

![image](https://github.com/yous/YousList/assets/15683789/164947cc-03ec-4b88-bb10-101e5b1e0891)
