### ISSUE TITLE
podbbang.com

### ISSUE THREAD

**Issue by linkinnam** [yous/YousList#37]
youslist.txt에

www.podbbang.com###dawin

추가 부탁드릴 수 있을까요?

http://www.podbbang.com/ch/13646
위와같은 주소들에서 광고 video엘리먼트에 가려 플레이어 내부 버튼 동작이 안되는 문제를 해결하려고 합니다.

**Comment by yous** [comment]
안녕하세요, 제보해주셔서 감사합니다. a22537d0a84cd7bda074142fc1ff30b5bd64e0f5 커밋에서 `#dawin_area`를 가리는 것으로 해결되었습니다. 사이트에서 보이는 광고도 조금 추가했습니다.

**Comment by linkinnam** [comment]
감사합니다 :)
잘 쓰겠습니다!
