### ISSUE TITLE
clien.net 광고

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#38]
[클리앙](https://www.clien.net/service/) 사이트가 개편되었는데, 광고 변경점 확인 부탁드립니다.

**Comment by fenslett** [comment]
메인 화면에 있는 광고 3개는 아래 필터로 차단하면 될 거 같습니다.
```
www.clien.net###div-pc-side
www.clien.net###div-main-top
www.clien.net###div-main-center
```

![1](https://cloud.githubusercontent.com/assets/14074081/25777611/5039e8b8-331d-11e7-9666-3c6896ed9892.PNG)
![2](https://cloud.githubusercontent.com/assets/14074081/25777612/5296f880-331d-11e7-9ef0-6c0454ff332b.PNG)

**Comment by yous** [comment]
@nagato7 님, @fenslett 님, 감사합니다. 4abd8c2b58bf21f74b3f92d847747b4123d19765 커밋에서 수정되었습니다.

**Comment by nagato7** [comment]
내부적으로 변화가 있었는지 플레이스홀더 "광고영역입니다"가 다시 나오네요.

**Comment by yous** [comment]
제보 감사합니다. 83041ac8b4e85a4e36bb29b50f96498975f43328 커밋에서 수정되었습니다.
