### ISSUE TITLE
티카페 주소변경 및 차단되지 않는 광고 제보

### ISSUE THREAD

**Issue by AndMeda** [yous/YousList#39]
https://twitter.com/tcafenet
2tcafe.com으로 변경되었습니다 추가부탁드립니다.

http://2tcafe.com/lotto/
로또에서 중간 광고배너가 기존 필터로는 사라지지 않습니다.

감사합니다 :)

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 2tcafe.com 확인하고 추가했는데 로또 페이지에서 배너를 찾을 수 없어 새로운 필터를 추가하지는 않았습니다. 광고가 계속 보인다면 알려주세요.
