### ISSUE TITLE
다음 메인페이지

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#4]
uBlock에서 필터를 사용할 때 다음 메인 광고와 뼈대 모두를 없애는 것으로 보이는데, 로그인이 왼쪽으로 쏠립니다.

![daum.net](https://cloud.githubusercontent.com/assets/12077847/10069989/a396858e-62ea-11e5-80e8-96ca1eb11dae.PNG)

이 경우에는 광고는 없애더라도 뼈대는 남기는 편이 좋지 않을까 싶어서 건의드립니다.

**Comment by yous** [comment]
제보해 주셔서 감사합니다. 업데이트 하시고 한 번 확인해 주세요.

**Comment by nagato7** [comment]
수정 확인했습니다. 반영 감사합니다.
