### ISSUE TITLE
SBS홈페이지 뉴스 영상 동영상이 재생 안되네요.

### ISSUE THREAD

**Issue by gosotopo** [yous/YousList#40]
안녕하세요.
전 SBS홈페이지 통해서 영상들을 종종 보는편인데요,
지난주부턴가 갑자기 영상들이 안나오기 시작했습니다. 로딩만 뱅글뱅글돌고

처음엔 플래시 문제인가 했다가, 오늘 아침에 혹시나 하고 애드블락 끄고 다시 재생하니 되더군요.
애드블락이 영상 직전에 나오는 광고영상 차단해주다가 뭐가 막힌듯 한데

이거 어지 해결 안될련지요?

영상 url 하나 남길께용
http://news.sbs.co.kr/news/endPage.do?news_id=N1004221924&plink=VERTICAL&cooper=VIDEOMUGLIST

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 해당 URL과 다른 뉴스 영상을 여러 번 재생해 보았는데, 사파리나 크롬에서는 그런 현상이 발생하지 않았습니다. 혹시 최근에도 비슷한 현상을 겪고 계신가요? 만약 그렇다면 사용하고 계신 다른 광고 필터 목록도 알려주시면 감사하겠습니다!

**Comment by gosotopo** [comment]
답변 감사합니다 ㅎㅎ

전 크롬 최신버전 쓰면서 이런 증상이 나타나서 여쭌건디
yous님께선 크롬에서도 그런 현상이 발생하지 않는다고 하셔서 놀란(?)맘에 옵션가서
기존에 기본적으로 구독되어있는 목록들 중에서
(Acceptable Ads, AdBlock custom filters, EasyList, 한국어.... 여기에다 저는 Youslist만 추가로 구독중)

EasyList의 구독을 푸니 문제가 해결되었어요 ㅎㅎㅎ
감사합니다~~

**Comment by yous** [comment]
확인 감사합니다! 다른 기기의 크롬으로 한 번 더 보니 플래시로 재생될 때 광고가 나오는 것 같네요. 크롬 업데이트를 하고 나니 여러 번 재현할 수가 없어서 필터를 추가하지는 못했습니다. 일단 이 이슈는 닫겠습니다. 또 광고가 보이거나 하면 언제든지 제보해주세요.
