### ISSUE TITLE
dns://m.cafe.naver.com

### ISSUE THREAD

**Issue by bobblun** [yous/YousList#409]
yous dns 필터에 

dns://m.cafe.naver.com

가 추가되어있어서 네이버 카페 앱 글 본문이 보이지 않습니다

확인 후 처리 부탁드립니다

**Comment by bobblun** [comment]
![Uploading Screenshot_20231227_003147_AdGuard.jpg…]()

**Comment by bobblun** [comment]
![Screenshot_20231227_003309_Naver Cafe](https://github.com/yous/YousList/assets/49634687/e060a343-4e23-4b41-9906-4aa656cc5c30)

**Comment by bobblun** [comment]
![Screenshot_20231227_003147_AdGuard](https://github.com/yous/YousList/assets/49634687/75bf8174-1821-47dd-abfb-bc1ff67d3d2e)
![Screenshot_20231227_003309_Naver Cafe](https://github.com/yous/YousList/assets/49634687/103c8d4a-a2a2-4997-99a9-5d9d565af9b2)

**Comment by yous** [comment]
DNS 필터를 등록할 땐 다음 주소를 사용해야 합니다.

```
https://raw.githubusercontent.com/yous/YousList/master/hosts.txt
```

다음 주소는 일반 필터로, DNS 필터로 사용하면 일반 사이트도 차단되어 문제가 될 수 있습니다.

```
https://github.com/yous/YousList/raw/master/youslist.txt
```
