### ISSUE TITLE
구글에서 크롬/구글시작페이지 제안 광고

### ISSUE THREAD

**Issue by Cokaksd** [yous/YousList#41]
안녕하세요. 한국 필터를 따로 관리해주시는 덕분에 쾌적한 웹 환경을 즐기고 있어서 감사합니다.

 제가 크롬을 설치 안하고 엣지 브라우저에서만 웹활동을 하는데 쿠키를 제거 할 때마다 구글에서 구글 시작페이지, 혹은 크롬을 제안하는 알림이 구글 메인페이지, 구글드라이브, 구글번역 등등 곳곳에서 발생을 합니다.
 필터 작성 정책이 있다면 이것도 범주에 포함이 되는지 궁금합니다.
 아니라면 구글에서 구글시작페이지/구글크롬 제안 알림도 없애 주신다면 더 좋을 것 같습니다.

감사합니다.

**Comment by yous** [comment]
안녕하세요, 제안해주셔서 감사합니다.

저는 평소에 사파리를 쓰고 있는데, 생각보다 해당 알림을 본 기억이 없어 다른 브라우저로 시도해 보니 IE 10, IE 11, Edge에서 크롬을 사용하겠냐는 팝업이 발생하고, Firefox에선 시작 페이지 팝업이 발생하네요.
다만 이 필터에서 제거하고자 하는 광고는 주로 타사 광고, 볼 필요가 없는 광고라서 자사 제품이거나 관련성이 상당히 높은 광고인 경우에는 되도록 남겨두도록 하는 편입니다. 광고가 아닌 건 가리면 안 된다고 생각해서 논란의 여지가 있는 경우엔 가리지 않는다고 생각하시면 될 것 같습니다.

일단 이슈는 닫습니다만 추가로 의견이 있으면 주시고, 새 이슈를 만드셔도 좋습니다. 다른 광고 제보도 언제든지 받습니다.
감사합니다.
