### ISSUE TITLE
ttocorps.com 광고 차단

### ISSUE THREAD

**Issue by irule2day** [yous/YousList#42]
안녕하세요.
ttocorps.com에서 뜨는 광고 리스트에 추가해주시면 감사하겠습니다.

제가 지금 사용하는 필터입니다.

! 8/14/2017, 4:25:14 PM https://ttocorps.com/
ttocorps.com###top > tbody > tr:nth-of-type(1) > td > table > tbody > tr > td > div:nth-of-type(2)

! 8/14/2017, 4:25:32 PM https://ttocorps.com/
ttocorps.com###right_banner

! 8/14/2017, 4:26:12 PM https://ttocorps.com/
ttocorps.com###leftw_banner

! 8/14/2017, 4:26:38 PM https://ttocorps.com/
ttocorps.com###left_l

! 8/14/2017, 4:27:13 PM https://ttocorps.com/
||ttocorps.com/img/banner/mton.gif$image

! 8/14/2017, 4:27:24 PM https://ttocorps.com/
||ttocorps.com/img/qbt.png$image

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. v20170814 버전에서 해결되었습니다. 확인해보시고 광고는 언제든지 제보해주세요.

**Comment by irule2day** [comment]
감사합니다!
