### ISSUE TITLE
네이버 카페 앱 배너 광고

### ISSUE THREAD

**Issue by bobblun** [yous/YousList#423]
![51](https://github.com/yous/YousList/assets/49634687/f1f2e766-0e21-4a4b-a58e-04cc45f27fc4)

모바일 웹사이트나 데스크탑 웹사이트는 이미지 주소를 추출해서 필터를 만들면 위의 카페 자체에서 넣는 배너 광고도 차단이 잘 되더군요

||cafeptthumb-phinf.pstatic.net/*_banner
(카페 자체에서 넣는 배너 광고는 _banner가 들어가는 점을 이용한 필터)

하지만 네이버 카페 앱은 위의 필터를 사용해도 광고가 그대로 나오더군요
네이버 카페 앱은 https 필터링 적용도 안되는 것 같고.. 카페 내 자체 배너 광고는 차단할 방법이 없을까요?

**Comment by bobblun** [comment]
![Screenshot_20240107_210117_Naver Cafe](https://github.com/yous/YousList/assets/49634687/1fba38ca-f4d3-4bed-9d8e-e6b9cb3ad561)
https://cafe.naver.com/anycallusershow/4626701

위 주소 글을 예시로 만들어본건데 카페 앱으로는 차단이 안되네요

**Comment by yous** [comment]
일반 앱의 경우에는 요소 가리기가 되지 않아 URL로만 차단할 수밖에 없는데요, HTTPS 필터링도 어려우면 현재로서는 차단이 힘들다고 봐야 할 것 같습니다. DNS로 도메인 전체를 차단하게 되면 일반 이미지도 안 보이게 될 거 같고요.

**Comment by bobblun** [comment]
> 일반 앱의 경우에는 요소 가리기가 되지 않아 URL로만 차단할 수밖에 없는데요, HTTPS 필터링도 어려우면 현재로서는 차단이 힘들다고 봐야 할 것 같습니다. DNS로 도메인 전체를 차단하게 되면 일반 이미지도 안 보이게 될 거 같고요.

아 그렇군요 답변 감사합니다
