### ISSUE TITLE
https://tczoa.info/ 광고차단 추가해주세요

### ISSUE THREAD

**Issue by doct0rfish** [yous/YousList#43]
! 2017. 10. 7. 오후 10:02:32 https://tczoa.info/
||tczoa.info/files/_etc/etc/vrbora_twzoa.gif$image

! 2017. 10. 7. 오후 10:02:34 https://tczoa.info/
||tczoa.info/files/_etc/etc/200-200-B.gif$image

! 2017. 10. 7. 오후 10:02:37 https://tczoa.info/
||tczoa.info/files/_etc/etc/th9391.gif$image

! 2017. 10. 7. 오후 10:02:39 https://tczoa.info/
||tczoa.info/files/_etc/etc/bo_twz.jpg$image

! 2017. 10. 7. 오후 10:02:55 https://tczoa.info/?m=bbs&bid=movie&uid=569161
||tczoa.info/files/_etc/etc/webbott.gif$image

! 2017. 10. 7. 오후 10:03:08 https://tczoa.info/?m=bbs&bid=drama
||tczoa.info/files/_etc/etc/yazoa.gif$image

필터에 추가는 했으나 광고가 사라지지가 않습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 방금 필터를 업데이트했으니 한번 확인 부탁드립니다.
광고가 남아 있거나, 광고가 보이는 다른 사이트가 있다면 언제든지 제보해주세요.

**Comment by doct0rfish** [comment]
넵 광고 사라졌습니다
