### ISSUE TITLE
Block open.oneplus.net

### ISSUE THREAD

**Issue by holdit** [yous/YousList#45]
"open.oneplus.net" is used by Oneplus (Chinese phone OEM) to collect data on their users.

Perhaps it should be added to this list? It would be useful for AdAway users.

More info about this: https://www.chrisdcmoore.co.uk/post/oneplus-analytics/

Thanks

**Comment by yous** [comment]
@holdit, thanks for letting me know. I've just updated to block `open.oneplus.net/cloud/pushdata`.
