### ISSUE TITLE
m.news.zum.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#454]
혹시 하단 Bar 제거 가능할까요? 
사용자 규칙으로라도 제거하고 싶어서요 감사합니다

아이폰 사파리 애드가드프로
유즈리스트 마이크로쉴드 나무링크

https://m.news.zum.com/articles/88793676?cm=front_news_text_1&r=4

![image](https://github.com/yous/YousList/assets/15683789/f0970607-a343-4bab-8e0a-1fa851e3cd77)

**Comment by yous** [comment]
다음 사용자 규칙으로 가릴 수 있습니다.

```
m.news.zum.com##div#banner_app_view
```
