### ISSUE TITLE
[Info] Referencement

### ISSUE THREAD

**Issue by funilrys** [yous/YousList#46]
Hello @yous ,

I know you were already informed but as the structure changed I still share the following for archiving.

Because I want to be transparent, I just wanted to inform you that we added your hosts file to [Ultimate.Hosts.Blacklist](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist) through [Ultimate-Hosts-Blacklist/YousList](https://github.com/Ultimate-Hosts-Blacklist/YousList).

Cheers,
Nissar

P.S: Feel free to close/comment after reading this information.

**Comment by yous** [comment]
Hi @funilrys! Thank you for keeping tracking. But one thing, it's noted as for smartadserver and mirrors, but I think that was came from https://github.com/yous/YousList/issues/44. The goal of this list is to block general advertisements (that also includes smartadserver). Since I mainly use internet in Korea, so it can be biased.

**Comment by funilrys** [comment]
Hello @yous and thanks for the feedback :+1: 

Actually, the repository name is a misunderstanding as we took the name from our older system.

But I checked our `info.json` and it says that we pull, test and clean `https:/raw.githubusercontent.com/yous/YousList/master/hosts.txt` before passing it to the central repository so I renamed the repository.

Cheers,
Nissar

**Comment by yous** [comment]
Thank you for the quick response! I'll be appreciated it if [README_template.md](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/templates/README_template.md#credits--thanks) on Ultimate.Hosts.Blacklist also gets modified. I'm closing this now.

**Comment by funilrys** [comment]
@yous Also done.

Have a nice day/night.
