### ISSUE TITLE
애드가드(adguard)에서 필터추가 어떻게 하나요?

### ISSUE THREAD

**Issue by nskzhd** [yous/YousList#47]
안드로이드 버전에서 필터리스트에 youslist가 안보이는데..자동 업데이트될 수 있도록 추가 하려면 어떻게 해야할까요?

**Comment by yous** [comment]
제보 감사합니다. iOS 버전에선 추가된 걸 확인했는데 안드로이드 버전은 따로 관리되는 모양이네요. 당장은 자동 업데이트가 어려울 것 같습니다.

**Comment by nskzhd** [comment]
@yous 아..그렇군요. 애드가드에 문의해봐야겠군요. 
사실 List-kr필터를 구독중이었는데.. 한달 이상 업데이트가 안되고 있더라구요. 관리자분 깃헙에도 더이상 답변도 안달리고.. 그래서 알아보다가 youslist를 알게되어 글을 남기게됐네요.

답변 감사합니다.

**Comment by yous** [comment]
@nskzhd 다음 안드로이드 앱 업데이트에 추가된다는 것 같네요. https://github.com/AdguardTeam/FiltersRegistry/issues/10#comment-376807346

**Comment by nskzhd** [comment]
@yous 감사합니다. 얼른 업데이트 되었으면 하네요ㅎㅎ
