### ISSUE TITLE
m.starnewskorea.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#487]
하늘색 사각형
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드
유즈리스트
유즈리스트dns

https://m.starnewskorea.com/view.html?no=2024041915150336948&MTI

![image](https://github.com/yous/YousList/assets/15683789/4adc8f03-ed43-4361-b5f9-1a0b5ba5bf6c)

**Comment by yous** [comment]
f6a7c50 커밋에서 같이 해결된 것으로 보입니다.
