### ISSUE TITLE
m.news.zum.com

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#493]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드
유즈리스트

https://m.news.zum.com/articles/90433069?cm=front_tventer_tv_1&r=1

![image](https://github.com/yous/YousList/assets/15683789/88166ccc-2f74-4b27-970d-17cfcefa09b3)

**Comment by yous** [comment]
dab96e1 커밋에서 같이 업데이트됐습니다.
