### ISSUE TITLE
lawtimes.co.kr

### ISSUE THREAD

**Issue by swbaek81** [yous/YousList#511]
광고차단 부탁드립니다 감사합니다

유즈리스트
마이크로쉴드
나무링크

Apple Safari
Apple iOS
AdGuard for iOS/iOS Pro

https://www.lawtimes.co.kr/

![image](https://github.com/yous/YousList/assets/15683789/a0c216b6-6d9d-49cb-b52d-f11070c4cc8b)

**Comment by yous** [comment]
css가 자동 생성되어서 공백까지 가리긴 어렵네요. 이미지만 일단 가렸습니다.
