### ISSUE TITLE
문서를 가리는 팝업형 내부링크 유도도 광고 범주에 포함되나요?

### ISSUE THREAD

**Issue by ndaesik** [yous/YousList#53]
http://www.itworld.co.kr 와 http://www.ciokorea.com 에서 아무 문서나 읽다보면 스크롤 중반부에 화면을 가리는 '오늘의 추천 콘텐츠' 라는 팝업형 링크 유도 메세지가 뜨며, 링크는 두개 다 itworld.com로 유도를 합니다.

ciokorea.com 도메인에서 이 팝업이 뜨는 것은 외부 링크로 이동을 유도하는 것이니 광고에 범주에 해당될 수 있다고 생각됩니다만, itworld.com에서 뜨는 팝업형 내부 링크 유도도 광고의 범주에 포함이 되나요?

광고의 범주에 포함이 된다면 div[id="techlibrary_left_slide_banner"] 를 차단 부탁드리고 싶습니다.
감사합니다.

**Comment by ndaesik** [comment]
+ 네이버 카페를 이용하다보면 게시물을 읽을 때 '확장 프로그램에 요청에 의해 페이지가 차단되었다'는 메세지가 뜨는데, 검색을 해보니 @@cc.naver.com 필터를 개인적으로 입력해주면 해결된다고 검색에 뜨네요.
위 허용 필터도 넣어주실 수 있을까요?

**Comment by yous** [comment]
사실 itworld.co.kr의 해당 배너의 경우 방해된다는 느낌을 항상 받았는데요, 내부 링크인데다가 내용 자체도 전혀 관련 없는 광고라고 판단하기 애매하여 두고 있었습니다. 그런데 지금 보니 `id="techlibrary_left_slide_banner"`로 배너의 형태를 띠고 있고 내용 자체도 이메일 구독을 요구하는 것이 전부인 듯하여 이번에 차단하도록 하겠습니다.

네이버 카페의 경우 필터에 `cc.naver.com`이 직접 포함된 경우는 없는데 혹시 다른 필터와 같이 사용하고 계신가요? YousList만 사용하고 있을 때에도 해당 메시지가 뜨는 주소를 하나만 알려주시면 확인하겠습니다.

**Comment by yous** [comment]
itworld.co.kr, ciokorea.com 업데이트 했습니다. https://github.com/yous/YousList/commit/e602fc58169fe146e5d8b7f3f8d42a6d734189aa, https://github.com/yous/YousList/commit/a75bddf9da65ca676b5e3e8bf010c9423e99e127

**Comment by ndaesik** [comment]
문제 해결해 주셔서 감사합니다.
cc.naver.com의 문제는 ublock 기본 필터의 문제인 것 같습니다.
ublock 필터 깃허브에 문의 넣으니 @@||cc.naver.com/cc$subdocument,first-party 추가해주신다고 합니다. :)
제가 잘 몰라서 그러는데, 필터는 중첩해서 쓸 필요없이 YoursList 하나만 켜면 되나요 ?
여태 Global 필터 + 국가별 서브 필터 로 사용하는거라고 생각하고 두개 다 열심히 키고 사용해서 네이버 카페가 먹통이 걸린 것 같네요.
혹시 모르니 다른 필터는 끄고 YoursList만 켜고 한번 테스트해 보겠습니다.

**Comment by ndaesik** [comment]
다른 필터 다 끄고 YoursList필터만 켜니 네이버 카페 표시 잘 되네요!
해외 사이트 딱히 브라우징 할 일 없으면 가볍게 YoursList만 써도 되나보군요. 
항상 잘 쓰고 있습니다. 감사합니다 :)

**Comment by yous** [comment]
확인 감사합니다. 다른 필터를 많이 켤수록 문제가 많이 발생하게 되더군요. 그래서 기본적으로 YousList 하나만 써도 되도록 만들고 있는데, 아무래도 주로 한국 웹사이트 위주로 업데이트가 자주 이루어지다보니 해외 사이트는 업데이트가 느릴 수도 있습니다.
