### ISSUE TITLE
영어필터에 의해 지마켓 결제페이지 로딩문제

### ISSUE THREAD

**Issue by DandyClubs** [yous/YousList#54]
adguard 영어 필터에서

 영어 필터: /getad?

필터링 되다보니. 결제 페이지 불러오는데 문제가 발생합니다.

@@/getAd?$domain=gmarket.co.kr

이렇게 허용필터 해주니 정상적으로 결제페이지가 로딩되더군요.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다.

찾아보니 AdGuard 영어 필터에서는 확인 못 했는데 EasyList에는 `/getad?` 항목이 있네요. AdGuard 필터 때문에 문제가 생기는 게 맞다면 여기에 제보해보세요. https://github.com/AdguardTeam/AdguardFilters/issues

지마켓 결제 페이지에서 로드하는 URL은 이런 형태인 것 같습니다.

```
http://dadispapi.gmarket.co.kr/target/gmkt/getAd?reqNo=…&adtIdType=…&adtId=…&adOptOut=…&callback=…&_=…
```

YousList에서는 해당 URL을 막고 있지 않습니다. 해당 영어 필터와 함께 계속 사용하고 싶으시면 말씀해주신대로
```
@@/getAd?$domain=gmarket.co.kr
```
또는 해당 URL
```
@@||dadispapi.gmarket.co.kr/target/gmkr/getAd?$domain=gmarket.co.kr
```
등의 예외 필터를 추가하셔서 사용하시면 될 것 같고, `/getad?`나 비슷한 필터로 더 많은 문제가 발생하면 예외 필터를 YousList에 따로 추가하는 것도 고려하겠습니다. 일단 이 이슈는 닫겠습니다. 다른 문제가 발생하거나 광고가 보이시면 언제든 제보해주세요.
