### ISSUE TITLE
Gmail. .aKB 가 광고인 것 같아요.

### ISSUE THREAD

**Issue by ndaesik** [yous/YousList#55]
기본텝 말고, 소셜이랑 프로모션 텝에보면 

발신인 이름 [광고]🛈 **광고제목** - 부제목 
발신인 이름 [광고]🛈 **광고제목** - 부제목

이렇게 두 광고가 div[class="aKB"]안에 묶여있는데, 확인 부탁드립니다.
최근에 업데이트 된 사항인지 ublock기본필터에서도 차단은 안해놨네요.
항상 필터 관리 업데이트 감사드립니다.

**Comment by yous** [comment]
제보 감사합니다. Gmail에선 해당 탭을 안 켜놓고 있어서 미처 몰랐네요. <https://github.com/yous/YousList/commit/8b6a178bc2d5aed1c6f0b1c47bd0a677538e333a>에서 업데이트 했습니다.
