### ISSUE TITLE
네이버 스포츠 동영상 광고

### ISSUE THREAD

**Issue by 7793690** [yous/YousList#56]
안녕하세요. 아이폰에서 AdGuard 를 사용하면서 Yous님 필터를 잘 사용하고 있습니다.

언제 부턴가 업데이트를 하고나서 부터 네이버 스포츠 광고가 검은 화면에 로깅이미지가 나오면서 스킵이 안되고 10-5초 정도 검은 화면이 나오고나서 영상이 나오는 문제가 있더군요.

어떤 부분이 업데이트 된건지를 정확히 모르겠더군요.

다른 필터들을 체크해제후에 YousList만 체크해서 봐도 마찬가지더군요.

제가 사용자 필터에 쓰던 주소가 있는데 혹시 적용이 가능한지 테스트 해봐주십사 글 적어 봅니다.

vod-naver.pstatic.net  이 주소를 막아주면 광고는 안나오고 바로 본 영상으로 넘어갑니다.

미리 감사드립니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 기존에 `||apis.naver.com/rmcnmv/rmcams/item/create/` 필터를 사용하고 있어서 데스크톱에서는 문제가 없었는데, 아이폰 환경에서는 말씀하신 현상이 나타나네요. 해당 필터 대신 광고 영상 URL을 여러 개 찾아 추가하니 해당 현상이 해결되었습니다.

**Comment by yous** [comment]
네이버 TV에서 여러 영상에서 사용되는 URL을 추가하긴 했습니다만, 전부 추가되진 않았을 것 같습니다. 사용하시다가 광고가 보이시면 언제든지 제보해주세요. 감사합니다.
