### ISSUE TITLE
카카오TV  동영상 광고

### ISSUE THREAD

**Issue by Reni1** [yous/YousList#57]
안녕하세요 ADGuard를 사용중이며 Youslist를  사용중에 있습니다. 늘 필터 업데이트에 감사 드립니다.
 
https://tv.kakao.com/channel/3149566/cliplink/390585054

필터 로그를 보니 필터가 정상작동하나 카카오티비에서 애드블록에 대응하여서 동영상이 재생되지 않고 광고차단프로그램을 끄라는 메세지가 나타나는것 같습니다.

한번 확인 부탁드립니다. 감사합니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다.
AdGuard를 설치해서 테스트해보니 영어 필터를 켜면 해당 메시지가 나오는 것 같습니다. 살펴보니 BlockAdBlock 같은 코드가 있어 EasyList 기반의 영어 필터가 감지되는 것 같습니다. 영어 필터를 꺼도 메시지가 나오는지 테스트 한번 부탁드립니다.

**Comment by Reni1** [comment]
확인했습니다. 영어 필터를 끄니 정상적으로 작동합니다.  
빠른 확인 감사드립니다.

**Comment by yous** [comment]
확인 감사합니다. 다른 문제가 생기거나 광고가 보이면 언제든지 제보해주세요.
