### ISSUE TITLE
카카오tv 재생이 되질않습니다.

### ISSUE THREAD

**Issue by SHxXxJ** [yous/YousList#58]
https://tv.kakao.com/channel/2654188/cliplink/390615065

윈도우10 크롬 69 애드가드 사용중입니다.

그리고 혹시 안드로이드앱이나 iOS용도 광고제보하면 차단해주시는지 궁금하네요.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 혹시 AdGuard에서 어떤 필터를 사용하고 계신지 알려주실 수 있을까요?
영어 필터, 모바일 광고 필터, EasyList, YousList를 켠 상태에서 필터 업데이트 후 여러 번 테스트해봤는데 계속 재생되고 있어서 재현이 안 됩니다.

안드로이드나 iOS 브라우저에서 광고가 보이는 경우에 제보해주시면 업데이트하고 있습니다.

**Comment by SHxXxJ** [comment]
잉 이상하게 지금은 잘되네용...
모바일기기중에 안되는거 제보드립니다...
안드로이드 앱중엔 뽐뿌알리미2에서 광고가 계속뜨구요~~~(오레오, 애드가드2.11버전사용중)
ios에선 사파리로 네이버tv 들어가면 재생이 되질않고 영상에는 검은색만 뜨네요...애드가드 비활성화시키면 잘되고 그럽니다.(ios에선 사파리필터랑 youslist만 씁니다.)

**Comment by SHxXxJ** [comment]
안드로이드앱은 vpn을 통해 앱광고도 차단됩니다...
ios는 조금더 알아보고 자세히 알려드리겠습니다.

**Comment by yous** [comment]
앗, 네. iOS에서는 VPN으로 광고 차단이 안 되는 것 같은데(애플에서 거절하는 것 같습니다. https://www.macrumors.com/2017/07/14/apple-ad-blocking-app-crackdown/), 혹시 안드로이드에서 뽐뿌알리미2 앱에 들어갔을 때 요청하는 URL 등을 보실 수 있다면 알려주시기 바랍니다. 업데이트 할 수 있도록 하겠습니다.

**Comment by SHxXxJ** [comment]
iOS도 AdGuard Pro앱은 vpn기능이 있어용...

**Comment by yous** [comment]
아, 알려주셔서 감사합니다. iOS의 AdGuard Pro는 VPN 통해 DNS를 바꿔서 다른 앱에서도 차단하는 방식이군요. 이 경우엔 호스트 전체 차단만 가능할 것 같고, 미리 설정된 DNS 중에 골라서 사용하는 거라 원하는 필터를 적용하기는 힘들 것 같습니다. 안드로이드에서는 어떤 방식으로 동작하나요?

**Comment by yous** [comment]
https://github.com/yous/YousList/commit/af1d4bf29a0bd3014400617cbfac17b6ee16b9d6 커밋에서 뽐뿌 알리미2 앱 광고 업데이트 했습니다. 카카오TV는 일단 문제가 없는 것 같으니 이슈는 닫겠습니다. 광고가 보이면 또 제보해주시기 바랍니다. 감사합니다.
