### ISSUE TITLE
slashdot.org

### ISSUE THREAD

**Issue by ReddestDream** [yous/YousList#581]
I know this isn't a Korean site, but since you seem to have expertise in iOS Content Blockers, I wanted to let you know about recent changes to slashdot.org that are breaking many blockers like AdGuard and 1Blocker (the one I use). Other blockers like Magic Lasso and Wipr 2 are also broken. Some of them just break with an ad blocker detection warning, but 1Blocker just lets ads through:

![Slashdot](https://github.com/user-attachments/assets/4bbad263-84ef-416f-9ee7-4d8ad83ab062)

Thank you for any support you may be able to provide. I've tried a few ways to block these ads with custom rules based on what uBlock is doing, but nothing has worked. :/

**Comment by piquark6046** [comment]
Just use [tinyShield](https://github.com/List-KR/tinyShield)

**Comment by piquark6046** [comment]
@ReddestDream Just use [tinyShield](https://github.com/List-KR/tinyShield) with AdGuard for iOS
