### ISSUE TITLE
clien.net 광고

### ISSUE THREAD

**Issue by nagato7** [yous/YousList#6]
네이버 광고 css 삭제 선택이 안 되는 경우가 있습니다.
e.g. http://clien.net/cs2/bbs/board.php?bo_table=lecture&wr_id=291381
그냥 평이하게
clien.net##div[style="clear:both;width:780px; height:115px; padding:0px; text-align:center;padding-left:5px;"]
로 하면 관계 없이 필터링이 되는 것으로 보입니다.

**Comment by yous** [comment]
제보해 주셔서 감사합니다. `div.board_main` 아래의 `div[style="clear:both;width:780px; height:115px; padding:0px; text-align:center;padding-left:5px;"]`를 모두 막는 방식으로 변경했습니다. 한번 확인해 주시면 감사하겠습니다.

**Comment by nagato7** [comment]
새 규칙에서는 상황에 관계 없이 모두 제거가 되는 것으로 보입니다. 빠른 조치 감사합니다.
