### ISSUE TITLE
(NSFW=후방 주의) 헬븐넷 광고가 차단되지 않고 있습니다. (캡처는 크롬 브라우저, 타 브라우저나 안드로이드에서도 증세 동일)

### ISSUE THREAD

**Issue by 115dkk** [yous/YousList#61]
![hellven ads in homepage](https://user-images.githubusercontent.com/33408534/47690504-a4220000-dc31-11e8-929f-1b4b267503b9.PNG)

이 광고들이 차단되지 않는 문제점이 있습니다.

Adguard 측에도 문의했으나, 조금 반응이 늦어지는 감도 있고 해서 여기에도 올려봅니다.

'이 웹사이트에서 광고 차단'을 이용하면 차단 자체는 가능하지만, 로그인 창과 세부 게시판에서 일일이 차단을 다시 진행해야 하므로 상당히 불편합니다.

광고가 게시된 사이트 링크: [https://hellven.net/](url)

그리고 각각 광고의 링크 주소는 다음과 같습니다.

위쪽:[https://hellven.net/bbs/adver_link.php?ad_no=1&nm=1](url)
아랫쪽:[https://www.mt-police.com/](url)

**Comment by 115dkk** [comment]
Adguard 측에 문의한 것이 먼저 적용되어 English 필터에서 처리되었습니다. 코드는 이 링크에 있습니다.

https://github.com/AdguardTeam/AdguardFilters/commit/15b871335f31ab5b2147f5e3119b7869c4d2e2e4

**Comment by yous** [comment]
제보 감사합니다. 곧 업데이트 하도록 하겠습니다.

**Comment by yous** [comment]
<https://github.com/yous/YousList/commit/282371d5561f620dd6e8be69ff43a8a39d670b02>에서 업데이트 했습니다. 추가로 광고가 보이면 언제든지 제보 주세요.
