### ISSUE TITLE
루리웹 모바일 광고가 차단되지 않았습니다.

### ISSUE THREAD

**Issue by 115dkk** [yous/YousList#62]
http://imgur.com/a/YsH9QTy

루리웹 모바일 하단 광고가 지금 차단되지 않고 있습니다.

현재 Adguard 안드로이드 버전입니다.

만약 표시되지 않은 경우 댓글로 알려주시기 바랍니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 해당 광고의 경우 `m.ruliweb.com##div.ad_wrapper` 필터로 차단되고 있는 것 같은데 혹시 업데이트 확인 가능하신가요? 사용 중인 다른 필터 목록도 알려주시면 감사하겠습니다. 추가로 해당 광고를 로드하는 스크립트를 차단하도록 업데이트했습니다. https://github.com/yous/YousList/commit/2d6b1cbc5f172f19fd19865305ea2c4728b5a241

**Comment by 115dkk** [comment]
필터는 최신이지만(업데이트 시도하니 최신이라 뜹니다.) 차단되지 않았습니다. 필터 목록은 다음과 같습니다.

영어 필터
모바일 필터
스파이웨어 필터
Annoyance 필터
단순화된 도메인 네임 필터(DNS 기반 차단도 사용 중)
일본 필터
Youslist

이렇게 쓰고 있습니다.

**Comment by 115dkk** [comment]
엇... 이제 차단됐습니다. 자동 업데이트로 모르는 새에 업데이트 된 것 같습니다.

**Comment by yous** [comment]
확인 감사합니다. 광고가 보이는 곳을 발견하거나 버그가 있는 것 같으면 언제든지 제보해주세요.

**Comment by 115dkk** [comment]
지금 광고 차단되었습니다. 감사합니다.
