### ISSUE TITLE
(후방주의) 히요비 사이트의 광고가 차단되지 않습니다.

### ISSUE THREAD

**Issue by 115dkk** [yous/YousList#65]
Adguard는 따로 표시가 필요해보이기에 그런 표시 없이 접근할 수 있을 것으로 기대되는 여기에 먼저 올립니다.

스크린샷 링크: http://imgur.com/a/cIrkaee

사이트 링크:https://hiyobi.me

**Comment by yous** [comment]
제보 감사합니다. 
https://github.com/yous/YousList/commit/90b03453c38a1d6e7cb957a74cc5dbe5c12e01fd 커밋에서 업데이트 했습니다. AdGuard에는 1~2시간 후에 업데이트 확인하면 적용될 것 같습니다. 광고가 보이면 언제든지 제보해 주세요.
