### ISSUE TITLE
findtorrent.net 유튜브 비디오 차단

### ISSUE THREAD

**Issue by nskzhd** [yous/YousList#66]
https://findtorrent.net 에서 백그라운드로 유튜브 비디오가 재생됩니다.
차단 가능하면 부탁드려봅니다. 감사합니다.

**Comment by yous** [comment]
제보 감사합니다. https://github.com/yous/YousList/commit/c56b2345d4dda7ecaf099b0bd4c16eea2729c110 커밋에서 업데이트 했습니다.

**Comment by nskzhd** [comment]
항상 감사드립니다. :)
