### ISSUE TITLE
(후방주의) 저번에 알려드린 히요비 사이트에서 차단되지 않은 광고가 나옵니다.

### ISSUE THREAD

**Issue by 115dkk** [yous/YousList#68]
링크: https://hiyobi.me

헬븐넷 광고에서 봤을 X냥몰 광고가 차단되지 않고 있습니다.

여기서 차단된 것을 인식했는지는 알 수 없습니다. 아닐거라고 보지만요.

**Comment by yous** [comment]
제보 감사합니다. https://github.com/yous/YousList/commit/a53070da69acf4f63f1fb58f090c96c87c5d3044 커밋에서 업데이트 했습니다.
