### ISSUE TITLE
모바일 버전 /네이버 메인 광고들이 안없어져요;; 

### ISSUE THREAD

**Issue by giiga0303** [yous/YousList#69]
그 주먹왕 랄프 를 시작으로 밑에 생기는 광고들이 사라지 않ㅇ네요;;

나름 다른 프로글매으로 표면 필터?나 필터 찾아서 적용을 해봤는데 안없어져요;;

||ssl.pstatic.net/tveta/libs/1211/1211755/*_*.jpg
||ssl.pstatic.net/tveta/libs/*/*/*_*.jpg
 ###nbp_da_img

브라우저는 모바일 웨일 사용하구 있구요
폰 기종은 g6 / 오레오 입니다..

pc에서는 잘 없어지는데 모바일은 왜 안없어지는 건가요?

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. AdGuard Pro 사용 중이신가요?
어떤 광고인지 잘 모르겠는데 혹시 스크린샷 올려주실 수 있을까요?

**Comment by yous** [comment]
저 광고의 경우 이미 추가되어 있는 아래 필터를 통해 차단되어야 할 것으로 보이는데, 차단이 되지 않고 있는 것 같습니다. 혹시 다른 브라우저에서도 시도해 보셨나요?
```
m.naver.com##div[data-da]
```

**Comment by giiga0303** [comment]
아 웨일브라우저에서만 그런것 같습니다;;;
엣지 브라우저에서는 광고가 사라져있네요
브라우저 문제인 듯 합니다...

**Comment by yous** [comment]
네, 확인 감사합니다. 필터 문제라기보단 안드로이드나 AdGuard 문제인 것 같으니 일단 닫겠습니다. 광고가 보이면 언제든지 제보해주세요. 감사합니다.
