### ISSUE TITLE
다음 뉴스 동영상이 광고차단에 막혀서 아무것도 나오지 않습니다.

### ISSUE THREAD

**Issue by webzeroacs** [yous/YousList#71]
다음 뉴스 동영상이 광고차단에 막혀서 아무것도 나오지 않습니다.
확인한 필터내용은 
||imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=~download.cnet.com
 에서 차단 되었다고 나옵니다.

@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=kakaotv.daum.net

@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=tv.kakao.com

를 예외조항으로 넣으주니 정상적으로 작동 하는것을 확인 하였습니다.

**Comment by yous** [comment]
제보 감사합니다. 혹시 동영상이 포함된 뉴스 링크 하나만 알 수 있을까요? 곧 확인해 보겠습니다.

**Comment by webzeroacs** [comment]
https://news.v.daum.net/v/20190104201207708
다음 뉴스 동영상 링크 입니다.

**Comment by yous** [comment]
제보 감사합니다. 해당 스크립트는 막지 않는 것이 맞다고 판단해서 해당 규칙을 삭제했습니다.
b1389e3cce5e4ea24dbd885a679b0ca79757c94d 커밋에서 업데이트했습니다.
