### ISSUE TITLE
점신 어플 광고 차단 질문이요

### ISSUE THREAD

**Issue by giiga0303** [yous/YousList#72]
https://play.google.com/store/apps/details?id=handasoft.mobile.divination
점신은 사주를 보는 어플입니다
되도록이면 개별어플 광고차단은 요청보다는

필터링 로그 보면서 개인 필터로 차단을하려고 노력을
하는데 이 어플은 힘드네요 ㅜ ㅜ
올려진 광고 이외에 몇 개가 더 나옵니다

애드가드의 한계인지 제 노력의 한계인지ㅜ ㅜ

![screenshot_2019-01-05-09-21-52](https://user-images.githubusercontent.com/38028863/50717674-ee37bf80-1080-11e9-9fd2-9c46e533085f.png)
![screenshot_2019-01-05-09-23-53](https://user-images.githubusercontent.com/38028863/50717677-f132b000-1080-11e9-8fdd-c318f2e33a6d.png)
![screenshot_2019-01-05-09-24-20](https://user-images.githubusercontent.com/38028863/50717680-f4c63700-1080-11e9-88e3-f7dd1d34ce1e.png)

**Comment by giiga0303** [comment]
아 이건 dns 기능을 켜야 하나 보군요
답변 감솨합니다

**Comment by giiga0303** [comment]
아 dns를 켜야 하나보군요

이걸 키지 않으면 점신 광고를 못 막는건가요?

**Comment by yous** [comment]
안녕하세요, https://github.com/yous/YousList/commit/b260b69f276182566525cfca3a743901d62c18de 커밋에서 점신 광고를 업데이트 해두었습니다. 다만 빈 화면을 막을 수는 없어서 완벽하지 않으니 참고 바랍니다. 앱 자체에서 앱 내 결제를 통해 광고 제거 기능을 제공하고 있으니 가장 확실한 방법은 결제하는 것입니다.

추가로, 안드로이드 누가 이후의 버전에서는 앱마다 HTTPS 필터링이 제대로 되지 않는 경우가 많은 것 같습니다. 다음 화면은 안드로이드 킷캣 버전에서 캡처한 것입니다. <https://github.com/yous/YousList/issues/63#issuecomment-443259288> 해당 앱의 필터링 로그를 봤을 때 이 화면처럼 URL이 끝까지 나오면 필터링이 가능하지만, 그렇지 않고 도메인 이름만 나온다면 필터링에 한계가 있습니다. 도메인 필터로만 만들게 되면 아무래도 다른 것도 차단될 가능성이 높아서 따로 만들고 있지는 않습니다. 이때는 개인 필터를 활용하시는 게 좋을 것 같습니다.

**Comment by giiga0303** [comment]
답변 감사합니다!! 
항상 행복하시고 새해 복 많이 받으세요!!
