### ISSUE TITLE
크롬브라우저에서 네이버tv 재생이 안됩니다

### ISSUE THREAD

**Issue by sh2o0207** [yous/YousList#74]
https://tv.naver.com/
여기서는 시청이 되는데

어떤영상을 다른 사이트에 링크걸고 그사이트에서 시청하려는데 재생이 안되네요

https://www.fmkorea.com/1509195527#comment_1509310516

여기서는 무한 로딩중이네요

확인부탁드립니다

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다.
혹시 다른 필터도 사용하고 계신가요? 어떤 필터를 사용 중인지 알려주시면 감사하겠습니다. 현재 YousList만 활성화한 상태에서 봤을 땐 괜찮은 것 같습니다.

**Comment by sh2o0207** [comment]
앗 그러네요 
다른거 다 꺼보고 실행할 생각을 못했네요
링크공유버튼도 활성화되네요.
원래 안됐었는데..

제가 사용하는건

영어필터
스파이웨어필터
소셜미디어필더
annoyance 필터
adblock warning removal list
(obsolete)anti-adblock killer l reek
nocoin filter list
유용한 광고 필터
단순화된 도메인 네임필터
일본필터 


입니다

답변 감사합니다

**Comment by webzeroacs** [comment]
기본 필터 인 영어, 스파이웨어,소셜미디어 필터 와 단순화된 도메인 네임 필터 제외한
나머지는 일단 꺼두고 시도 해보세요.
해보시고 하나씩 켜서 시도 해보시면 어떤 필터가 문제가 되는지 알지 싶네요.

**Comment by sh2o0207** [comment]
문의했던 타사이트 링크영상은 되는데
지금 네이버 축구 중계가 안되네요..

다끄고 youslist만 켜니까 안됩니다

**Comment by yous** [comment]
확인했습니다. https://github.com/yous/YousList/commit/fa0d6be3718418f62702fa856bee6ae35fa410e4 커밋에서 업데이트했습니다.

사용자 필터에 다음 규칙을 추가해보세요. 업데이트 적용되는 건 한 시간 정도 걸릴 것 같습니다.
```
||vod-naver.pstatic.net/tveta/owfs_rmc/read/$domain=~sports.news.naver.com
```

**Comment by yous** [comment]
일단 이 이슈는 닫겠습니다. 혹시 또 재생이 안 된다면 언제든 제보해주세요. 감사합니다.
