### ISSUE TITLE
네이버 카페 모바일 페이지 광고

### ISSUE THREAD

**Issue by newget** [yous/YousList#76]
![screenshot_20190130-210540__](https://user-images.githubusercontent.com/3542715/51980359-2640ef80-24d3-11e9-82c3-d61694175d6f.png)

https://m.cafe.naver.com/ArticleRead.nhn?clubid=26620492&articleid=4330&boardtype=L&referrerAllArticles=true&menutype=B&wCmt=true&commentCount=0&commentNew=false&rClick=false

삼성 인터넷 베타버전에 Adguard(기본 영어 필터 등과 Youslist)를 사용중입니다.

스크린샷을 찍고 다른 페이지도 들어가보고 다시 광고 뜨던 페이지로 돌아와보니 광고가 없었습니다.
필터에는 있으나 잠시 오류로 차단이 안 되었던건지, 아니면 필터에 아예 없는건진 잘 모르겠습니다.

**Comment by yous** [comment]
안녕하세요, 네이버 카페 모바일 페이지의 경우 다음 규칙이 추가되어 있습니다.

```
m.cafe.naver.com##div.area_sa
```

다른 카페에서 확인해보니 동일한 위치에 해당 요소가 존재해서 브라우저에서 가려지고 있는데, AdGuard의 문제인지 브라우저의 문제인지는 정확하지 않습니다. 일단은 이슈가 재현되지 않는 것 같아 닫습니다.

해당 광고가 또 보이거나 다른 광고가 보이면 언제든지 제보해주세요. 감사합니다.
