### ISSUE TITLE
Add purpose of this list to README.MD

### ISSUE THREAD

**Issue by Gitoffthelawn** [yous/YousList#77]
Can you add the purpose of this list to README.MD?

For example, how does this list differ from other filter lists?

What is the goal of this filter list?

Thanks!

**Comment by yous** [comment]
Thanks for pointing this out.

This filter focuses on blocking advertisements mainly on Korean sites. But I don't restrict the target sites. I get reports from Adblock Plus and GitHub, and blocks advertisements wherever the site is.

**Comment by Gitoffthelawn** [comment]
You're welcome.  And thank you!
