### ISSUE TITLE
네이버 광고

### ISSUE THREAD

**Issue by mireado** [yous/YousList#8]
||nv2.veta.naver.com/dr
||nv1.veta.naver.com/dr
naver.com###veta_branding
naver.com###veta_top

==
pull request로 할려고했는데..
checksum 만드는 방법을 모르겠네요;

**Comment by yous** [comment]
안녕하세요, 제보 감사드립니다. 체크섬의 경우 Vim 플러그인 [adblock-filter.vim](https://github.com/mojako/adblock-filter.vim)을 사용하고 있습니다. 코드에 반영했으니 확인 부탁드립니다.
