### ISSUE TITLE
모바일 이토렌트 광고가 나오네요

### ISSUE THREAD

**Issue by giiga0303** [yous/YousList#80]
![screenshot_2019-03-05-22-15-54](https://user-images.githubusercontent.com/38028863/53808167-e61ed200-3f94-11e9-84c8-b42fb5c0b196.png)
모바일 이토렌트 유머게시판
광고가 안사라져요
https는 켰구요 dns는 안 켰습니다
http://www.etobang.co.kr/plugin/mobile/board.php?bo_table=etohumor01

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 모바일 기기에서 광고 나오는 것 확인했습니다. 곧 업데이트 하도록 하겠습니다.

**Comment by yous** [comment]
63fafed 커밋에서 업데이트했습니다.
