### ISSUE TITLE
allvod.sbs.co.kr 차단 안되는 문제

### ISSUE THREAD

**Issue by mimiya1000** [yous/YousList#82]
애드가드를 키면 광고는 안보이는데 재생이 안되고 검은화면만 뜹니다
해결 가능할까요?

http://allvod.sbs.co.kr/allvod/vodEndPage.do?mdaId=22000004081&btn=free

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 광고를 불러오지 않으면 재생이 안 되어 https://github.com/yous/YousList/commit/b0bf085a2bb35f572f86b663eab80db28e0fd3c4 커밋에서 광고를 허용해 두었습니다.
