### ISSUE TITLE
mangashowme 광고차단

### ISSUE THREAD

**Issue by newget** [yous/YousList#83]
https차단때문에 해당 사이트가 도메인을 자주 바꿔서 필터에 있는 mangashow.me##div.banner 가 제대로 작동을 안 합니다.

mangashow2.me, mangashow3.me, mangashow5.me까지 추가되었는데 혹시 mangashow*.me나 mangashow?.me도 적용되나해서 해보았는데 와일드카드는 적용이 안 되는 것 같네요.

일단 mangashow5.me##div.banner를 추가하니 광고는 사라졌습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/7a2b007893fc0a76ff0aa8d14f6c3f5407ffcb52 커밋에서 업데이트했습니다.
