### ISSUE TITLE
정말로 죄송하다만..

### ISSUE THREAD

**Issue by takid2848** [yous/YousList#84]
![Screenshot_20190317-001914_Adhell3](https://user-images.githubusercontent.com/31562186/54477438-27439b80-484b-11e9-8ae9-9819b780fa69.jpg)
![Screenshot_20190317-002351_Adhell3](https://user-images.githubusercontent.com/31562186/54477439-27439b80-484b-11e9-965d-88caa76e4418.jpg)

Adhell3라고 삼성SDK를 사용하는 광고 차단기가 있는데

이 앱이 방화벽을 사용해서 차단을 해서 "*"나 "*.jpg/jar"따위나 iframe 차단따위를 그냥 무시해버려서 쓸 수가 없습니다.

처음에는 제가 매크로로 수정하려고 했는데 반복성이 없고 매크로를 잘못 사용했다가는(광고 서버와 사이트 서버가 동일한 경우) 몇몇 사이트가 통채로 차단될 것 같은데

인지도(삼성 전용이기도 하고 몰라서)와 접근성(앱을 직접 빌드해야 해서 막힐수도 있습니다.)이 적은 앱이긴 하다만 Adhell용 로그를 만들어 줄 수 있을까요?

다운로드는 여기고

https://gitlab.com/fusionjack/adhell3
(추신적으로 여기서 방법 보면서 직접 빌드해야 합니다; POWERSHELL에러 뜨면 cmd파일 수정해서 wgst를 직접 다운로드 받으셔야 합니다.)

로그 예시는 여기있습니다.

https://www.androidsage.com/2018/06/12/hosts-txt-providers-list-for-adblockers-on-android-phones

왠만해서 이런 글 올리면 안되는건 아는데 지원하는 로그가 너무 적기도 하고 통합 로그 쓰려니까 너무 속도가 느려지기도 해서.. 정말로 죄송하다만 가능할까요?

**Comment by yous** [comment]
안녕하세요, 도메인 차단용 필터는 hosts.txt에 정리해두고 있습니다만, 말씀해주신 것처럼 도메인 전체를 차단해도 괜찮은 경우에만 추가하는 방식으로 만들고 있어서 차단이 완벽하지는 않습니다.

adhell3에서 쓸 수 있는 필터를 만들려면 기존 hosts.txt 파일에서 좀 더 처리를 거쳐야 하나요?

**Comment by takid2848** [comment]
뭔가 이렇게 이야기 하면 안될것 같다만 솔직히 직설적으로 이야기하자면 그 로그로는 광고차단이 거의 안됩니다. 

![Screenshot_20190317-220214_Firefox](https://user-images.githubusercontent.com/31562186/54492918-0728e080-490e-11e9-8ead-2e168a25e7db.jpg)

왠만한 사이트는 다 들어가봤는데 되는게 거의 없었습니다.

**Comment by takid2848** [comment]
![이미지 002](https://user-images.githubusercontent.com/31562186/54492953-52db8a00-490e-11e9-8d43-317fb14165c5.png)
그냥 제 생각인데

! URL filters 부분을 사용하는게 제일 가능성 있어 보입니다. 아직 테스트는 못했는데 불안한게 광고 서버와 실제 사이트 서버가 겹친는 부분이 있을까봐 좀..

이참에 물어보는데 광고서버하고 실제 사이트 서버하고 같은 경우가 있었나요..?

**Comment by yous** [comment]
현재 hosts.txt가 굉장히 보수적으로 작성되어 있는 것은 사실입니다. URL 필터 중에 서드 파티로 광고를 로드하는 데에만 쓰이는 도메인만 추려서 hosts.txt에 추가하는 작업이 필요할 것 같네요.

위의 `101.livere.co.kr` 같은 경우로 예를 들자면, 기본적으로 `101.livere.co.kr` 아래의 js 등을 통해 뉴스 댓글을 로드하는 데 사용되고, 위의 `/coinone-ad/coinone-ad-widget.html` 같은 경우는 댓글과 함께 보이는 광고 iframe 주소라고 보시면 될 것 같습니다. 그래서 `101.livere.co.kr`을 차단할 수 없고, 아마 많은 부분이 그런 식으로 되어 있을 겁니다.

일단은 현재 차단 URL 중에 도메인을 통째로 차단해도 웬만하면 괜찮을 곳들을 추려서 hosts.txt를 업데이트 해보도록 하겠습니다.

**Comment by yous** [comment]
https://github.com/yous/YousList/commit/84ee9e679389314a2b17a9440710952666058e69 커밋에서 hosts.txt에 광고 서버로 보이는 규칙을 더 추가했습니다. 모든 항목을 확인한 것은 아니라서 광고가 아닌데도 차단될 수는 있습니다만, 대부분은 광고일 것이라 판단했습니다.

**Comment by takid2848** [comment]
감사합니다. 아무래도 광고가 안 불러와지면 파이어폭스에서 다시 불러오는 것 같은데 모바일 파이어폭스는 애드가드 확장프로그램 사용이 가능하더군요.. 일단 Adhell3 자체가 상당히 브라우저 광고 차단용으로는 사용하기는 힘들다만 앱 광고 차단정도까지는 잘 해내서 그냥 Adguard 모바일 필터만(앱 차단은 iframe따위로 차단하는게 적어서 앱 차단은 됩니다) 켜두고 파이어폭스는 애드가드나 ublock를 써야겠군요.

**Comment by takid2848** [comment]
여전히 차단이 잘 되지는 않다만 몇개는 차단이 됬습니다. 고생하게 만드셔서 죄송하고 감사합니다.

**Comment by yous** [comment]
네, 앱 차단은 제가 적극적으로 쓰고 있지 않아서 빠진 부분이 있을 것 같은데, 브라우저의 경우엔 uBlock Origin이나 AdGuard로 쾌적하게 사용할 수 있으실 겁니다. 둘 다 필터 목록에 YousList가 있으니 사용하는 데 불편함은 없으실 것 같네요.

다시 한 번 제안 감사드리고, 불편한 점이 있거나 광고가 보이면 제보 주세요. 감사합니다.
