### ISSUE TITLE
모바일환경 네이버웹툰 팝업

### ISSUE THREAD

**Issue by ndaesik** [yous/YousList#85]
모바일 파이어폭스에서도 필터 항상 잘 쓰고 있습니다. 감사합니다.
좌우로 넘기는 컷툰 제일 마지막 페이지에 외부링크로 유도하는 전체화면 광고를 차단하는 필터입니다.

m.comic.naver.com##div.viewer.cuttoon div.ly_wrap
m.comic.naver.com##div.viewer.cuttoon div.ly_dim

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/945be393e8b0309cde1e62de5fece320672ac6a7 커밋에서 업데이트했습니다.
