### ISSUE TITLE
윈도우포럼 광고창 크기

### ISSUE THREAD

**Issue by swan201** [yous/YousList#86]
https://windowsforum.kr/

배너 광고가 차단은되나 레이아웃이 제거 되지 않습니다. 해당문제 해결이 가능할까요?

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 해당 사이트는 https://github.com/yous/YousList/commit/60eb9aa25ef33bb044d78820aac1ce0d906147bf 커밋에서 업데이트했습니다. 앞으로도 광고가 보이거나 이상한 점이 있으면 제보해주세요. 감사합니다.
