### ISSUE TITLE
퀘이사존 기능 문제

### ISSUE THREAD

**Issue by Droiyan7** [yous/YousList#87]
윈도우10 - 파이어폭스 66버전 - uBlock Origin으로 사용 중입니다.

https://quasarzone.co.kr/ : 특정 광고박스에 사이트 기능이 연동되어 있어서 광고 차단 시 해당 기능을 쓸 수 없게 바뀌었습니다.

배너 광고(붉은색 박스 부분) 차단 시 내 글/댓글 등 확인하는 부분(노란색 박스 부분)이 먹통이 됩니다.
![](https://i.imgur.com/u3JbQcO.jpg)

![](https://i.imgur.com/xyT9vf4.png)

덧: 왼쪽 광고(파란색 박스 부분) 차단 추가해 주실 수 있으신가요? 차단 자체는 쉬운데 빈 공간으로 남아서, 저거 없이 깔끔하게 차단 추가해 주시면 감사하겠습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. 일단 오른쪽 광고 박스 자체를 가리지는 않도록 하고, 나머지 부분에 대해 https://github.com/yous/YousList/commit/2da2054c10229941a886bfdd0649177dacb0074f 커밋에서 업데이트했습니다. 업데이트해서 한번 기능이 제대로 동작하는지 확인해주세요. 제가 사이트에 아이디는 따로 없어서 직접 확인하기가 어렵네요.

**Comment by Droiyan7** [comment]
예. 현재 기능은 제대로 잘 됩니다. 감사합니다.

덧: 왼쪽 광고 차단하고 남는 빈공간도 없앨 수 있는지 알아봐 주시면 좋겠습니다. ^^/*

**Comment by yous** [comment]
확인 감사합니다. 왼쪽 사이드바 부분은 봤는데 가운데 콘텐츠 자체가 처음부터 왼쪽 여백을 두도록 되어 있어서 왼쪽 영역을 가려도 가운데 콘텐츠 자리가 변경되지 않는 것 같습니다. 이 부분은 차단 스크립트로 조정하기는 어려울 것 같습니다.

**Comment by yous** [comment]
일단 이 이슈는 닫겠습니다. 혹시 다른 광고가 보이거나 기능이 동작하지 않으면 언제든 제보해주세요. 감사합니다.
