### ISSUE TITLE
뽐뿌 파워링크

### ISSUE THREAD

**Issue by xeleven11** [yous/YousList#88]
뽐뿌에서 검색하면 파워링크 광고가 자꾸 뜨네요.

**Comment by yous** [comment]
제보 감사합니다. https://github.com/yous/YousList/commit/1ee44c8e947af923ac25e3ce4d14525f1768d248 커밋에서 업데이트했습니다.

**Comment by xeleven11** [comment]
업데이트 하고 난 이후 광고 안 떴는데 뽐뿌에서 애드블록 감지를 해서 그런지 광고가 지금 보이네요.

**Comment by yous** [comment]
안녕하세요, 제가 찾기가 어려워서 그런데 혹시 광고가 보이는 URL 하나만 알려주실 수 있을까요?

**Comment by xeleven11** [comment]
[http://www.ppomppu.co.kr/zboard/zboard.php?id=phone&page_num=30&category=&search_type=sub_memo&keyword=5g](url) 검색창 안에 아무거나 검색하면 자꾸 광고 뜨더라고요. ublock Origin 이용중이에요

**Comment by yous** [comment]
감사합니다. https://github.com/yous/YousList/commit/b9f20231060b9b22c1cf19c59c4e4bc40f49c118 커밋에서 업데이트했으니 확인해보시기 바랍니다.
