### ISSUE TITLE
티빙 다시보기시 30초 광고

### ISSUE THREAD

**Issue by DandyClubs** [yous/YousList#89]
티빙에서 다시보기 들어가면 30초짜리 광고가 나옵니다.

그런데
영어필터에서 

/* SUMMARY REQUEST INFO */

Request URL: http://adverweb.cjenm.com/vod.mezzo/20190401131641/1280/720
Remote Address: 14.34.8.217:80
Source URL: http://www.tving.com/vod/player/E002251317
Process name: chrome.exe
Process ID: 8908
Connection ID: 16216178
Status: Blocked
Content type: Other
Protocol type: Tcp
Start time: 10:07:25.2641
Time: 1 ms
Size: 41.0 KB
Request Method: GET
Status code: 500 Request Blocked
규칙:
 영어 필터: /adverweb.

/adverweb. 부분을 차단하면 광고는 안나오는데.. 영상도 안나옵니다.

그래서 /adverweb.를 티빙에서는 허용하면 광고가 나옵니다. 광고 끝나고 영상도 나오고요. 

어떻게 하면 광고만 차단할 수 있을까요?

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/a32bac38aa0fc63eb114422e49688103342348b8 커밋에서 업데이트했으니 확인해보시기 바랍니다.

**Comment by DandyClubs** [comment]
파폭 크롬 둘 다 잘 작동하네요.

감사합니다.

**Comment by yous** [comment]
이 이슈는 닫겠습니다. 다른 광고가 보이면 언제든 제보해주세요.
