### ISSUE TITLE
필터를 키면 구글 수정된 검색창이 띄지 않습니다.

### ISSUE THREAD

**Issue by tjtnsgns** [yous/YousList#91]
![Screenshot_20190408-213252_Samsung Internet](https://user-images.githubusercontent.com/28147257/55724655-dc323800-5a46-11e9-939f-9307861eae1a.jpg)
![Screenshot_20190408-213035_Firefox Beta](https://user-images.githubusercontent.com/28147257/55724665-e0f6ec00-5a46-11e9-9aa6-a6df0c67b97a.jpg)
위와 같이 필터를 키면 구글 검색시 오타나 잘못된 검색어를 자동으로 수정해주는 데 수정되어다는 창이 띄지 않습니다.

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/7cbceec3f6d037ca7ad5f5bb3feb52fc7139a6f8 커밋에서 업데이트했습니다.
