### ISSUE TITLE
아프리카TV 배너광고

### ISSUE THREAD

**Issue by swan201** [yous/YousList#94]
![image](https://user-images.githubusercontent.com/12713262/56104816-51849800-5f74-11e9-9ab7-55acec5c7996.png)

![image](https://user-images.githubusercontent.com/12713262/56104829-63663b00-5f74-11e9-80dc-252e9442ee23.png)

해당 주소 삭제시 광고가 없어지는걸 확인했습니다. 업데이트 가능할까요

**Comment by yous** [comment]
안녕하세요, 제보 감사합니다. https://github.com/yous/YousList/commit/e2650a1cdc2fc27c43401fb30f4353d649dda1e1 커밋에서 업데이트했습니다.
