### ISSUE TITLE
아프리카TV 안드로이드 APP VOD 광고차단

### ISSUE THREAD

**Issue by bobblun** [yous/YousList#96]
||mtag.mman.kr^

필터 추가시 광고차단이 되는것을 확인했습니다
추가 부탁드립니다

**Comment by bobblun** [comment]
추가가 되어있는것 같네요  일단 닫아두겠습니다

**Comment by yous** [comment]
안드로이드에서 잘 차단이 되지 않는다면 아마도 AdGuard 등에서 전체 URL을 필터링하지 못해서 그런 것일 수 있습니다. https://github.com/yous/YousList/issues/63#issuecomment-443976473 등을 보시면 안드로이드 7.0부터 HTTPS 차단 기능이 일부 제한된 것 같고요, 이 경우엔 전체 URL은 안 보이지만 도메인은 보입니다. 그래서 `||mtag.mman.kr^` 등의 규칙으로 도메인 전체를 차단하면 광고가 차단됩니다.

광고 사이트 도메인 목록은 [hosts.txt](https://github.com/yous/YousList/blob/master/hosts.txt)에 정리하고 있으니 필요하다면 사용해주시기 바랍니다.
