### ISSUE TITLE
pcgames.de - mobile client

### ISSUE THREAD

**Issue by BlazDT** [yous/YousList#98]
When viewing pcgames.de on a mobile device and clicking on a link, it won't work.

Required rule:

@@||script.ioam.de/iam.js$domain=pcgames.de

**Comment by yous** [comment]
Thanks for the reporting! I'll fix it soon.

**Comment by yous** [comment]
Updated via https://github.com/yous/YousList/commit/333f7664d307f8986f705ee5915ff5713a4a9bde.

**Comment by yous** [comment]
Closing. Please feel free to open a new issue when you see advertisements or have some problems.
