### ISSUE TITLE
news.tvchosun.com - broken video

### ISSUE THREAD

**Issue by BlazDT** [yous/YousList#99]
https://github.com/AdguardTeam/AdguardFilters/issues/32799

When trying to play the video with YousList active, you will only get this error:

<img width="500" alt="youslist" src="https://user-images.githubusercontent.com/34266271/56460258-32d13780-63a0-11e9-9702-af45012474d3.png">

Culprit rule:
||smrmembers-smr.smartmediarep.com/smc/smrmembers/$domain=~allvod.sbs.co.kr|~news.sbs.co.kr|~programs.sbs.co.kr

When replacing the ad video with a very short one, the player works.

**Comment by yous** [comment]
I looked into <http://img.tvchosun.com/upload_img/n2017/js/flowplayer.customizing.all_in_one.min.js>, and I think it would work when the response of either `http://openapi.tvchosun.com/player/smrAdvLive.cstv` or `http://openapi.tvchosun.com/player/smrAdv.cstv` contains "error":
``` json
{ "response": "error", "error": 3, "message": "" }
```

But it can't be done without using extended syntaxes as just blocking `*.cstv`s disables the player. So I'll just add an exception for news.tvchosun.com. It's updated via https://github.com/yous/YousList/commit/82505ce57e9e22ce35c1ea4953de3e37f38582c5.

I think you can make custom response for that specific `*.cstv` URLs. When you make working rules, please give an example here to let people know.

**Comment by BlazDT** [comment]
The ad video is fixed for AdGuard main products already (replaced ad video):
```
||smrmembers-smr.smartmediarep.com/smc/smrmembers^$mp4,important
||cdnprism.pandora.tv/_adv_img^$domain=tvchosun.com,mp4,important
```

**Comment by yous** [comment]
Thanks for letting me know.

It seems that uBlock Origin also has similar feature called [`redirect`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect), but Adblock Plus' [`redirect`](https://adblockplus.org/filters#options) seems quite different. Currently I don't use extended syntaxes that aren't available for every blocker. Closing.
